const CATEGORY = {
  CLI_AGENT: "cli-agent",
  IDE: "ide",
  DESKTOP_CHAT: "desktop-chat",
  CLOUD_CHAT: "cloud-chat",
  RUNTIME: "runtime",
  PLATFORM: "platform",
  EXTENSION: "extension",
};

const SIGNATURES = [
  {
    id: "claude-code",
    name: "Claude Code",
    vendor: "Anthropic",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["claude code", "claude-code", "claudecode", "claude cli"],
    processes: ["claude", "claude.exe", "claude-code", "claude-code-acp"],
    npm: ["@anthropic-ai/claude-code"],
    roamingDirs: [],
    localDirs: ["claude-cli-nodejs"],
    homeDirs: [".claude", ".claude-code-router", ".claude-server-commander"],
    installPaths: [
      "%LOCALAPPDATA%/Programs/claude",
      "%APPDATA%/npm/claude.cmd",
      "%LOCALAPPDATA%/fnm_multishells",
    ],
    cli: { cmd: "claude", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.claude/projects",
      recentCwd: "encoded-project-dir",
      currentTask: "last-user-message",
    },
  },
  {
    id: "claude-desktop",
    name: "Claude Desktop",
    vendor: "Anthropic",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["claude desktop"],
    processes: ["claude"],
    npm: [],
    roamingDirs: ["Claude", "claude-desktop"],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/claude-desktop" },
  },
  {
    id: "codex-cli",
    name: "Codex CLI",
    vendor: "OpenAI",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["codex cli", "codex", "openai codex", "codex-acp"],
    processes: ["codex", "codex.exe"],
    npm: ["@openai/codex", "@zed-industries/codex-acp"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".codex"],
    installPaths: ["%APPDATA%/npm/codex.cmd"],
    cli: { cmd: "codex", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.codex/sessions",
      recentCwd: "jsonl-cwd",
      currentTask: "last-user-message",
    },
  },
  {
    id: "gemini-cli",
    name: "Gemini CLI",
    vendor: "Google",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["gemini cli", "gemini", "google gemini"],
    processes: ["gemini"],
    npm: ["@google/gemini-cli"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".gemini"],
    installPaths: ["%APPDATA%/npm/gemini.cmd"],
    cli: { cmd: "gemini", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.gemini/sessions",
      recentCwd: "jsonl-cwd",
      currentTask: "last-user-message",
    },
  },
  {
    id: "qwen-code",
    name: "Qwen Code",
    vendor: "Alibaba",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["qwen code", "qwen-code", "qwen cli", "qwen"],
    processes: ["qwen"],
    npm: ["@qwen-code/qwen-code"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".qwen", ".qwenpaw", ".qwen-test-output"],
    installPaths: ["%APPDATA%/npm/qwen.cmd"],
    cli: { cmd: "qwen", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.qwen/projects",
      recentCwd: "encoded-project-dir",
      currentTask: "last-user-message",
    },
  },
  {
    id: "qwen-work-cn",
    name: "千问办公",
    vendor: "Alibaba",
    tier: 1,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["qwenworkcn", "qwen work", "千问办公", "qwenwork cn"],
    processes: ["qwenworkcn", "launcher"],
    npm: [],
    roamingDirs: ["QwenWorkCN"],
    localDirs: ["qwen-work-cn-updater"],
    homeDirs: [".qwenworkcn"],
    installPaths: ["%PROGRAMFILES%/QwenWorkCN", "%LOCALAPPDATA%/QwenWorkCN"],
    session: { type: "electron", root: "%APPDATA%/QwenWorkCN" },
  },
  {
    id: "iflow-cli",
    name: "iFlow CLI",
    vendor: "iFlytek",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["iflow", "iflow cli", "iflow-cli"],
    processes: ["iflow"],
    npm: ["@iflow-ai/iflow-cli"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".iflow", ".iflow-bot"],
    installPaths: ["%APPDATA%/npm/iflow.cmd"],
    cli: { cmd: "iflow", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.iflow/projects",
      recentCwd: "encoded-project-dir",
      currentTask: "last-user-message",
    },
  },
  {
    id: "kilocode",
    name: "Kilo Code",
    vendor: "KiloCode",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["kilo code", "kilocode", "kilo"],
    processes: ["kilo", "kilocode"],
    npm: ["@kilocode/cli"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".kilocode"],
    installPaths: ["%APPDATA%/npm/kilo.cmd"],
    cli: { cmd: "kilo", args: ["--version"] },
    session: { type: "jsonl", root: "~/.kilocode" },
  },
  {
    id: "opencode",
    name: "OpenCode",
    vendor: "OpenCode",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["opencode", "open code", "opencode desktop"],
    processes: ["opencode"],
    npm: ["opencode-ai", "oh-my-opencode"],
    roamingDirs: ["ai.opencode.desktop"],
    localDirs: ["OpenCode", "ai.opencode.desktop", "oh-my-opencode"],
    homeDirs: [".opencode"],
    installPaths: ["%LOCALAPPDATA%/OpenCode"],
    cli: { cmd: "opencode", args: ["--version"] },
    session: {
      type: "opencode-storage",
      root: "~/.local/share/opencode/storage/session",
      recentCwd: "opencode-directory",
      currentTask: "opencode-title",
    },
  },
  {
    id: "qoder",
    name: "Qoder",
    vendor: "Alibaba",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["qoder", "qodercli"],
    processes: ["qoder"],
    npm: ["@qoder-ai/qodercli"],
    roamingDirs: ["Qoder", "com.qoder.app.stable"],
    localDirs: ["Qoder", "qoder-updater"],
    homeDirs: [".qoder", ".qoder-cli", ".qoder-cn", ".qodercli", ".qmind"],
    installPaths: ["%LOCALAPPDATA%/Qoder"],
    cli: { cmd: "qoder", args: ["--version"] },
    session: {
      type: "vscdb",
      root: "%APPDATA%/Qoder/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "codebuddy",
    name: "CodeBuddy",
    vendor: "Tencent",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["codebuddy", "codebuddy cn"],
    processes: ["codebuddy"],
    npm: ["@tencent-ai/codebuddy-code"],
    roamingDirs: ["CodeBuddy CN"],
    localDirs: ["CodeBuddyExtension"],
    homeDirs: [".codebuddy"],
    installPaths: ["%LOCALAPPDATA%/Programs/CodeBuddy CN"],
    cli: { cmd: "codebuddy", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.codebuddy/conversations",
      recentCwd: "jsonl-cwd",
      currentTask: "last-user-message",
    },
  },
  {
    id: "coze",
    name: "Coze 扣子",
    vendor: "ByteDance",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["coze", "扣子"],
    processes: ["coze"],
    npm: ["@coze/cli"],
    roamingDirs: ["Coze"],
    localDirs: ["coze-updater"],
    homeDirs: [".coze"],
    installPaths: ["%PROGRAMFILES%/Coze"],
    session: { type: "electron", root: "%APPDATA%/Coze" },
  },
  {
    id: "cursor",
    name: "Cursor",
    vendor: "Anysphere",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["cursor"],
    processes: ["cursor"],
    npm: [],
    roamingDirs: ["Cursor"],
    localDirs: [],
    homeDirs: [".cursor", ".oldcursor"],
    installPaths: ["E:/cursor"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/Cursor/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "trae-cn",
    name: "Trae CN",
    vendor: "ByteDance",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["trae cn", "trae"],
    processes: ["trae cn"],
    npm: [],
    roamingDirs: ["Trae CN", "Trae"],
    localDirs: [],
    homeDirs: [".trae-cn", ".trae"],
    installPaths: ["%LOCALAPPDATA%/Programs/Trae CN"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/Trae CN/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "trae-solo-cn",
    name: "TRAE SOLO CN",
    vendor: "ByteDance",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["trae solo cn", "traework cn", "trae work", "traework"],
    processes: ["trae solo cn"],
    npm: [],
    roamingDirs: ["TRAE SOLO CN"],
    localDirs: [],
    homeDirs: [".trae-aicc"],
    installPaths: ["%LOCALAPPDATA%/Programs/TRAE SOLO CN"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/TRAE SOLO CN/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "workbuddy",
    name: "WorkBuddy",
    vendor: "Tencent",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["workbuddy", "work buddy", "genie workbuddy"],
    processes: ["workbuddy"],
    npm: [],
    roamingDirs: ["WorkBuddy", "@genie"],
    localDirs: ["WorkBuddy", "WorkBuddyExtension", "@genieworkbuddy-desktop-updater"],
    homeDirs: [".workbuddy"],
    installPaths: ["%PROGRAMFILES%/WorkBuddy"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/WorkBuddy/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "antigravity",
    name: "Antigravity",
    vendor: "Google",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["antigravity"],
    processes: [],
    npm: [],
    roamingDirs: ["Antigravity"],
    localDirs: ["Antigravity", "Antigravity Tools"],
    homeDirs: [".antigravity", ".antigravity_tools"],
    installPaths: ["E:/Antigravity"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/Antigravity/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "kiro",
    name: "Kiro",
    vendor: "AWS",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["kiro"],
    processes: [],
    npm: [],
    roamingDirs: ["Kiro"],
    localDirs: [],
    homeDirs: [],
    installPaths: ["E:/Kiro"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/Kiro/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "zcode",
    name: "ZCode",
    vendor: "ZCode",
    tier: 1,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["zcode"],
    processes: ["zcode"],
    npm: [],
    roamingDirs: ["ZCode"],
    localDirs: ["@zcodedesktop-updater"],
    homeDirs: [".zcode"],
    installPaths: ["%PROGRAMFILES%/ZCode"],
    session: { type: "electron", root: "%APPDATA%/ZCode" },
  },
  {
    id: "today-cn",
    name: "Today",
    vendor: "Today",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["today cn", "todaycn", "today"],
    processes: ["todaycn", "todaywindowsplatformhost"],
    npm: [],
    roamingDirs: ["Today CN"],
    localDirs: ["today-desktop-cn-updater"],
    homeDirs: [],
    installPaths: ["%PROGRAMFILES%/Today CN"],
    session: { type: "electron", root: "%APPDATA%/Today CN" },
  },
  {
    id: "doubao",
    name: "豆包 Doubao",
    vendor: "ByteDance",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["doubao", "豆包"],
    processes: ["doubao"],
    npm: [],
    roamingDirs: ["Doubao"],
    localDirs: ["Doubao", "DoubaoLinkRouter"],
    homeDirs: [".mediakit-doubao"],
    installPaths: ["%LOCALAPPDATA%/Doubao"],
    session: { type: "electron", root: "%APPDATA%/Doubao" },
  },
  {
    id: "kimi",
    name: "Kimi",
    vendor: "Moonshot AI",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["kimi", "kimi desktop"],
    processes: [],
    npm: [],
    roamingDirs: ["kimi", "kimi-desktop"],
    localDirs: ["kimi-code", "kimi-desktop-updater", "KimiAppCache"],
    homeDirs: [".kimi", ".kimi-code", ".kimi-work", ".kimi-webbridge"],
    installPaths: ["%LOCALAPPDATA%/Programs/Kimi"],
    session: { type: "electron", root: "%APPDATA%/kimi" },
  },
  {
    id: "minimax-code",
    name: "MiniMax Code",
    vendor: "MiniMax",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["minimax code", "minimax"],
    processes: ["minimax code"],
    npm: [],
    roamingDirs: ["MiniMax", "MiniMax Agent"],
    localDirs: ["@mmx-agentelectron-updater"],
    homeDirs: [".minimax", ".minimax-agent"],
    installPaths: ["%LOCALAPPDATA%/Programs/MiniMax Code"],
    session: { type: "electron", root: "%APPDATA%/MiniMax Agent" },
  },
  {
    id: "skywork",
    name: "Skywork",
    vendor: "Skywork",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["skywork", "skywork desktop"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: ["skywork-desktop"],
    homeDirs: [".skywork"],
    installPaths: ["%LOCALAPPDATA%/skywork-desktop"],
    session: { type: "electron", root: "%APPDATA%/skywork-desktop" },
  },
  {
    id: "open-design",
    name: "Open Design",
    vendor: "Open Design",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["open design"],
    processes: [],
    npm: [],
    roamingDirs: ["Open Design"],
    localDirs: [],
    homeDirs: [],
    installPaths: ["%LOCALAPPDATA%/Programs/Open Design"],
    session: { type: "electron", root: "%APPDATA%/Open Design" },
  },
  {
    id: "marvis",
    name: "Marvis",
    vendor: "Marvis",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["marvis"],
    processes: ["marvisagent", "marvisassistant", "marvishost", "marvismcp", "marvisdlsvr", "marvisknowledgebase", "marvissvr", "marvis-browser-host"],
    npm: [],
    roamingDirs: [],
    localDirs: ["Marvis"],
    homeDirs: [".marvis", ".mavis"],
    installPaths: ["%LOCALAPPDATA%/Marvis"],
    session: { type: "electron", root: "%APPDATA%/Marvis" },
  },
  {
    id: "cherry-studio",
    name: "Cherry Studio",
    vendor: "CherryHQ",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["cherry studio", "cherrystudio"],
    processes: [],
    npm: [],
    roamingDirs: ["CherryStudio"],
    localDirs: ["cherrystudio-updater"],
    homeDirs: [".cherrystudio"],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/CherryStudio" },
  },
  {
    id: "chatbox",
    name: "Chatbox",
    vendor: "Chatbox",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["chatbox", "xyz.chatboxapp.app"],
    processes: [],
    npm: [],
    roamingDirs: ["xyz.chatboxapp.app"],
    localDirs: ["xyz.chatboxapp.app-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/xyz.chatboxapp.app" },
  },
  {
    id: "deepchat",
    name: "DeepChat",
    vendor: "ThinkInAIX",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["deepchat", "deep chat"],
    processes: [],
    npm: [],
    roamingDirs: ["DeepChat"],
    localDirs: ["deepchat-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/DeepChat" },
  },
  {
    id: "anythingllm",
    name: "AnythingLLM",
    vendor: "Mintplex Labs",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["anythingllm", "anything llm"],
    processes: [],
    npm: [],
    roamingDirs: ["anythingllm-desktop"],
    localDirs: ["anythingllm-desktop-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/anythingllm-desktop" },
  },
  {
    id: "aionui",
    name: "AionUi",
    vendor: "AionUi",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["aionui", "aion ui"],
    processes: [],
    npm: [],
    roamingDirs: ["AionUi"],
    localDirs: ["aionui-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/AionUi" },
  },
  {
    id: "askmanyai",
    name: "AskManyAI",
    vendor: "AskManyAI",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["askmanyai", "ask many ai"],
    processes: [],
    npm: [],
    roamingDirs: ["AskManyAI"],
    localDirs: ["askmanyai-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/AskManyAI" },
  },
  {
    id: "aipy-pro",
    name: "AiPy Pro",
    vendor: "AiPy",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["aipy pro", "aipypro", "aipy"],
    processes: [],
    npm: [],
    roamingDirs: ["aipy-pro"],
    localDirs: ["aipy-pro-updater"],
    homeDirs: [".aipyapp"],
    installPaths: ["E:/AiPyPro"],
    session: { type: "electron", root: "%APPDATA%/aipy-pro" },
  },
  {
    id: "namiai",
    name: "纳米AI",
    vendor: "360",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["namiai", "namiwork", "纳米ai", "nami ai"],
    processes: [],
    npm: [],
    roamingDirs: ["namiwork"],
    localDirs: ["namiwork-image-viewer-updater"],
    homeDirs: [],
    installPaths: ["%PROGRAMFILES%/namiai"],
    session: { type: "electron", root: "%APPDATA%/namiwork" },
  },
  {
    id: "ima-copilot",
    name: "ima.copilot",
    vendor: "Tencent",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["ima.copilot", "ima copilot", "ima"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: ["ima.copilot"],
    homeDirs: [],
    installPaths: ["E:/ima.copilot"],
    session: { type: "electron", root: "%LOCALAPPDATA%/ima.copilot" },
  },
  {
    id: "360-ai-office",
    name: "360AI办公",
    vendor: "360",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["360ai办公", "360 ai", "reader"],
    processes: ["readertray"],
    npm: [],
    roamingDirs: ["Reader"],
    localDirs: [],
    homeDirs: [],
    installPaths: ["%APPDATA%/Reader"],
    session: { type: "electron", root: "%APPDATA%/Reader" },
  },
  {
    id: "quark",
    name: "夸克 Quark",
    vendor: "Alibaba",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["quark", "夸克"],
    processes: [],
    npm: [],
    roamingDirs: ["Quark", "quark-cloud-drive"],
    localDirs: ["Quark", "QuarkMini", "QuarkUpdater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/Quark" },
  },
  {
    id: "memu-bot",
    name: "memU bot",
    vendor: "memU",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["memu bot", "memu-bot"],
    processes: [],
    npm: [],
    roamingDirs: ["memu-bot"],
    localDirs: ["memu-bot-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/memu-bot" },
  },
  {
    id: "qclaw",
    name: "QClaw",
    vendor: "Tencent",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["qclaw"],
    processes: [],
    npm: [],
    roamingDirs: ["QClaw"],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/QClaw" },
  },
  {
    id: "teamo-router",
    name: "TeamoRouter",
    vendor: "Teamo",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["teamorouter", "teamo router"],
    processes: ["teamorouter-desktop"],
    npm: [],
    roamingDirs: [],
    localDirs: ["TeamoRouter", "com.teamolab.teamorouter"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%LOCALAPPDATA%/TeamoRouter" },
  },
  {
    id: "auto-coder-rag",
    name: "AutoCoder RAG",
    vendor: "AutoCoder",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["auto coder rag", "auto-coder-rag"],
    processes: [],
    npm: [],
    roamingDirs: ["auto-coder-rag-desktop"],
    localDirs: ["auto-coder-rag-desktop-updater"],
    homeDirs: [".auto-coder-rag"],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/auto-coder-rag-desktop" },
  },
  {
    id: "grok",
    name: "Grok",
    vendor: "xAI",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["grok", "grok-cli", "grok desktop"],
    processes: ["grok", "grok.exe"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: ["%LOCALAPPDATA%/Programs/Grok", "%APPDATA%/npm/grok.cmd"],
    cli: { cmd: "grok", args: ["--version"] },
    session: { type: "jsonl", root: "~/.grok", recentCwd: "cwd", currentTask: "last-user-message" },
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    vendor: "OpenAI",
    tier: 1,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["chatgpt", "chat-gpt", "openai chatgpt"],
    processes: ["chatgpt", "chatgpt.exe", "chatdesktop"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [
      "%LOCALAPPDATA%/Programs/chatgpt",
      "%APPDATA%/npm/chatgpt.cmd",
    ],
    cli: { cmd: "chatgpt", args: ["--version"] },
    session: { type: "jsonl", root: "~/.chatgpt", recentCwd: "cwd", currentTask: "last-user-message" },
  },
  {
    id: "deepseek-cli",
    name: "DeepSeek CLI",
    vendor: "DeepSeek",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["deepseek cli", "deepseek-cli", "deepseek"],
    processes: ["deepseek", "deepseek-cli"],
    npm: ["@sluisr/deepseek-cli"],
    roamingDirs: [],
    localDirs: [".deepseek"],
    homeDirs: [".deepseek"],
    installPaths: ["%APPDATA%/npm/deepseek.cmd"],
    cli: { cmd: "deepseek", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.deepseek/projects",
      recentCwd: "encoded-project-dir",
      currentTask: "last-user-message",
    },
  },
  {
    id: "yuanbao",
    name: "腾讯元宝",
    vendor: "Tencent",
    tier: 1,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["yuanbao", "tencent yuanbao", "qq yuanbao"],
    processes: ["yuanbao", "yuanbao.exe"],
    npm: [],
    roamingDirs: ["Tencent"],
    localDirs: ["yuanbao"],
    homeDirs: [".yuanbao"],
    installPaths: ["%PROGRAMFILES%/Tencent/Yuanbao"],
    session: { type: "electron", root: "%APPDATA%/Tencent/Yuanbao" },
  },
  {
    id: "glm",
    name: "GLM",
    vendor: "Zhipu AI",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["glm", "glm-cli", "chatglm", "zhipu"],
    processes: ["glm", "chatglm"],
    npm: ["@zhipuai/chatglm"],
    roamingDirs: [],
    localDirs: [".glm"],
    homeDirs: [".glm"],
    installPaths: ["%APPDATA%/npm/glm.cmd"],
    cli: { cmd: "glm", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.glm/projects",
      recentCwd: "encoded-project-dir",
      currentTask: "last-user-message",
    },
  },
  {
    id: "pi",
    name: "Pi",
    vendor: "Inflection",
    tier: 2,
    category: CATEGORY.CLI_AGENT,
    aliases: ["pi", "pi-assistant", "inflection pi"],
    processes: ["pi", "pi-assistant"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".pi"],
    installPaths: ["%LOCALAPPDATA%/Programs/Pi"],
    cli: { cmd: "pi", args: ["--version"] },
    session: { type: "jsonl", root: "~/.pi", recentCwd: "cwd", currentTask: "last-user-message" },
  },
  {
    id: "notebooklm",
    name: "NotebookLM",
    vendor: "Google",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["notebooklm", "google notebooklm"],
    processes: ["notebooklm"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".notebooklm"],
    installPaths: ["%LOCALAPPDATA%/Programs/NotebookLM"],
    session: { type: "jsonl", root: "~/.notebooklm", recentCwd: "cwd", currentTask: "last-user-message" },
  },
  {
    id: "character-ai",
    name: "Character AI",
    vendor: "Character.AI",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["character ai", "character-ai", "c.ai"],
    processes: ["character-ai", "cai"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".character-ai"],
    installPaths: ["%LOCALAPPDATA%/Programs/CharacterAI"],
    session: { type: "jsonl", root: "~/.character-ai", recentCwd: "cwd", currentTask: "last-user-message" },
  },
  {
    id: "devin-desktop",
    name: "Devin Desktop",
    vendor: "Cognition AI",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["devin desktop", "devin-desktop", "windsurf"],
    processes: ["devin", "devin-desktop"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".devin"],
    installPaths: ["%LOCALAPPDATA%/Programs/Devin-Desktop"],
    session: { type: "electron", root: "%APPDATA%/Devin" },
  },
  {
    id: "manus",
    name: "Manus",
    vendor: "Manus AI",
    tier: 2,
    category: CATEGORY.CLOUD_CHAT,
    aliases: ["manus", "manus ai"],
    processes: ["manus"],
    npm: [],
    roamingDirs: ["Manus"],
    localDirs: ["manus-updater"],
    homeDirs: [".manus"],
    installPaths: ["%APPDATA%/Manus"],
    session: { type: "electron", root: "%APPDATA%/Manus" },
  },
  {
    id: "perplexity",
    name: "Perplexity",
    vendor: "Perplexity AI",
    tier: 1,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["perplexity", "perplexity.ai"],
    processes: ["perplexity", "perplexity.exe", "comet"],
    npm: [],
    roamingDirs: ["Perplexity"],
    localDirs: [],
    homeDirs: [".perplexity"],
    installPaths: ["%LOCALAPPDATA%/Programs/Perplexity"],
    session: { type: "electron", root: "%APPDATA%/Perplexity" },
  },
  {
    id: "poe",
    name: "Poe",
    vendor: "Quora",
    tier: 1,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["poe", "poe.com"],
    processes: ["poe", "poe.exe"],
    npm: [],
    roamingDirs: ["Poe"],
    localDirs: [],
    homeDirs: [".poe"],
    installPaths: ["%LOCALAPPDATA%/Programs/Poe"],
    session: { type: "electron", root: "%APPDATA%/Poe" },
  },
  {
    id: "gamma",
    name: "Gamma",
    vendor: "Gamma",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["gamma", "gamma.app"],
    processes: ["gamma", "gamma.exe"],
    npm: [],
    roamingDirs: ["Gamma"],
    localDirs: [],
    homeDirs: [".gamma"],
    installPaths: ["%LOCALAPPDATA%/Programs/Gamma"],
    session: { type: "electron", root: "%APPDATA%/Gamma" },
  },
  {
    id: "lovable",
    name: "Lovable",
    vendor: "Lovable",
    tier: 1,
    category: CATEGORY.IDE,
    aliases: ["lovable", "lovable.dev"],
    processes: ["lovable", "lovable.exe"],
    npm: [],
    roamingDirs: ["Lovable"],
    localDirs: [],
    homeDirs: [".lovable"],
    installPaths: ["%LOCALAPPDATA%/Programs/Lovable"],
    session: { type: "electron", root: "%APPDATA%/Lovable" },
  },
  {
    id: "fireflies",
    name: "Fireflies",
    vendor: "Fireflies.ai",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["fireflies", "fireflies.ai"],
    processes: ["fireflies", "fireflies.exe"],
    npm: [],
    roamingDirs: ["Fireflies"],
    localDirs: [],
    homeDirs: [".fireflies"],
    installPaths: ["%LOCALAPPDATA%/Programs/Fireflies"],
    session: { type: "electron", root: "%APPDATA%/Fireflies" },
  },
  {
    id: "fathom",
    name: "Fathom",
    vendor: "Fathom",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["fathom", "fathom.video"],
    processes: ["fathom", "fathom.exe"],
    npm: [],
    roamingDirs: ["Fathom"],
    localDirs: [],
    homeDirs: [".fathom"],
    installPaths: ["%LOCALAPPDATA%/Programs/Fathom"],
    session: { type: "electron", root: "%APPDATA%/Fathom" },
  },
  {
    id: "otter",
    name: "Otter",
    vendor: "Otter.ai",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["otter", "otter.ai"],
    processes: ["otter", "otter.exe"],
    npm: [],
    roamingDirs: ["Otter"],
    localDirs: [],
    homeDirs: [".otter"],
    installPaths: ["%LOCALAPPDATA%/Programs/Otter"],
    session: { type: "electron", root: "%APPDATA%/Otter" },
  },
  {
    id: "granola",
    name: "Granola",
    vendor: "Granola",
    tier: 2,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["granola", "granola.so"],
    processes: ["granola", "granola.exe"],
    npm: [],
    roamingDirs: ["Granola"],
    localDirs: [],
    homeDirs: [".granola"],
    installPaths: ["%LOCALAPPDATA%/Programs/Granola"],
    session: { type: "electron", root: "%APPDATA%/Granola" },
  },
  {
    id: "genspark",
    name: "Genspark",
    vendor: "Genspark",
    tier: 1,
    category: CATEGORY.CLI_AGENT,
    aliases: ["genspark", "genspark.ai"],
    processes: ["genspark", "genspark.exe"],
    npm: [],
    roamingDirs: ["Genspark"],
    localDirs: [],
    homeDirs: [".genspark"],
    installPaths: ["%LOCALAPPDATA%/Programs/Genspark"],
    cli: { cmd: "genspark", args: ["--version"] },
    session: { type: "jsonl", root: "~/.genspark/projects", recentCwd: "cwd", currentTask: "last-user-message" },
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    vendor: "OpenClaw Community",
    tier: 2,
    category: CATEGORY.CLI_AGENT,
    aliases: ["openclaw", "clawdhub"],
    processes: ["openclaw"],
    npm: [],
    roamingDirs: ["clawdhub"],
    localDirs: ["@guanjia-openclawelectron-updater"],
    homeDirs: [".openclaw", ".clawdchat"],
    installPaths: [],
    cli: { cmd: "openclaw", args: ["--version"] },
    session: {
      type: "jsonl",
      root: "~/.openclaw/agents",
      recentCwd: "jsonl-cwd",
      currentTask: "last-user-message",
    },
  },
  {
    id: "cline",
    name: "Cline",
    vendor: "Cline",
    tier: 2,
    category: CATEGORY.EXTENSION,
    aliases: ["cline"],
    processes: [],
    npm: [],
    roamingDirs: ["Cline"],
    localDirs: [],
    homeDirs: [".cline"],
    installPaths: [],
    vscodeExtensions: [
      "saoudrizwan.claude-dev",
      "tianguaduizhang.claude-dev-china",
      "cline.cline",
    ],
    session: { type: "jsonl", root: "~/.cline" },
  },
  {
    id: "roo-code",
    name: "Roo Code",
    vendor: "Roo Code",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["roo code", "roo-code", "roocode"],
    processes: [],
    npm: [],
    roamingDirs: ["Roo-Code"],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    vscodeExtensions: ["rooveterinaryinc.roo-cline", "rooveterinaryinc.roo-cline-china"],
    session: { type: "vscdb", root: "%APPDATA%/Roo-Code/User" },
  },
  {
    id: "gemini-code-assist",
    name: "Gemini Code Assist",
    vendor: "Google",
    tier: 2,
    category: CATEGORY.EXTENSION,
    aliases: ["gemini code assist", "geminicodeassist", "gemini code"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    vscodeExtensions: ["google.geminicodeassist", "google.gemini-code-assist"],
    session: null,
  },
  {
    id: "codemate-agent",
    name: "Codemate Agent",
    vendor: "CodemateAI",
    tier: 2,
    category: CATEGORY.EXTENSION,
    aliases: ["codemate agent", "codemate", "codemateai"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".codemate", ".codemate.cache"],
    installPaths: [],
    vscodeExtensions: ["codemateai.codemate-agent", "codemateai.codemate-ai"],
    session: null,
  },
  {
    id: "iflow-vscode",
    name: "iFlow VS Code Companion",
    vendor: "iFlytek",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["iflow vscode", "iflow ide companion"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    vscodeExtensions: [
      "iflow-cli.iflow-cli-vscode-ide-companion",
      "iflow.iflow-cli-vscode-ide-companion",
    ],
    session: null,
  },
  {
    id: "quokka",
    name: "Quokka",
    vendor: "Wallaby",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["quokka"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".quokka"],
    installPaths: [],
    vscodeExtensions: ["wallabyjs.quokka-vscode"],
    session: null,
  },
  {
    id: "mcp-vscode-ext",
    name: "VS Code MCP Extension",
    vendor: "block",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["vscode mcp extension", "mcp extension"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    vscodeExtensions: ["block.vscode-mcp-extension"],
    session: null,
  },
  {
    id: "doubao-vscode",
    name: "豆包 VS Code Plugin",
    vendor: "ByteDance",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["doubao vscode", "doubao plugin"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    vscodeExtensions: ["doubao.doubao-app-share-vscode-plugin"],
    session: null,
  },
  {
    id: "vscode-copilot",
    name: "GitHub Copilot / VS Code",
    vendor: "Microsoft / GitHub",
    tier: 2,
    category: CATEGORY.IDE,
    aliases: ["visual studio code", "vscode"],
    processes: ["code"],
    npm: [],
    roamingDirs: ["Code"],
    localDirs: [],
    homeDirs: [".vscode", ".vscode-shared"],
    installPaths: ["E:/Microsoft VS Code"],
    session: {
      type: "vscdb",
      root: "%APPDATA%/Code/User",
      recentCwd: "vscdb-profile-workspaces",
    },
  },
  {
    id: "github-desktop",
    name: "GitHub Desktop",
    vendor: "GitHub",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["github desktop"],
    processes: ["github desktop"],
    npm: [],
    roamingDirs: ["GitHub Desktop"],
    localDirs: ["GitHub Desktop"],
    homeDirs: [],
    installPaths: [],
    session: null,
  },
  {
    id: "warp",
    name: "Warp",
    vendor: "Warp",
    tier: 2,
    category: CATEGORY.IDE,
    aliases: ["warp"],
    processes: ["warp", "warp-terminal"],
    npm: [],
    roamingDirs: [],
    localDirs: ["warp"],
    homeDirs: [],
    installPaths: ["%LOCALAPPDATA%/Programs/Warp"],
    session: { type: "electron", root: "%LOCALAPPDATA%/warp" },
  },
  {
    id: "zed",
    name: "Zed",
    vendor: "Zed Industries",
    tier: 2,
    category: CATEGORY.IDE,
    aliases: ["zed"],
    processes: ["zed"],
    npm: [],
    roamingDirs: ["Zed"],
    localDirs: ["Zed"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/Zed" },
  },
  {
    id: "ollama",
    name: "Ollama",
    vendor: "Ollama",
    tier: 2,
    category: CATEGORY.RUNTIME,
    aliases: ["ollama"],
    processes: ["ollama", "ollama app"],
    npm: [],
    roamingDirs: ["ollama app.exe"],
    localDirs: ["Ollama"],
    homeDirs: [".ollama"],
    installPaths: ["%LOCALAPPDATA%/Programs/Ollama"],
    cli: { cmd: "ollama", args: ["--version"] },
    session: null,
  },
  {
    id: "pinokio",
    name: "Pinokio",
    vendor: "Pinokio",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["pinokio"],
    processes: [],
    npm: [],
    roamingDirs: ["Pinokio"],
    localDirs: ["pinokio-updater"],
    homeDirs: [],
    installPaths: [],
    session: null,
  },
  {
    id: "notion",
    name: "Notion",
    vendor: "Notion",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["notion"],
    processes: ["notion"],
    npm: [],
    roamingDirs: ["Notion"],
    localDirs: ["notion-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/Notion" },
  },
  {
    id: "obsidian",
    name: "Obsidian",
    vendor: "Obsidian",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["obsidian"],
    processes: [],
    npm: [],
    roamingDirs: ["obsidian"],
    localDirs: ["obsidian-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/obsidian" },
  },
  {
    id: "5ire",
    name: "5ire",
    vendor: "5ire",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["5ire"],
    processes: [],
    npm: [],
    roamingDirs: ["5ire"],
    localDirs: ["5ire-updater"],
    homeDirs: [],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/5ire" },
  },
  {
    id: "feishu",
    name: "飞书 Feishu",
    vendor: "ByteDance",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["feishu", "飞书", "lark"],
    processes: [],
    npm: [],
    roamingDirs: ["LarkShell"],
    localDirs: ["Feishu", "@hilodesktop-updater"],
    homeDirs: [".lark-cli"],
    installPaths: [],
    session: { type: "electron", root: "%LOCALAPPDATA%/Feishu" },
  },
  {
    id: "dingtalk",
    name: "钉钉 DingTalk",
    vendor: "Alibaba",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["dingtalk", "钉钉", "dingone"],
    processes: ["dingtalk"],
    npm: [],
    roamingDirs: ["DingTalk", "dingone", "dinglive"],
    localDirs: ["DingTalk", "dingone-updater"],
    homeDirs: [".dingone", ".dingtalkdevtools"],
    installPaths: [],
    session: { type: "electron", root: "%APPDATA%/DingTalk" },
  },
  {
    id: "codeverse",
    name: "CodeVerse",
    vendor: "Ant Group",
    tier: 3,
    category: CATEGORY.IDE,
    aliases: ["codeverse"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".codeverse"],
    installPaths: [],
    session: null,
  },
  {
    id: "medusa-backend",
    name: "Medusa Backend",
    vendor: "Local",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["medusa-backend", "medusa"],
    processes: [],
    npm: ["medusa-backend"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".medusa", ".mem0"],
    installPaths: [],
    session: null,
  },
  {
    id: "hermes-agent",
    name: "Hermes Agent",
    vendor: "Hermes",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["hermes agent", "hermes-agent", "hermes"],
    processes: [],
    npm: ["hermes-agent"],
    roamingDirs: [],
    localDirs: ["hermes", "com.nousresearch.hermes.setup"],
    homeDirs: [".hermes"],
    installPaths: [],
    session: null,
  },
  {
    id: "crush",
    name: "Crush",
    vendor: "Charm",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["crush"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: ["crush"],
    homeDirs: [".crush"],
    installPaths: [],
    session: null,
  },
  {
    id: "opencli",
    name: "OpenCLI",
    vendor: "OpenCLI",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["opencli", "open cli"],
    processes: [],
    npm: ["@jackwener/opencli"],
    roamingDirs: [],
    localDirs: ["com.vercel.cli"],
    homeDirs: [".opencli"],
    installPaths: [],
    session: null,
  },
  {
    id: "claude-code-router",
    name: "Claude Code Router",
    vendor: "musistudio",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["claude code router", "claude-code-router", "ccr"],
    processes: [],
    npm: ["@musistudio/claude-code-router"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".claude-code-router"],
    installPaths: [],
    session: null,
  },
  {
    id: "cc-switch",
    name: "CC Switch",
    vendor: "CC Switch",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["cc switch", "cc-switch-cli"],
    processes: [],
    npm: ["cc-switch-cli"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".cc-switch-cli"],
    installPaths: [],
    session: null,
  },
  {
    id: "agent-browser",
    name: "Agent Browser",
    vendor: "Local",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["agent-browser", "agent browser", "browser use cli"],
    processes: [],
    npm: ["agent-browser"],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".agent-browser", ".browser-use-cli"],
    installPaths: [],
    session: null,
  },
  {
    id: "codebuddy-router",
    name: "CodeBuddy Marketplace",
    vendor: "Tencent",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["codebuddy marketplace"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".codemate", ".composio"],
    installPaths: [],
    session: null,
  },
  {
    id: "stigmergy",
    name: "Stigmergy",
    vendor: "Local",
    tier: 2,
    category: CATEGORY.PLATFORM,
    aliases: ["stigmergy"],
    processes: [],
    npm: ["stigmergy"],
    roamingDirs: ["stigmergy-desktop-app"],
    localDirs: ["agentskills"],
    homeDirs: [".stigmergy", ".stigmergy-cli", ".stigmergy-project"],
    installPaths: [],
    session: { type: "jsonl", root: "~/.stigmergy", currentTask: "last-user-message" },
  },
  {
    id: "tarko-agent",
    name: "Tarko Agent",
    vendor: "Tarko",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["tarko agent", "tarko-agent-cli"],
    processes: [],
    npm: [],
    roamingDirs: ["tarko-agent-cli-nodejs"],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    session: null,
  },
  {
    id: "cn-gov-office-ai",
    name: "海鹦 OfficeAI 助手",
    vendor: "珠海海鹦",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["officeai", "office ai", "海鹦"],
    processes: ["officeaiservice"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: ["%PROGRAMFILESX86%/HaiYingSoft/OfficeAI"],
    session: null,
  },
  {
    id: "metaso",
    name: "秘塔AI搜索",
    vendor: "秘塔",
    tier: 3,
    category: CATEGORY.EXTENSION,
    aliases: ["metaso", "秘塔ai搜索", "秘塔"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    browserExtensions: ["metaso"],
    session: null,
  },
  {
    id: "codex-muse",
    name: "CodexMuse",
    vendor: "CodexMuse",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["codexmuse", "codex muse"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".codexmuse"],
    installPaths: [],
    session: null,
  },
  {
    id: "marvis-cli",
    name: "Marvis CLI",
    vendor: "Marvis",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["marvis cli"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    session: null,
  },
  {
    id: "skyreels",
    name: "SkyReels",
    vendor: "Skywork",
    tier: 3,
    category: CATEGORY.DESKTOP_CHAT,
    aliases: ["skyreels"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".skypilot"],
    installPaths: [],
    session: null,
  },
  {
    id: "medusa-skill",
    name: "Letta / MemGPT",
    vendor: "Letta",
    tier: 3,
    category: CATEGORY.CLI_AGENT,
    aliases: ["letta", "memgpt"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".letta"],
    installPaths: [],
    session: null,
  },
  {
    id: "modelscope",
    name: "ModelScope",
    vendor: "Alibaba",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["modelscope"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [".modelscope"],
    installPaths: [],
    session: null,
  },
  {
    id: "webuse-mcp",
    name: "WinUse MCP / MCP Hosts",
    vendor: "Various",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["winusemcp"],
    processes: ["winusemcp", "kbmcp", "gameinfomcp", "commerce-mcp", "androwsmcp", "drinkcouponmcp", "agent-tool-host"],
    npm: [],
    roamingDirs: [],
    localDirs: [],
    homeDirs: [],
    installPaths: [],
    session: null,
  },
  {
    id: "smart-agents",
    name: "Smart Agents / SkillHub",
    vendor: "Local",
    tier: 3,
    category: CATEGORY.PLATFORM,
    aliases: ["smart agents", "skillhub", "agent skills"],
    processes: [],
    npm: [],
    roamingDirs: [],
    localDirs: ["agentskills"],
    homeDirs: [".smart-agents", ".smart-cli", ".skillhub", ".openskills"],
    installPaths: [],
    session: null,
  },
];

function normalize(value) {
  return String(value || "")
    .toLowerCase()
    .replace(/[\s._\-()[\]{}'"`]/g, "")
    .trim();
}

function getSignatures() {
  return SIGNATURES;
}

function getSignature(id) {
  return SIGNATURES.find((s) => s.id === id) || null;
}

function signatureForPlatform(platform) {
  return SIGNATURES;
}

module.exports = {
  CATEGORY,
  SIGNATURES,
  normalize,
  getSignatures,
  getSignature,
  signatureForPlatform,
};