// Gemini CLI ShareMem Integration
// Auto-generated by ShareMem v1.0.2
// Project: D:\stigmergy-CLI-Multi-Agents\test-resumesession-fix

const { CrossCLIHistory } = require('./sharemem-core');

class GeminiHistoryHandler {
  constructor() {
    this.history = new CrossCLIHistory('D:\stigmergy-CLI-Multi-Agents\test-resumesession-fix');
  }

  async handleCommand(input, session) {
    if (!input.startsWith('/history')) return null;

    try {
      const result = await this.history.query(input, {
        currentCLI: 'gemini',
        sessionPath: session.path
      });

      return {
        text: result.response,
        continue: true,
        suggestions: result.suggestions
      };
    } catch (error) {
      return {
        text: `�?History command failed: ${error.message}`,
        continue: true,
        suggestions: []
      };
    }
  }
}

// 注册处理�?const handler = new GeminiHistoryHandler();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GeminiHistoryHandler, handler };
}

// Gemini CLI integration
if (typeof geminiCLI !== 'undefined') {
  geminiCLI.addCommandHandler('history', handler.handleCommand.bind(handler));
}
