#!/usr/bin/env node

/**
 * Automated test for ResumeSession initialization
 */

const { spawn } = require('child_process');
const path = require('path');

console.log('üß™ Automated ResumeSession Test\n');

// Simulate user selection: select Codex CLI
const initProcess = spawn('resumesession', ['init'], {
  cwd: __dirname,
  stdio: ['pipe', 'pipe', 'pipe']
});

// Wait for the interactive prompt
initProcess.stdout.on('data', (data) => {
  const output = data.toString();
  console.log('CLI Output:', output);

  // When we see the selection prompt, automatically select the option
  if (output.includes('Select CLI tools')) {
    console.log('üìù Automatically selecting Codex CLI...');

    // Send space to select, then enter to confirm
    initProcess.stdin.write(' ');
    setTimeout(() => {
      initProcess.stdin.write('\n');
    }, 500);
  }
});

initProcess.stderr.on('data', (data) => {
  console.error('CLI Error:', data.toString());
});

initProcess.on('close', (code) => {
  console.log(`\n‚ú?Initialization completed with code: ${code}`);

  // Check what was generated
  console.log('\nüìÅ Generated files:');
  const fs = require('fs');

  if (fs.existsSync('.resumesession')) {
    console.log('‚ú?.resumesession configuration file');
    const config = JSON.parse(fs.readFileSync('.resumesession', 'utf8'));
    console.log('   Project:', config.projectPath);
    console.log('   Selected CLIs:', config.selectedCLIs);
    console.log('   Version:', config.version);
  }

  // Check for integration files
  const expectedPaths = [
    '.codex/plugins/resumesession-history.js'
  ];

  expectedPaths.forEach(path => {
    if (fs.existsSync(path)) {
      console.log(`‚ú?Integration file: ${path}`);
    } else {
      console.log(`‚ù?Missing integration file: ${path}`);
    }
  });

  // Test if integration code works
  testIntegrationCode();
});

initProcess.stdin.end();

function testIntegrationCode() {
  console.log('\nüîß Testing integration code...');

  const fs = require('fs');
  const integrationPath = '.codex/plugins/resumesession-history.js';

  if (fs.existsSync(integrationPath)) {
    try {
      const code = fs.readFileSync(integrationPath, 'utf8');

      // Check for key functions
      if (code.includes('handleHistoryCommand')) {
        console.log('‚ú?Contains handleHistoryCommand function');
      }

      if (code.includes('scanProjectSessions')) {
        console.log('‚ú?Contains scanProjectSessions function');
      }

      if (code.includes('formatResponse')) {
        console.log('‚ú?Contains formatResponse function');
      }

      // Check for required modules
      if (code.includes("require('child_process')")) {
        console.log('‚ú?Imports child_process module');
      }

      if (code.includes("require('path')")) {
        console.log('‚ú?Imports path module');
      }

      console.log('\nüìã Integration code analysis:');
      console.log('   Code length:', code.length, 'characters');
      console.log('   Lines of code:', code.split('\n').length);
      console.log('   Generated by ResumeSession:', code.includes('ShareMem') || code.includes('ResumeSession'));

    } catch (error) {
      console.log('‚ù?Error reading integration file:', error.message);
    }
  }
}
