// Claude CLI ResumeSession Integration
// Auto-generated by ResumeSession v1.0.4
// Project: D:\stigmergy-CLI-Multi-Agents\test-final-verification-2

const fs = require('fs');
const path = require('path');
const os = require('os');

// Load shared path configuration
const pathConfigLoader = require(path.join(__dirname, 'path-config-loader.js'));

// Embedded ResumeSession Core Functionality

class SessionScanner {
  scanSessions(cliType, sessionsPath, projectPath) {
    const sessions = [];
    if (!sessionsPath || !projectPath) return sessions;

    try {
      if (!fs.existsSync(sessionsPath)) return sessions;

      // For IFlow, Claude, QoderCLI: scan projects subdirectories (one level)
      if ((cliType === 'iflow' || cliType === 'claude' || cliType === 'qodercli') && sessionsPath.includes('projects')) {
        const subdirs = fs.readdirSync(sessionsPath);
        for (const subdir of subdirs) {
          const subdirPath = path.join(sessionsPath, subdir);
          try {
            const stat = fs.statSync(subdirPath);
            if (stat.isDirectory()) {
              sessions.push(...this.scanSessionFiles(cliType, subdirPath, projectPath));
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      // For Gemini: scan tmp/<hash>/chats subdirectories (multiple levels)
      if (cliType === 'gemini' && sessionsPath.includes('tmp')) {
        const hashDirs = fs.readdirSync(sessionsPath);
        for (const hashDir of hashDirs) {
          const hashDirPath = path.join(sessionsPath, hashDir);
          try {
            const stat = fs.statSync(hashDirPath);
            if (stat.isDirectory()) {
              const chatsPath = path.join(hashDirPath, 'chats');
              if (fs.existsSync(chatsPath)) {
                sessions.push(...this.scanSessionFiles(cliType, chatsPath, projectPath));
              }
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      // For Qwen: scan projects/<projectName>/chats subdirectories (two levels)
      if (cliType === 'qwen' && sessionsPath.includes('projects')) {
        const projectDirs = fs.readdirSync(sessionsPath);
        for (const projectDir of projectDirs) {
          const projectDirPath = path.join(sessionsPath, projectDir);
          try {
            const stat = fs.statSync(projectDirPath);
            if (stat.isDirectory()) {
              const chatsPath = path.join(projectDirPath, 'chats');
              if (fs.existsSync(chatsPath)) {
                sessions.push(...this.scanSessionFiles(cliType, chatsPath, projectPath));
              }
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      // For CodeBuddy: scan both projects subdirectories and root history.jsonl
      if (cliType === 'codebuddy') {
        const projectsPath = path.join(sessionsPath, 'projects');
        if (fs.existsSync(projectsPath)) {
          const projectDirs = fs.readdirSync(projectsPath);
          for (const projectDir of projectDirs) {
            const projectDirPath = path.join(projectsPath, projectDir);
            try {
              const stat = fs.statSync(projectDirPath);
              if (stat.isDirectory()) {
                sessions.push(...this.scanSessionFiles(cliType, projectDirPath, projectPath));
              }
            } catch (error) {
              continue;
            }
          }
        }
        sessions.push(...this.scanSessionFiles(cliType, sessionsPath, projectPath));
        return sessions;
      }

      return this.scanSessionFiles(cliType, sessionsPath, projectPath);
    } catch (error) {
      console.warn(`Warning: Could not scan ${cliType} sessions:`, error.message);
    }

    return sessions;
  }

  scanSessionFiles(cliType, sessionsPath, projectPath) {
    const sessions = [];

    try {
      const files = fs.readdirSync(sessionsPath);
      for (const file of files) {
        if (file.endsWith('.json') || file.endsWith('.session') || file.endsWith('.jsonl')) {
          try {
            const filePath = path.join(sessionsPath, file);
            let sessionData;

            if (file.endsWith('.jsonl')) {
              const content = fs.readFileSync(filePath, 'utf8');
              const lines = content.trim().split('\n').filter(line => line.trim());
              const messages = lines.map(line => JSON.parse(line));
              
              if (messages.length === 0) continue;
              sessionData = this.parseJSONLSession(messages, file);
            } else {
              const content = fs.readFileSync(filePath, 'utf8');
              sessionData = JSON.parse(content);
            }

            if (this.isProjectSession(sessionData, projectPath)) {
              sessions.push({
                cliType,
                sessionId: sessionData.id || sessionData.sessionId || file.replace(/\.(json|session|jsonl)$/, ''),
                title: sessionData.title || sessionData.topic || 'Untitled',
                content: this.extractContent(sessionData),
                updatedAt: new Date(sessionData.updatedAt || sessionData.timestamp || fs.statSync(filePath).mtime),
                messageCount: sessionData.messageCount || this.countMessages(sessionData),
                projectPath
              });
            }
          } catch (error) {
            console.warn(`Warning: Could not parse ${file}:`, error.message);
          }
        }
      }
    } catch (error) {
      console.warn(`Warning: Could not scan files:`, error.message);
    }

    return sessions;
  }

  parseJSONLSession(messages, filename) {
    const firstMsg = messages[0];
    const lastMsg = messages[messages.length - 1];
    const userMessages = messages.filter(m => m.type === 'user' || m.role === 'user');
    
    let title = 'Untitled Session';
    if (userMessages.length > 0) {
      const firstUserMsg = userMessages[0];
      let content = firstUserMsg.message?.content || firstUserMsg.content || '';
      if (typeof content === 'object') {
        content = JSON.stringify(content);
      }
      if (typeof content === 'string' && content.trim()) {
        title = content.substring(0, 100) || title;
      }
    }

    const contentParts = messages
      .map(m => {
        if (m.message && typeof m.message === 'object') {
          return m.message.content || m.message.text || '';
        }
        return m.content || m.text || '';
      })
      .filter(text => text && typeof text === 'string' && text.trim());

    return {
      sessionId: firstMsg.sessionId || filename.replace('.jsonl', ''),
      title: title,
      content: contentParts.join(' '),
      timestamp: lastMsg.timestamp || new Date().toISOString(),
      projectPath: firstMsg.cwd || firstMsg.workingDirectory,
      messageCount: messages.filter(m => m.type === 'user' || m.type === 'assistant' || m.role === 'user' || m.role === 'assistant').length,
      messages: messages
    };
  }

  scanAllCLISessions(projectPath) {
    const allSessions = [];
    const cliPathsMap = pathConfigLoader.getAllCLISessionPaths();

    for (const [cliType, sessionsPaths] of Object.entries(cliPathsMap)) {
      // Scan all possible paths for this CLI
      for (const sessionsPath of sessionsPaths) {
        const sessions = this.scanSessions(cliType, sessionsPath, projectPath);
        allSessions.push(...sessions);
      }
    }

    return allSessions;
  }

  isProjectSession(session, projectPath) {
    const sessionProject = session.projectPath || session.workingDirectory;
    if (!sessionProject) return true;

    return sessionProject === projectPath ||
           sessionProject.startsWith(projectPath) ||
           projectPath.startsWith(sessionProject);
  }

  extractContent(sessionData) {
    if (sessionData.content && typeof sessionData.content === 'string') {
      return sessionData.content;
    }

    if (sessionData.messages && Array.isArray(sessionData.messages)) {
      return sessionData.messages
        .map(msg => {
          if (msg.message && typeof msg.message === 'object') {
            const content = msg.message.content || msg.message.text || '';
            return this.extractTextFromContent(content);
          }
          const content = msg.content || msg.text || '';
          return this.extractTextFromContent(content);
        })
        .filter(text => text && typeof text === 'string' && text.trim())
        .join(' ');
    }

    if (Array.isArray(sessionData)) {
      return sessionData
        .map(item => {
          if (item.message && typeof item.message === 'object') {
            const content = item.message.content || item.message.text || '';
            return this.extractTextFromContent(content);
          }
          const content = item.content || item.text || '';
          return this.extractTextFromContent(content);
        })
        .filter(text => text && typeof text === 'string' && text.trim())
        .join(' ');
    }

    return '';
  }

  extractTextFromContent(content) {
    if (typeof content === 'string') {
      return content;
    }

    if (Array.isArray(content)) {
      return content
        .map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object') {
            return item.text || item.content || '';
          }
          return '';
        })
        .filter(text => text && typeof text === 'string')
        .join(' ');
    }

    if (content && typeof content === 'object') {
      return content.text || content.content || JSON.stringify(content);
    }

    return '';
  }

  countMessages(sessionData) {
    if (sessionData.messages) {
      return Array.isArray(sessionData.messages) ? sessionData.messages.length : 0;
    }

    if (Array.isArray(sessionData)) {
      return sessionData.length;
    }

    return 0;
  }
}

class SessionFilter {
  filterByCLI(sessions, cliType) {
    if (!cliType) return sessions;
    return sessions.filter(session => session.cliType === cliType);
  }

  filterBySearch(sessions, searchTerm) {
    if (!searchTerm) return sessions;

    const lowerSearch = searchTerm.toLowerCase();
    return sessions.filter(session =>
      session.title.toLowerCase().includes(lowerSearch) ||
      session.content.toLowerCase().includes(lowerSearch)
    );
  }

  filterByDateRange(sessions, timeRange = 'all') {
    if (timeRange === 'all') return sessions;

    const now = new Date();
    return sessions.filter(session => {
      const sessionDate = new Date(session.updatedAt);

      switch (timeRange) {
        case 'today':
          return sessionDate.toDateString() === now.toDateString();
        case 'week':
          const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
          return sessionDate >= weekAgo;
        case 'month':
          const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
          return sessionDate >= monthAgo;
        default:
          return true;
      }
    });
  }

  sortByDate(sessions) {
    return [...sessions].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
  }

  filterByProject(sessions, projectPath) {
    return sessions.filter(session => session.projectPath === projectPath);
  }

  applyFilters(sessions, options, projectPath) {
    let filteredSessions = [...sessions];

    filteredSessions = this.filterByProject(filteredSessions, projectPath);

    if (options.cli) {
      filteredSessions = this.filterByCLI(filteredSessions, options.cli);
    }

    if (options.search) {
      filteredSessions = this.filterBySearch(filteredSessions, options.search);
    }

    if (options.timeRange) {
      filteredSessions = this.filterByDateRange(filteredSessions, options.timeRange);
    }

    filteredSessions = this.sortByDate(filteredSessions);

    if (options.limit && options.limit > 0) {
      filteredSessions = filteredSessions.slice(0, options.limit);
    }

    return filteredSessions;
  }
}

class HistoryFormatter {
  formatSummary(sessions, context) {
    if (sessions.length === 0) {
      return `📭 当前项目暂无历史会话\n\n💡 **提示:** 尝试: /stigmergy-resume --search <关键词>`;
    }

    let response = `📁 **项目历史会话**\n\n📊 共找到 ${sessions.length} 个会话\n\n`;

    const byCLI = {};
    sessions.forEach(session => {
      if (!byCLI[session.cliType]) byCLI[session.cliType] = [];
      byCLI[session.cliType].push(session);
    });

    Object.entries(byCLI).forEach(([cli, cliSessions]) => {
      const icon = this.getCLIIcon(cli);
      response += `${icon} **${cli.toUpperCase()}** (${cliSessions.length}个)\n`;

      cliSessions.slice(0, 3).forEach((session, i) => {
        const date = this.formatDate(session.updatedAt);
        const title = session.title.substring(0, 50);
        response += `   ${i + 1}. ${title}...\n`;
        response += `      📅 ${date} • 💬 ${session.messageCount}条消息\n`;
      });

      if (cliSessions.length > 3) {
        response += `   ... 还有 ${cliSessions.length - 3} 个会话\n`;
      }
      response += '\n';
    });

    response += `💡 **使用方法:**\n`;
    response += `• '/stigmergy-resume --cli <工具>' - 查看特定CLI\n`;
    response += `• '/stigmergy-resume --search <关键词>' - 搜索内容\n`;
    response += `• '/stigmergy-resume --format timeline' - 时间线视图`;

    return response;
  }

  formatTimeline(sessions) {
    if (sessions.length === 0) {
      return '📭 暂无会话时间线。';
    }

    let response = `⏰ **时间线视图**\n\n`;

    sessions.forEach((session, index) => {
      const date = this.formatDate(session.updatedAt);
      const cliIcon = this.getCLIIcon(session.cliType);

      response += `${index + 1}. ${cliIcon} ${session.title}\n`;
      response += `   📅 ${date} • 💬 ${session.messageCount}条消息\n`;
      response += `   🔑 ${session.cliType}:${session.sessionId}\n\n`;
    });

    return response;
  }

  formatDetailed(sessions) {
    if (sessions.length === 0) {
      return '📭 暂无详细会话信息。';
    }

    let response = `📋 **详细视图**\n\n`;

    sessions.forEach((session, index) => {
      const cliIcon = this.getCLIIcon(session.cliType);
      const date = session.updatedAt.toLocaleString();

      response += `${index + 1}. ${cliIcon} **${session.title}**\n`;
      response += `   📅 ${date}\n`;
      response += `   🔧 CLI: ${session.cliType}\n`;
      response += `   💬 消息数: ${session.messageCount}\n`;
      response += `   🆔 会话ID: '${session.sessionId}'\n\n`;
    });

    return response;
  }

  formatContext(session) {
    if (!session) {
      return `📭 暂无可恢复的上下文。`;
    }

    let response = `🔄 **上下文恢复**\n\n`;
    response += `📅 会话时间: ${session.updatedAt.toLocaleString()}\n`;
    response += `🔧 来源CLI: ${session.cliType}\n`;
    response += `💬 消息数: ${session.messageCount}\n`;
    response += `🆔 会话ID: ${session.sessionId}\n\n`;
    response += `---\n\n`;
    response += `**上次讨论内容:**\n`;
    response += session.content.substring(0, 500);
    if (session.content.length > 500) {
      response += `...`;
    }

    return response;
  }

  getCLIIcon(cliType) {
    const icons = {
      'claude': '🟢',
      'gemini': '🔵',
      'qwen': '🟡',
      'iflow': '🔴',
      'codebuddy': '🟣',
      'codex': '🟪',
      'qodercli': '🟠'
    };
    return icons[cliType] || '🔹';
  }

  formatDate(date) {
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (24 * 60 * 60 * 1000));

    if (days === 0) {
      return date.toLocaleTimeString();
    } else if (days === 1) {
      return '昨天';
    } else if (days < 7) {
      return `${days}天前`;
    } else if (days < 30) {
      return `${Math.floor(days / 7)}周前`;
    } else {
      return `${Math.floor(days / 30)}个月前`;
    }
  }
}

class HistoryQuery {
  constructor() {
    this.scanner = new SessionScanner();
    this.filter = new SessionFilter();
    this.formatter = new HistoryFormatter();
  }

  queryHistory(options, projectPath) {
    try {
      const allSessions = this.scanner.scanAllCLISessions(projectPath);
      const filteredSessions = this.filter.applyFilters(allSessions, options, projectPath);

      let response;
      switch (options.format) {
        case 'timeline':
          response = this.formatter.formatTimeline(filteredSessions);
          break;
        case 'detailed':
          response = this.formatter.formatDetailed(filteredSessions);
          break;
        case 'context':
          response = this.formatter.formatContext(filteredSessions[0] || null);
          break;
        case 'summary':
        default:
          response = this.formatter.formatSummary(filteredSessions);
          break;
      }

      const suggestions = this.generateSuggestions(filteredSessions, options);

      return {
        response,
        suggestions
      };
    } catch (error) {
      return {
        response: `❌ 历史查询失败: ${error.message}`,
        suggestions: ['/stigmergy-resume --help']
      };
    }
  }

  generateSuggestions(sessions, query) {
    const suggestions = [];
    const cmd = '/stigmergy-resume';

    if (sessions.length > 0) {
      suggestions.push(`${cmd} --format context`);
      suggestions.push(`${cmd} --format timeline`);

      if (sessions[0]?.cliType) {
        suggestions.push(`${cmd} --cli ${sessions[0].cliType}`);
      }
    }

    suggestions.push(`${cmd} --search "react"`);
    suggestions.push(`${cmd} --today`);

    return suggestions.slice(0, 5);
  }
}

/**
 * 处理 /stigmergy-resume 命令
 */
async function handleHistoryCommand(input, context) {
  try {
    console.log('🔍 Searching cross-CLI history...');

    const query = buildQuery(input);
    const historyQuery = new HistoryQuery();
    const result = historyQuery.queryHistory(query, 'D:\stigmergy-CLI-Multi-Agents\test-final-verification-2');

    return {
      response: result.response,
      suggestions: result.suggestions
    };
  } catch (error) {
    console.error('History command error:', error);
    return {
      response: `❌ 历史查询失败: ${error.message}`,
      suggestions: ['/stigmergy-resume --help']
    };
  }
}

/**
 * 构建查询参数
 */
function buildQuery(input) {
  const options = {
    limit: 10,
    format: 'summary',
    timeRange: 'all',
    cli: null,
    search: null
  };

  const cleanInput = input.replace(/^\/(stigmergy-resume|history|stigmergy-history)\s*/i, '').trim();
  const parts = cleanInput.split(/\s+/).filter(p => p.length > 0);

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].toLowerCase();

    if (part === '--cli' && i + 1 < parts.length) {
      options.cli = parts[++i];
    } else if (part === '--search' && i + 1 < parts.length) {
      options.search = parts[++i];
    } else if (part === '--limit' && i + 1 < parts.length) {
      options.limit = parseInt(parts[++i]);
    } else if (part === '--format' && i + 1 < parts.length) {
      const format = parts[++i]?.toLowerCase();
      if (['summary', 'timeline', 'detailed', 'context'].includes(format)) {
        options.format = format;
      }
    } else if (part === '--today') {
      options.timeRange = 'today';
    } else if (part === '--week') {
      options.timeRange = 'week';
    } else if (part === '--month') {
      options.timeRange = 'month';
    } else if (!part.startsWith('--') && !options.search) {
      options.search = part;
    }
  }

  return options;
}



// 导出处理器
module.exports = {
  handleHistoryCommand
};

// 注册到Claude CLI
if (typeof global !== 'undefined' && global.claudeCLI) {
  global.claudeCLI.addSlashCommand('/stigmergy-resume', handleHistoryCommand);
}
