// Kode CLI ResumeSession Integration
// Auto-generated by ResumeSession v1.0.4
// Project: D:\stigmergy-CLI-Multi-Agents\test-fix-verification

const fs = require('fs');
const path = require('path');
const os = require('os');

// Load shared path configuration
const pathConfigLoader = require(path.join(__dirname, 'path-config-loader.js'));

class SessionScanner {
  scanSessions(cliType, sessionsPath, projectPath) {
    const sessions = [];
    if (!sessionsPath || !projectPath) return sessions;

    try {
      if (!fs.existsSync(sessionsPath)) return sessions;

      // For Kode: scan projects, sessions, conversations subdirectories (one level)
      if (cliType === 'kode' && (sessionsPath.includes('projects') || sessionsPath.includes('sessions') || sessionsPath.includes('conversations'))) {
        const subdirs = fs.readdirSync(sessionsPath);
        for (const subdir of subdirs) {
          const subdirPath = path.join(sessionsPath, subdir);
          try {
            const stat = fs.statSync(subdirPath);
            if (stat.isDirectory()) {
              sessions.push(...this.scanSessionFiles(cliType, subdirPath, projectPath));
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      return this.scanSessionFiles(cliType, sessionsPath, projectPath);
    } catch (error) {
      console.warn(`Warning: Could not scan ${cliType} sessions:`, error.message);
    }

    return sessions;
  }

  scanSessionFiles(cliType, sessionsPath, projectPath) {
    const sessions = [];

    try {
      const files = fs.readdirSync(sessionsPath);
      for (const file of files) {
        if (file.endsWith('.json') || file.endsWith('.session') || file.endsWith('.jsonl')) {
          try {
            const filePath = path.join(sessionsPath, file);
            let sessionData;

            if (file.endsWith('.jsonl')) {
              const content = fs.readFileSync(filePath, 'utf8');
              const lines = content.trim().split('\n').filter(line => line.trim());
              const messages = lines.map(line => JSON.parse(line));

              if (messages.length === 0) continue;
              sessionData = this.parseJSONLSession(messages, file);
            } else {
              const content = fs.readFileSync(filePath, 'utf8');
              sessionData = JSON.parse(content);
            }

            if (this.isProjectSession(sessionData, projectPath)) {
              sessions.push({
                cliType,
                sessionId: sessionData.id || sessionData.sessionId || file.replace(/\.(json|session|jsonl)$/, ''),
                title: sessionData.title || sessionData.topic || 'Untitled',
                content: this.extractContent(sessionData),
                updatedAt: new Date(sessionData.updatedAt || sessionData.timestamp || fs.statSync(filePath).mtime),
                messageCount: sessionData.messageCount || this.countMessages(sessionData),
                projectPath
              });
            }
          } catch (error) {
            console.warn(`Warning: Could not parse ${file}:`, error.message);
          }
        }
      }
    } catch (error) {
      console.warn(`Warning: Could not scan files:`, error.message);
    }

    return sessions;
  }

  parseJSONLSession(messages, filename) {
    const firstMsg = messages[0];
    const lastMsg = messages[messages.length - 1];
    const userMessages = messages.filter(m => m.type === 'user' || m.role === 'user');

    let title = 'Untitled Session';
    if (userMessages.length > 0) {
      const firstUserMsg = userMessages[0];
      let content = firstUserMsg.message?.content || firstUserMsg.content || '';
      if (typeof content === 'object') {
        content = JSON.stringify(content);
      }
      if (typeof content === 'string' && content.trim()) {
        title = content.substring(0, 100) || title;
      }
    }

    const contentParts = messages
      .map(m => {
        if (m.message && typeof m.message === 'object') {
          return m.message.content || m.message.text || '';
        }
        return m.content || m.text || '';
      })
      .filter(text => text && typeof text === 'string' && text.trim());

    return {
      sessionId: firstMsg.sessionId || filename.replace('.jsonl', ''),
      title: title,
      content: contentParts.join(' '),
      timestamp: lastMsg.timestamp || new Date().toISOString(),
      projectPath: firstMsg.cwd || firstMsg.workingDirectory,
      messageCount: messages.filter(m => m.type === 'user' || m.type === 'assistant' || m.role === 'user' || m.role === 'assistant').length,
      messages: messages
    };
  }

  scanAllCLISessions(projectPath) {
    const allSessions = [];
    const cliPathsMap = pathConfigLoader.getAllCLISessionPaths();

    for (const [cliType, sessionsPaths] of Object.entries(cliPathsMap)) {
      for (const sessionsPath of sessionsPaths) {
        const sessions = this.scanSessions(cliType, sessionsPath, projectPath);
        allSessions.push(...sessions);
      }
    }

    return allSessions;
  }

  isProjectSession(session, projectPath) {
    const sessionProject = session.projectPath || session.workingDirectory;
    if (!sessionProject) return true;

    return sessionProject === projectPath ||
           sessionProject.startsWith(projectPath) ||
           projectPath.startsWith(sessionProject);
  }

  extractContent(sessionData) {
    if (sessionData.content && typeof sessionData.content === 'string') {
      return sessionData.content;
    }

    if (sessionData.messages && Array.isArray(sessionData.messages)) {
      return sessionData.messages
        .map(msg => {
          if (msg.message && typeof msg.message === 'object') {
            const content = msg.message.content || msg.message.text || '';
            return this.extractTextFromContent(content);
          }
          const content = msg.content || msg.text || '';
          return this.extractTextFromContent(content);
        })
        .filter(text => text && typeof text === 'string' && text.trim())
        .join(' ');
    }

    if (Array.isArray(sessionData)) {
      return sessionData
        .map(item => {
          if (item.message && typeof item.message === 'object') {
            const content = item.message.content || item.message.text || '';
            return this.extractTextFromContent(content);
          }
          const content = item.content || item.text || '';
          return this.extractTextFromContent(content);
        })
        .filter(text => text && typeof text === 'string' && text.trim())
        .join(' ');
    }

    return '';
  }

  extractTextFromContent(content) {
    if (typeof content === 'string') {
      return content;
    }

    if (Array.isArray(content)) {
      return content
        .map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object') {
            return item.text || item.content || '';
          }
          return '';
        })
        .filter(text => text && typeof text === 'string')
        .join(' ');
    }

    if (content && typeof content === 'object') {
      return content.text || content.content || JSON.stringify(content);
    }

    return '';
  }

  countMessages(sessionData) {
    if (sessionData.messages) {
      return Array.isArray(sessionData.messages) ? sessionData.messages.length : 0;
    }

    if (Array.isArray(sessionData)) {
      return sessionData.length;
    }

    return 0;
  }
}

class SessionFilter {
  applyFilters(sessions, options, projectPath) {
    let filtered = sessions.filter(s => s.projectPath === projectPath);

    if (options.cli) {
      filtered = filtered.filter(s => s.cliType === options.cli);
    }

    if (options.search) {
      const term = options.search.toLowerCase();
      filtered = filtered.filter(s =>
        s.title.toLowerCase().includes(term) ||
        s.content.toLowerCase().includes(term)
      );
    }

    filtered.sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));

    if (options.limit) {
      filtered = filtered.slice(0, options.limit);
    }

    return filtered;
  }
}

class HistoryFormatter {
  formatSummary(sessions) {
    if (sessions.length === 0) {
      return '📭 当前项目暂无历史会话\n\n💡 尝试: /stigmergy-resume --search <关键词>';
    }

    let response = `📁 **项目历史会话**\n\n📊 共找到 ${sessions.length} 个\n\n`;

    const byCLI = {};
    sessions.forEach(s => {
      if (!byCLI[s.cliType]) byCLI[s.cliType] = [];
      byCLI[s.cliType].push(s);
    });

    Object.entries(byCLI).forEach(([cli, cliSessions]) => {
      const icon = this.getCLIIcon(cli);
      response += `${icon} **${cli.toUpperCase()}** (${cliSessions.length}个)\n`;
      cliSessions.slice(0, 3).forEach((s, i) => {
        response += `   ${i + 1}. ${s.title.substring(0, 50)}...\n`;
        response += `      💬 ${s.messageCount}条消息\n`;
      });
      if (cliSessions.length > 3) {
        response += `   ... 还有 ${cliSessions.length - 3} 个\n`;
      }
      response += '\n';
    });

    response += '💡 **使用:** /stigmergy-resume --cli <工具> | --search <词> | --format timeline';
    return response;
  }

  formatTimeline(sessions) {
    if (sessions.length === 0) return '📭 暂无会话';
    let response = '⏰ **时间线**\n\n';
    sessions.forEach((s, i) => {
      const icon = this.getCLIIcon(s.cliType);
      response += `${i + 1}. ${icon} ${s.title}\n   💬 ${s.messageCount}条\n\n`;
    });
    return response;
  }

  formatDetailed(sessions) {
    if (sessions.length === 0) return '📭 暂无会话';
    let response = '📋 **详细**\n\n';
    sessions.forEach((s, i) => {
      const icon = this.getCLIIcon(s.cliType);
      response += `${i + 1}. ${icon} **${s.title}**\n   🔧 ${s.cliType}\n   💬 ${s.messageCount}条\n\n`;
    });
    return response;
  }

  formatContext(session) {
    if (!session) return '📭 暂无上下文';
    return `🔄 **上下文**\n\n${session.title}\n💬 ${session.messageCount}条消息\n\n${session.content.substring(0, 500)}...`;
  }

  getCLIIcon(cliType) {
    const icons = {
      'claude': '🟢',
      'gemini': '🔵',
      'qwen': '🟡',
      'iflow': '🔴',
      'codebuddy': '🟣',
      'codex': '🟪',
      'qodercli': '🟠',
      'kode': '⚡'
    };
    return icons[cliType] || '🔹';
  }
}

class HistoryQuery {
  constructor() {
    this.scanner = new SessionScanner();
    this.filter = new SessionFilter();
    this.formatter = new HistoryFormatter();
  }

  queryHistory(options, projectPath) {
    try {
      const allSessions = this.scanner.scanAllCLISessions(projectPath);
      const filtered = this.filter.applyFilters(allSessions, options, projectPath);

      let response;
      switch (options.format) {
        case 'timeline':
          response = this.formatter.formatTimeline(filtered);
          break;
        case 'detailed':
          response = this.formatter.formatDetailed(filtered);
          break;
        case 'context':
          response = this.formatter.formatContext(filtered[0]);
          break;
        default:
          response = this.formatter.formatSummary(filtered);
      }

      return {
        response,
        suggestions: ['/stigmergy-resume --format timeline', '/stigmergy-resume --search <关键词>']
      };
    } catch (error) {
      return {
        response: `❌ 查询失败: ${error.message}`,
        suggestions: []
      };
    }
  }
}

class KodeHistoryHandler {
  constructor() {
    this.historyQuery = new HistoryQuery();
  }

  async handleCommand(input, context) {
    if (!input.startsWith('/stigmergy-resume') && !input.startsWith('/history') && !input.startsWith('/resume')) return null;

    try {
      const options = this.buildQuery(input);
      const result = this.historyQuery.queryHistory(options, 'D:\stigmergy-CLI-Multi-Agents\test-fix-verification');

      return {
        response: result.response,
        suggestions: result.suggestions
      };
    } catch (error) {
      return {
        response: `❌ 失败: ${error.message}`,
        suggestions: []
      };
    }
  }

  buildQuery(input) {
    const options = {
      limit: 10,
      format: 'summary',
      timeRange: 'all',
      cli: null,
      search: null
    };

    const parts = input.replace(/^\/(stigmergy-resume|history|resume)\s*/i, '').trim().split(/\s+/).filter(p => p.length > 0);

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i].toLowerCase();

      if (part === '--cli' && i + 1 < parts.length) {
        options.cli = parts[++i];
      } else if (part === '--search' && i + 1 < parts.length) {
        options.search = parts[++i];
      } else if (part === '--limit' && i + 1 < parts.length) {
        options.limit = parseInt(parts[++i]);
      } else if (part === '--format' && i + 1 < parts.length) {
        options.format = parts[++i];
      } else if (part === '--today') {
        options.timeRange = 'today';
      }
    }

    return options;
  }
}

const handler = new KodeHistoryHandler();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { KodeHistoryHandler, handler };
}

// Kode CLI integration
if (typeof kode !== 'undefined' && kode.addExtension) {
  kode.addExtension('history', handler.handleCommand);
} else if (typeof global !== 'undefined' && global.kode) {
  global.kode.addExtension('history', handler.handleCommand);
}