/**
 * SkillGenerator - 自主技能创建引擎
 *
 * 核心功能：
 * 1. 从经验教训提取 → 自动创建新技能
 * 2. 优化已有技能
 * 3. 写入 ~/.stigmergy/skills/ 目录
 * 4. 与 EvolveLoop 集成实现持续技能进化
 */

const fs = require("fs");
const path = require("path");

class SkillGenerator {
  constructor(options = {}) {
    this.verbose = options.verbose || false;

    // 技能存储目录
    this.skillsDir =
      options.skillsDir ||
      path.join(require("os").homedir(), ".stigmergy", "skills");

    // 进化记录目录
    this.evolutionsDir =
      options.evolutionsDir ||
      path.join(
        require("os").homedir(),
        ".stigmergy",
        "soul-state",
        "evolutions",
      );

    // 技能模板
    this.template = options.template || this._getDefaultTemplate();

    // 已创建的技能记录
    this.createdSkills = new Map();

    // 确保目录存在
    this._ensureDirectories();
  }

  /**
   * 从经验教训创建新技能
   * @param {Object} experience - 经验数据
   * @returns {Promise<Object>} 创建结果
   */
  async createFromExperience(experience) {
    const { lessons, patterns, improvements, context } = experience;

    if (this.verbose) {
      console.log("[SkillGenerator] 🔧 Creating skill from experience...");
    }

    // 1. 分析经验，生成技能定义
    const skillDefinition = await this._analyzeAndDefineSkill(
      lessons,
      patterns,
      improvements,
      context,
    );

    // 2. 检查是否需要创建新技能还是优化已有技能
    if (skillDefinition.type === "new") {
      return this._createNewSkill(skillDefinition);
    } else {
      return this._optimizeExistingSkill(skillDefinition);
    }
  }

  /**
   * 创建全新技能
   * @private
   */
  async _createNewSkill(definition) {
    const { name, description, tags, content, requires } = definition;

    // 验证技能名称
    const validName = this._validateSkillName(name);

    // 创建技能目录
    const skillPath = path.join(this.skillsDir, validName);
    const skillFilePath = path.join(skillPath, "SKILL.md");

    if (fs.existsSync(skillPath)) {
      console.warn(`[SkillGenerator] Skill already exists: ${validName}`);
      return { success: false, reason: "exists", name: validName };
    }

    // 创建目录
    fs.mkdirSync(skillPath, { recursive: true });

    // 生成技能内容
    const skillContent = this._generateSkillContent({
      name: validName,
      description,
      tags,
      requires,
      content,
      autoGenerated: true,
    });

    // 写入文件
    fs.writeFileSync(skillFilePath, skillContent, "utf8");

    // 记录创建
    this.createdSkills.set(validName, {
      type: "new",
      createdAt: new Date().toISOString(),
      definition,
    });

    // 写入进化记录
    this._recordEvolution("created", validName, definition);

    if (this.verbose) {
      console.log(`[SkillGenerator] ✅ Created new skill: ${validName}`);
    }

    return {
      success: true,
      type: "new",
      name: validName,
      path: skillFilePath,
    };
  }

  /**
   * 优化已有技能
   * @private
   */
  async _optimizeExistingSkill(definition) {
    const { existingName, improvements, newContent } = definition;

    const skillPath = path.join(this.skillsDir, existingName);
    const skillFilePath = path.join(skillPath, "SKILL.md");

    if (!fs.existsSync(skillFilePath)) {
      console.warn(
        `[SkillGenerator] Existing skill not found: ${existingName}`,
      );
      return { success: false, reason: "not_found" };
    }

    // 读取现有内容
    const existingContent = fs.readFileSync(skillFilePath, "utf8");

    // 应用改进
    const improvedContent = this._applyImprovements(
      existingContent,
      improvements,
      newContent,
    );

    // 备份原文件
    const backupPath = path.join(skillPath, `SKILL.md.backup.${Date.now()}`);
    fs.copyFileSync(skillFilePath, backupPath);

    // 写入改进版本
    fs.writeFileSync(skillFilePath, improvedContent, "utf8");

    // 记录优化
    this.createdSkills.set(existingName, {
      type: "optimized",
      optimizedAt: new Date().toISOString(),
      definition,
      backupPath,
    });

    // 写入进化记录
    this._recordEvolution("optimized", existingName, definition);

    if (this.verbose) {
      console.log(`[SkillGenerator] ✅ Optimized skill: ${existingName}`);
    }

    return {
      success: true,
      type: "optimized",
      name: existingName,
      backupPath,
    };
  }

  /**
   * 分析并定义技能
   * @private
   */
  async _analyzeAndDefineSkill(lessons, patterns, improvements, context) {
    // 智能决定是创建新技能还是优化已有技能

    // 检查是否有匹配的现有技能
    const existingSkill = await this._findMatchingSkill(context);

    if (existingSkill) {
      // 优化已有技能
      return {
        type: "optimize",
        existingName: existingSkill.name,
        improvements,
        newContent: this._generateImprovementsContent(lessons, improvements),
      };
    }

    // 创建新技能
    return {
      type: "new",
      name: this._generateSkillName(context, improvements),
      description: this._generateDescription(lessons, improvements),
      tags: this._extractTags(patterns, improvements),
      requires: ["two-agent-loop"], // 强制依赖
      content: this._generateSkillContentFromLessons(lessons, improvements),
    };
  }

  /**
   * 查找匹配的现有技能
   * @private
   */
  async _findMatchingSkill(context) {
    if (!fs.existsSync(this.skillsDir)) {
      return null;
    }

    const entries = fs.readdirSync(this.skillsDir, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      // 简单匹配：检查名称是否包含关键词
      const skillName = entry.name.toLowerCase();
      const keywords = this._extractKeywords(context);

      for (const keyword of keywords) {
        if (skillName.includes(keyword.toLowerCase())) {
          return { name: entry.name };
        }
      }
    }

    return null;
  }

  /**
   * 提取关键词
   * @private
   */
  _extractKeywords(context) {
    const text = JSON.stringify(context);
    // 简单提取：匹配连续的中文或英文单词
    const matches = text.match(/[\u4e00-\u9fa5]{2,}|[a-zA-Z]{3,}/g) || [];
    return [...new Set(matches)].slice(0, 5);
  }

  /**
   * 验证技能名称
   * @private
   */
  _validateSkillName(name) {
    // 转换为 kebab-case
    return name
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fa5]/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }

  /**
   * 生成技能名称
   * @private
   */
  _generateSkillName(context, improvements) {
    const keywords = this._extractKeywords(context);

    if (keywords.length > 0) {
      return `auto-${keywords[0]}-skill`;
    }

    // 基于改进类型生成
    if (improvements?.includes("optimization")) {
      return `auto-optimization-skill-${Date.now()}`;
    }

    return `auto-generated-skill-${Date.now()}`;
  }

  /**
   * 生成描述
   * @private
   */
  _generateDescription(lessons, improvements) {
    const parts = [];

    if (lessons?.length > 0) {
      parts.push(`从 ${lessons.length} 个经验教训中提取`);
    }

    if (improvements?.length > 0) {
      parts.push(`实现 ${improvements.join(", ")}`);
    }

    return parts.join("，") || "自动生成的技能";
  }

  /**
   * 提取标签
   * @private
   */
  _extractTags(patterns, improvements) {
    const tags = new Set(["auto-generated", "evolution"]);

    if (patterns) {
      patterns.forEach((p) => tags.add(p.type || p));
    }

    if (improvements) {
      improvements.forEach((i) => tags.add(i));
    }

    return Array.from(tags).slice(0, 6);
  }

  /**
   * 生成技能内容 (从经验教训)
   * @private
   */
  _generateSkillContentFromLessons(lessons, improvements) {
    let content = "# 自动生成的技能\n\n";
    content += "## 概述\n\n";
    content += "基于进化经验自动创建的技能。\n\n";

    if (lessons?.length > 0) {
      content += "## 经验教训\n\n";
      lessons.forEach((lesson, i) => {
        content += `${i + 1}. ${lesson}\n`;
      });
      content += "\n";
    }

    if (improvements?.length > 0) {
      content += "## 改进要点\n\n";
      improvements.forEach((imp, i) => {
        content += `${i + 1}. ${imp}\n`;
      });
      content += "\n";
    }

    content += "## 使用方式\n\n";
    content += "此技能通过 soul-evolution 自动进化机制创建。\n";

    return content;
  }

  /**
   * 生成技能内容 (完整模板)
   * @private
   */
  _generateSkillContent(data) {
    const { name, description, tags, requires, content, autoGenerated } = data;

    const frontmatter = [
      "---",
      `name: ${name}`,
      `description: ${description}`,
      `version: 1.0.0`,
      `tags: [${tags.join(", ")}]`,
      requires?.length > 0 ? `requires: [${requires.join(", ")}]` : null,
      autoGenerated ? `autoGenerated: true` : null,
      autoGenerated ? `generatedAt: ${new Date().toISOString()}` : null,
      "---",
      "",
    ]
      .filter(Boolean)
      .join("\n");

    return `${frontmatter}\n\n${content}`;
  }

  /**
   * 应用改进
   * @private
   */
  _applyImprovements(existingContent, improvements, newContent) {
    // 简单实现：在现有内容后追加改进内容
    return existingContent + "\n\n## 进化改进\n\n" + newContent;
  }

  /**
   * 生成改进内容
   * @private
   */
  _generateImprovementsContent(lessons, improvements) {
    let content = "";

    if (lessons?.length > 0) {
      content += "### 新增经验教训\n\n";
      lessons.forEach((lesson, i) => {
        content += `${i + 1}. ${lesson}\n`;
      });
      content += "\n";
    }

    if (improvements?.length > 0) {
      content += "### 改进要点\n\n";
      improvements.forEach((imp, i) => {
        content += `${i + 1}. ${imp}\n`;
      });
    }

    content += `\n*最后更新: ${new Date().toISOString()}*\n`;

    return content;
  }

  /**
   * 获取默认模板
   * @private
   */
  _getDefaultTemplate() {
    return {
      frontmatter: [
        "---",
        "name: {{name}}",
        "description: {{description}}",
        "version: 1.0.0",
        "tags: [{{tags}}]",
        "{{#if requires}}requires: [{{requires}}]{{/if}}",
        "autoGenerated: true",
        "---",
      ].join("\n"),
      structure: [
        "# {{name}}\n\n",
        "## 概述\n\n{{description}}\n\n",
        "{{#if lessons}}## 经验教训\n\n{{lessons}}\n\n{{/if}}",
        "{{#if improvements}}## 改进要点\n\n{{improvements}}\n\n{{/if}}",
        "## 使用方式\n\n此技能通过 soul-evolution 自动进化机制创建。\n",
      ].join(""),
    };
  }

  /**
   * 确保目录存在
   * @private
   */
  _ensureDirectories() {
    if (!fs.existsSync(this.skillsDir)) {
      fs.mkdirSync(this.skillsDir, { recursive: true });
    }
    if (!fs.existsSync(this.evolutionsDir)) {
      fs.mkdirSync(this.evolutionsDir, { recursive: true });
    }
  }

  /**
   * 记录进化
   * @private
   */
  _recordEvolution(action, skillName, definition) {
    const record = {
      timestamp: new Date().toISOString(),
      action,
      skillName,
      definition,
    };

    const recordPath = path.join(
      this.evolutionsDir,
      `evolution-${Date.now()}.json`,
    );

    fs.writeFileSync(recordPath, JSON.stringify(record, null, 2));
  }

  /**
   * 列出所有自动创建的技能
   */
  listCreatedSkills() {
    return Array.from(this.createdSkills.entries()).map(([name, data]) => ({
      name,
      ...data,
    }));
  }

  /**
   * 获取技能目录
   */
  getSkillsDir() {
    return this.skillsDir;
  }
}

module.exports = { SkillGenerator };
