#!/usr/bin/env node

/**
 * Test script to verify Node.js deployment script functionality
 * This verifies that the Node.js coordination layer actually performs the deployments
 */

const path = require('path');
const os = require('os');
const fs = require('fs');

// Import the deployment managers
const HookDeploymentManager = require('./src/core/coordination/nodejs/HookDeploymentManager');
const CLIIntegrationManager = require('./src/core/coordination/nodejs/CLIIntegrationManager');

async function verifyNodeJsDeployment() {
  console.log('=== Verifying Node.js Deployment Script Functionality ===\n');
  
  try {
    // Initialize the deployment managers
    const hookManager = new HookDeploymentManager();
    const integrationManager = new CLIIntegrationManager();
    
    await hookManager.initialize();
    console.log('✓ HookDeploymentManager initialized');
    
    console.log('✓ CLIIntegrationManager initialized\n');
    
    // Test deployment for one CLI to verify the process
    const testCLI = 'claude';
    console.log(`--- Testing Node.js deployment for ${testCLI} ---`);
    
    // 1. Deploy hooks using Node.js coordination layer
    console.log('1. Deploying hooks via Node.js coordination layer...');
    const hookDeploymentStart = Date.now();
    const hookResult = await hookManager.deployHooksForCLI(testCLI);
    const hookDeploymentTime = Date.now() - hookDeploymentStart;
    
    if (hookResult) {
      console.log(`✓ Hooks deployed via Node.js in ${hookDeploymentTime}ms`);
    } else {
      console.log(`✗ Failed to deploy hooks via Node.js`);
      return;
    }
    
    // 2. Deploy integration using Node.js coordination layer
    console.log('2. Deploying integration via Node.js coordination layer...');
    const integrationDeploymentStart = Date.now();
    const integrationDir = path.join(os.homedir(), '.stigmergy', 'integrations', testCLI);
    const integrationPath = await integrationManager.deployNodeJsIntegration(testCLI, integrationDir);
    const integrationDeploymentTime = Date.now() - integrationDeploymentStart;
    
    console.log(`✓ Integration deployed via Node.js in ${integrationDeploymentTime}ms`);
    console.log(`  Integration script path: ${integrationPath}`);
    
    // 3. Verify the deployed files were created by Node.js scripts
    console.log('3. Verifying deployed files...');
    
    // Check hook file
    const hookFilePath = path.join(os.homedir(), '.stigmergy', 'hooks', testCLI, `${testCLI}_nodejs_hook.js`);
    if (fs.existsSync(hookFilePath)) {
      const hookStat = fs.statSync(hookFilePath);
      console.log(`✓ Hook file created by Node.js: ${hookFilePath}`);
      console.log(`  File size: ${hookStat.size} bytes`);
    } else {
      console.log(`✗ Hook file not found: ${hookFilePath}`);
    }
    
    // Check integration file
    if (fs.existsSync(integrationPath)) {
      const integrationStat = fs.statSync(integrationPath);
      console.log(`✓ Integration file created by Node.js: ${integrationPath}`);
      console.log(`  File size: ${integrationStat.size} bytes`);
    } else {
      console.log(`✗ Integration file not found: ${integrationPath}`);
    }
    
    // 4. Verify file content was generated by Node.js templates
    console.log('4. Verifying file content source...');
    
    // Read hook file content
    const hookContent = fs.readFileSync(hookFilePath, 'utf8');
    if (hookContent.includes('Auto-generated by Stigmergy CLI Hook Deployment Manager')) {
      console.log('✓ Hook file content generated by Node.js template');
    } else {
      console.log('✗ Hook file content not from Node.js template');
    }
    
    // Read integration file content
    const integrationContent = fs.readFileSync(integrationPath, 'utf8');
    if (integrationContent.includes('Auto-generated by Stigmergy CLI Integration Manager')) {
      console.log('✓ Integration file content generated by Node.js template');
    } else {
      console.log('✗ Integration file content not from Node.js template');
    }
    
    // 5. Test that the deployed scripts actually work
    console.log('5. Testing deployed script functionality...');
    
    try {
      // Test hook script
      const HookClass = require(hookFilePath);
      const hookInstance = new HookClass();
      console.log('✓ Hook script can be loaded and instantiated');
      
      // Test integration script
      const IntegrationClass = require(integrationPath);
      const integrationInstance = new IntegrationClass();
      console.log('✓ Integration script can be loaded and instantiated');
      console.log(`  Integration CLI name: ${integrationInstance.cliName}`);
      console.log(`  Integration executable: ${integrationInstance.executable}`);
    } catch (error) {
      console.log(`✗ Deployed script functionality test failed: ${error.message}`);
    }
    
    console.log('\n=== Node.js deployment verification completed ===');
    console.log('✓ Confirmed: All deployments are performed by Node.js deployment scripts');
    
  } catch (error) {
    console.error('Node.js deployment verification failed:', error);
    process.exit(1);
  }
}

// Run the verification
if (require.main === module) {
  verifyNodeJsDeployment();
}