#!/usr/bin/env node

/**
 * Claude Hook Implementation - TDD Implementation
 * Phase 2: Hook System - GREEN Phase (Minimal implementation to pass tests)
 */

const BaseHook = require('./base-hook.cjs');

class ClaudeHook extends BaseHook {
    constructor(config = {}) {
        super('claude', {
            name: 'claude',
            version: '1.0.0',
            ...config
        });
    }

    processCommand(input, context = {}) {
        const result = super.processCommand(input, context);

        if (result.success && result.skillDetected) {
            // Add Claude-specific processing
            result.claudeContext = this.enhanceForClaude(result);
        }

        return result;
    }

    enhanceForClaude(result) {
        return {
            cliIntegration: true,
            nativeSkills: true,
            enhancedContext: true,
            supportedActions: ['translate', 'analyze', 'generate', 'document']
        };
    }

    isCLIAvailable() {
        try {
            // Check if Claude CLI is available
            const { spawnSync } = require('child_process');
            const result = spawnSync('claude', ['--version'], {
                stdio: 'pipe',
                timeout: 5000
            });
            return result.status === 0;
        } catch (error) {
            return false;
        }
    }

    getHookDirectory() {
        const os = require('os');
        const path = require('path');
        return path.join(os.homedir(), '.claude', 'hooks');
    }

    install() {
        const fs = require('fs');
        const path = require('path');
        const hookDir = this.getHookDirectory();

        try {
            if (!fs.existsSync(hookDir)) {
                fs.mkdirSync(hookDir, { recursive: true });
            }

            const hookFile = path.join(hookDir, 'stigmergy-skill.cjs');
            const hookContent = this.generateHookContent();

            fs.writeFileSync(hookFile, hookContent);
            return { success: true, hookPath: hookFile };
        } catch (error) {
            return { success: false, error: error.message };
        }
    }

    generateHookContent() {
        return `#!/usr/bin/env node
/**
 * Claude Hook for Stigmergy Skills
 * Auto-generated by stigmergy-skill package
 */

const SkillsDetector = require('${__dirname}/../skills-engine/skills-detector.cjs');
const detector = new SkillsDetector();

module.exports = {
    name: 'stigmergy-skill',
    description: 'Natural language skill detection and execution',
    version: '1.0.0',

    execute: async function(input, context) {
        const result = detector.detectSkill(input);
        if (result.skill && result.confidence > 5) {
            return {
                handled: true,
                skill: result.skill,
                confidence: result.confidence,
                parameters: result.parameters
            };
        }
        return { handled: false };
    }
};`;
    }
}

module.exports = ClaudeHook;