// Claude CLI ShareMem Integration
// Auto-generated by ShareMem v1.0.3
// Project: D:\stigmergy-CLI-Multi-Agents\test-end-to-end

const { spawn, execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

/**
 * 处理 /history 命令
 */
async function handleHistoryCommand(input, context) {
  try {
    console.log('🔍 Searching cross-CLI history...');

    // 构建查询命令
    const query = buildQuery(input);

    // 执行跨CLI会话扫描
    const sessions = await scanProjectSessions(query, context);

    // 格式化结�?    const response = formatResponse(sessions, query, context);

    return {
      response,
      suggestions: generateSuggestions(sessions, query)
    };
  } catch (error) {
    console.error('History command error:', error);
    return {
      response: `�?历史查询失败: ${error.message}`,
      suggestions: ['/history --help']
    };
  }
}

/**
 * 构建查询参数
 */
function buildQuery(input) {
  const options = {
    limit: 10,
    format: 'summary',
    timeRange: 'all',
    cli: null,
    search: null
  };

  const cleanInput = input.replace(/^\/history\s*/i, '').trim();
  const parts = cleanInput.split(/\s+/).filter(p => p.length > 0);

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].toLowerCase();

    if (part === '--cli' && i + 1 < parts.length) {
      options.cli = parts[++i];
    } else if (part === '--search' && i + 1 < parts.length) {
      options.search = parts[++i];
    } else if (part === '--limit' && i + 1 < parts.length) {
      options.limit = parseInt(parts[++i]);
    } else if (part === '--format') {
      const format = parts[++1]?.toLowerCase();
      if (['summary', 'timeline', 'detailed', 'context'].includes(format)) {
        options.format = format;
      }
    } else if (part === '--today') {
      options.timeRange = 'today';
    } else if (part === '--week') {
      options.timeRange = 'week';
    } else if (part === '--month') {
      options.timeRange = 'month';
    } else if (!part.startsWith('--') && !options.search) {
      options.search = part;
    }
  }

  return options;
}

/**
 * 扫描项目会话
 */
async function scanProjectSessions(query, context) {
  const projectPath = 'D:\stigmergy-CLI-Multi-Agents\test-end-to-end';
  const allSessions = [];

  // 扫描各个CLI的会�?  const cliPaths = {
    claude: path.join(require('os').homedir(), '.claude', 'sessions'),
    gemini: path.join(require('os').homedir(), '.gemini', 'sessions'),
    qwen: path.join(require('os').homedir(), '.qwen', 'sessions'),
    iflow: path.join(require('os').homedir(), '.iflow', 'stigmergy', 'sessions')
  };

  for (const [cliType, sessionsPath] of Object.entries(cliPaths)) {
    if (fs.existsSync(sessionsPath)) {
      try {
        const sessions = await scanCLISessions(cliType, sessionsPath, projectPath);
        allSessions.push(...sessions);
      } catch (error) {
        console.warn(`Failed to scan ${cliType} sessions:`, error.message);
      }
    }
  }

  // 应用过滤�?  let filteredSessions = allSessions;

  if (query.cli) {
    filteredSessions = filteredSessions.filter(s => s.cliType === query.cli);
  }

  if (query.search) {
    const searchLower = query.search.toLowerCase();
    filteredSessions = filteredSessions.filter(s =>
      s.title?.toLowerCase().includes(searchLower) ||
      s.content?.toLowerCase().includes(searchLower)
    );
  }

  if (query.timeRange !== 'all') {
    filteredSessions = filterByTimeRange(filteredSessions, query.timeRange);
  }

  // 按时间排序（最新的在前�?  filteredSessions.sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));

  return filteredSessions.slice(0, query.limit);
}

/**
 * 扫描特定CLI的会�? */
async function scanCLISessions(cliType, sessionsPath, projectPath) {
  const sessions = [];

  try {
    const files = fs.readdirSync(sessionsPath);

    for (const file of files) {
      if (file.endsWith('.json') || file.endsWith('.session')) {
        try {
          const filePath = path.join(sessionsPath, file);
          const content = fs.readFileSync(filePath, 'utf8');
          const session = JSON.parse(content);

          // 检查是否属于当前项�?          if (isProjectSession(session, projectPath)) {
            sessions.push({
              cliType,
              sessionId: session.id || session.sessionId || file.replace(/\.(json|session)$/, ''),
              title: session.title || session.topic || 'Untitled',
              content: session.content || session.messages?.map(m => m.content).join(' ') || '',
              updatedAt: new Date(session.updatedAt || session.timestamp || fs.statSync(filePath).mtime),
              messageCount: session.messageCount || session.messages?.length || 0,
              projectPath
            });
          }
        } catch (error) {
          // 忽略单个文件解析错误
        }
      }
    }
  } catch (error) {
    console.warn(`Error scanning ${cliType} sessions:`, error.message);
  }

  return sessions;
}

/**
 * 检查会话是否属于当前项�? */
function isProjectSession(session, projectPath) {
  const sessionProject = session.projectPath || session.workingDirectory;
  if (!sessionProject) return true; // 如果没有项目路径，假设属于当前项�?
  return sessionProject === projectPath ||
         sessionProject.startsWith(projectPath) ||
         projectPath.startsWith(sessionProject);
}

/**
 * 按时间范围过�? */
function filterByTimeRange(sessions, timeRange) {
  const now = new Date();

  return sessions.filter(session => {
    const sessionDate = new Date(session.updatedAt);

    switch (timeRange) {
      case 'today':
        return sessionDate.toDateString() === now.toDateString();
      case 'week':
        const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
        return sessionDate >= weekAgo;
      case 'month':
        const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
        return sessionDate >= monthAgo;
      default:
        return true;
    }
  });
}

/**
 * 格式化响�? */
function formatResponse(sessions, query, context) {
  if (sessions.length === 0) {
    return `📭 当前项目暂无历史会话\n\n💡 **提示:**\n�?尝试: /history --search <关键�?\n�?检�? 其他CLI工具是否有会话文件`;
  }

  switch (query.format) {
    case 'timeline':
      return formatTimeline(sessions);
    case 'detailed':
      return formatDetailed(sessions);
    case 'context':
      return formatContext(sessions[0]);
    default:
      return formatSummary(sessions, context);
  }
}

/**
 * 格式化摘要视�? */
function formatSummary(sessions, context) {
  let response = `📁 **项目历史会话**\n\n📊 共找�?${sessions.length} 个会话\n\n`;

  // 按CLI分组
  const byCLI = {};
  sessions.forEach(session => {
    if (!byCLI[session.cliType]) byCLI[session.cliType] = [];
    byCLI[session.cliType].push(session);
  });

  Object.entries(byCLI).forEach(([cli, cliSessions]) => {
    const icon = cli === 'claude' ? '🟢' : '🔵';
    response += `${icon} **${cli.toUpperCase()}** (${cliSessions.length}�?\n`;

    cliSessions.slice(0, 3).forEach((session, i) => {
      const date = formatDate(session.updatedAt);
      const title = session.title.substring(0, 50);
      response += `   ${i + 1}. ${title}...
`;
      response += `      📅 ${date} �?💬 ${session.messageCount}条消息\n`;
    });

    if (cliSessions.length > 3) {
      response += `   ... 还有 ${cliSessions.length - 3} 个会话\n`;
    }
    response += '\n';
  });

  response += `💡 **使用方法:**\n`;
  response += `�?`/history --cli <工具>` - 查看特定CLI\n`;
  response += `�?`/history --search <关键�?` - 搜索内容\n`;
  response += `�?`/history --format timeline` - 时间线视图`;

  return response;
}

/**
 * 格式化时间线视图
 */
function formatTimeline(sessions) {
  let response = `�?**时间线视�?*\n\n`;

  sessions.forEach((session, index) => {
    const date = formatDate(session.updatedAt);
    const cliIcon = getCLIIcon(session.cliType);

    response += `${index + 1}. ${cliIcon} ${session.title}\n`;
    response += `   📅 ${date} �?💬 ${session.messageCount}条消息\n`;
    response += `   🔑 ${session.cliType}:${session.sessionId}\n\n`;
  });

  return response;
}

/**
 * 格式化详细视�? */
function formatDetailed(sessions) {
  let response = `📋 **详细视图**\n\n`;

  sessions.forEach((session, index) => {
    const cliIcon = getCLIIcon(session.cliType);
    const date = session.updatedAt.toLocaleString();

    response += `${index + 1}. ${cliIcon} **${session.title}**\n`;
    response += `   📅 ${date}\n`;
    response += `   🔧 CLI: ${session.cliType}\n`;
    response += `   💬 消息�? ${session.messageCount}\n`;
    response += `   🆔 会话ID: \`${session.sessionId}\`\n\n`;
  });

  return response;
}

/**
 * 格式化上下文视图
 */
function formatContext(session) {
  if (!session) {
    return `📭 暂无可恢复的上下文。`;
  }

  let response = `🔄 **上下文恢�?*\n\n`;
  response += `📅 会话时间: ${session.updatedAt.toLocaleString()}\n`;
  response += `🔧 来源CLI: ${session.cliType}\n`;
  response += `💬 消息�? ${session.messageCount}\n`;
  response += `🆔 会话ID: ${session.sessionId}\n\n`;
  response += `---\n\n`;
  response += `**上次讨论内容:**\n`;
  response += session.content.substring(0, 500);
  if (session.content.length > 500) {
    response += `...`;
  }

  return response;
}

/**
 * 格式化日�? */
function formatDate(date) {
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  const days = Math.floor(diff / (24 * 60 * 60 * 1000));

  if (days === 0) {
    return date.toLocaleTimeString();
  } else if (days === 1) {
    return '昨天';
  } else if (days < 7) {
    return `${days}天前`;
  } else if (days < 30) {
    return `${Math.floor(days / 7)}周前`;
  } else {
    return `${Math.floor(days / 30)}个月前`;
  }
}

/**
 * 获取CLI图标
 */
function getCLIIcon(cliType) {
  const icons = {
    'claude': '🟢',
    'gemini': '🔵',
    'qwen': '🟡',
    'iflow': '🔴',
    'codebuddy': '🟣',
    'codex': '🟪',
    'qodercli': '🟠'
  };
  return icons[cliType] || '🔹';
}

/**
 * 生成建议
 */
function generateSuggestions(sessions, query) {
  const suggestions = [];

  if (sessions.length > 0) {
    suggestions.push('/history --format context');
    suggestions.push('/history --format timeline');

    if (sessions[0].cliType) {
      suggestions.push(`/history --cli ${sessions[0].cliType}`);
    }
  }

  suggestions.push('/history --search "react"');
  suggestions.push('/history --today');

  return suggestions.slice(0, 5);
}

// 导出处理�?module.exports = {
  handleHistoryCommand
};

// 注册到Claude CLI
if (typeof global !== 'undefined' && global.claudeCLI) {
  global.claudeCLI.addSlashCommand('/history', handleHistoryCommand);
}
