/**
 * Stigmergy Help Injector (安全版本)
 * 安全地将 stigmergy 命令帮助信息注入到各 CLI 工具
 *
 * 策略：
 * 1. 创建独立的帮助文件，不修改原有配置
 * 2. 使用注释包裹，确保不影响 CLI 解析
 * 3. 提供备份和回滚机制
 * 4. 验证文件格式
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

class StigmergyHelpInjector {
  constructor() {
    this.homeDir = os.homedir();
    this.supportedCLIs = [
      'claude',
      'gemini',
      'qwen',
      'iflow',
      'qodercli',
      'codebuddy',
      'codex',
      'copilot'
    ];
  }

  /**
   * 生成安全的帮助内容（使用 HTML 注释）
   * 这样不会破坏 markdown 解析
   */
  generateSafeHelpContent() {
    return `
<!--
STIGMERGY COMMANDS REFERENCE
============================

## Skills Management
stigmergy skill install <collection>  - Install skill collection
stigmergy skill list                - List installed skills
stigmergy skill read <name>          - Read skill content
stigmergy skill validate <path>       - Validate a skill
stigmergy skill remove <name>         - Remove a skill

## Cross-CLI Communication
stigmergy <cli> "<task>"            - Call another CLI tool
stigmergy route "<task>"             - Smart routing to best CLI
stigmergy ask <cli> "<task>"          - Ask specific CLI

## Session Management
stigmergy resume                     - Resume previous session
stigmergy resume <cli> <limit>        - Resume from specific CLI
stigmergy interactive                - Enter interactive mode

## Configuration
stigmergy status                     - Check system status
stigmergy deploy                     - Deploy configurations
stigmergy install                    - Install CLI tools

-->
`;
  }

  /**
   * 生成独立的帮助文件
   */
  generateHelpFile() {
    return `# Stigmergy Commands Reference

This document provides a quick reference for Stigmergy commands.

## Skills Management

### Install Skills
\`\`\`bash
# Install a predefined collection
stigmergy skill install anthropics
stigmergy skill install vercel

# Install from GitHub
stigmergy skill install username/skills
\`\`\`

### List Skills
\`\`\`bash
stigmergy skill list
\`\`\`

### Read Skill
\`\`\`bash
stigmergy skill read <skill-name>
\`\`\`

### Other Commands
\`\`\`bash
stigmergy skill validate <path>
stigmergy skill remove <name>
\`\`\`

## Cross-CLI Communication

\`\`\`bash
# Call specific CLI
stigmergy claude "write a function"
stigmergy gemini "translate this text"
stigmergy qwen "分析这段代码"

# Smart routing
stigmergy route "analyze this code"

# Ask specific CLI
stigmergy ask qwen "help me"
\`\`\`

## Session Management

\`\`\`bash
# Resume sessions
stigmergy resume
stigmergy resume qwen 10
stigmergy resume --list
\`\`\`

## Interactive Mode

\`\`\`bash
stigmergy interactive
\`\`\`

In interactive mode:
- \`help\` - Show available commands
- \`skill-l\` - List skills
- \`use <cli>\` - Switch CLI
- \`route <task>\` - Smart routing
- \`exit\` - Exit

---
*Generated by Stigmergy CLI*
`;
  }

  /**
   * 安全地注入帮助信息 - 创建独立文件而不是修改原有文件
   */
  async injectHelpForCLI(cliName) {
    const configDirs = {
      iflow: '.iflow',
      qwen: '.qwen',
      codebuddy: '.codebuddy',
      qodercli: '.qoder',
      claude: '.claude',
      gemini: '.gemini',
      codex: '.codex',
      copilot: '.copilot'
    };

    const configDir = configDirs[cliName];
    if (!configDir) {
      console.warn(`[HELP_INJECTOR] No config directory for ${cliName}`);
      return false;
    }

    const fullPath = path.join(this.homeDir, configDir);

    try {
      // 确保配置目录存在
      if (!fs.existsSync(fullPath)) {
        console.warn(`[HELP_INJECTOR] Config directory not found: ${fullPath}`);
        return false;
      }

      // 方案 1: 创建独立的帮助文件（最安全）
      const helpFilePath = path.join(fullPath, 'STIGMERGY_COMMANDS.md');
      const helpContent = this.generateHelpFile();

      fs.writeFileSync(helpFilePath, helpContent, 'utf8');
      console.log(`[HELP_INJECTOR] Created help file: ${helpFilePath}`);

      // 方案 2: 在原文件末尾添加注释（可选，更安全的方式）
      await this.appendSafeComment(cliName, fullPath);

      return true;

    } catch (error) {
      console.error(`[HELP_INJECTOR] Failed to inject help for ${cliName}:`, error.message);
      return false;
    }
  }

  /**
   * 在文件末尾添加安全的注释
   */
  async appendSafeComment(cliName, configDir) {
    const mdFilenames = {
      iflow: 'iflow.md',
      qwen: 'qwen.md',
      codebuddy: 'codebuddy.md',
      qodercli: 'qoder.md',
      claude: 'claude.md',
      gemini: 'gemini.md'
    };

    const filename = mdFilenames[cliName];
    if (!filename) {
      return;
    }

    const filePath = path.join(configDir, filename);

    try {
      // 检查文件是否存在
      if (!fs.existsSync(filePath)) {
        return;
      }

      let content = fs.readFileSync(filePath, 'utf8');

      // 检查是否已经添加过
      if (content.includes('<!-- STIGMERGY_COMMANDS -->')) {
        return;
      }

      // 在文件末尾添加安全的注释
      const safeComment = `

<!-- STIGMERGY_COMMANDS -->
<!-- Stigmergy CLI commands reference available at: STIGMERGY_COMMANDS.md -->
<!-- Run: stigmergy help for more information -->
`;

      content = content + safeComment;

      // 写回文件
      fs.writeFileSync(filePath, content, 'utf8');
      console.log(`[HELP_INJECTOR] Added safe comment to ${filePath}`);

    } catch (error) {
      console.warn(`[HELP_INJECTOR] Failed to add comment: ${error.message}`);
    }
  }

  /**
   * 回滚（删除帮助信息）
   */
  async rollbackForCLI(cliName) {
    const configDirs = {
      iflow: '.iflow',
      qwen: '.qwen',
      codebuddy: '.codebuddy',
      qodercli: '.qoder',
      claude: '.claude',
      gemini: '.gemini'
    };

    const configDir = configDirs[cliName];
    if (!configDir) {
      return false;
    }

    const fullPath = path.join(this.homeDir, configDir);
    const helpFilePath = path.join(fullPath, 'STIGMERGY_COMMANDS.md');

    try {
      // 删除帮助文件
      if (fs.existsSync(helpFilePath)) {
        fs.unlinkSync(helpFilePath);
        console.log(`[HELP_INJECTOR] Removed help file: ${helpFilePath}`);
      }

      // 移除 markdown 文件中的注释（可选）
      const mdFilenames = {
        iflow: 'iflow.md',
        qwen: 'qwen.md',
        codebuddy: 'codebuddy.md',
        qodercli: 'qoder.md',
        claude: 'claude.md',
        gemini: 'gemini.md'
      };

      const filename = mdFilenames[cliName];
      if (filename) {
        const mdPath = path.join(fullPath, filename);
        if (fs.existsSync(mdPath)) {
          let content = fs.readFileSync(mdPath, 'utf8');
          // 移除我们的注释标记
          content = content.replace(/\n<!-- STIGMERGY_COMMANDS -->[\s\S]*?<!-- Run: stigmergy help for more information -->\n?/g, '');
          fs.writeFileSync(mdPath, content, 'utf8');
          console.log(`[HELP_INJECTOR] Removed comment from ${mdPath}`);
        }
      }

      return true;

    } catch (error) {
      console.error(`[HELP_INJECTOR] Rollback failed for ${cliName}:`, error.message);
      return false;
    }
  }

  /**
   * 验证帮助信息是否已注入
   */
  async verifyHelpInjection(cliName) {
    const configDirs = {
      iflow: '.iflow',
      qwen: '.qwen',
      codebuddy: '.codebuddy',
      qodercli: '.qoder',
      claude: '.claude',
      gemini: '.gemini'
    };

    const configDir = configDirs[cliName];
    if (!configDir) {
      return { injected: false, reason: 'No config directory' };
    }

    const fullPath = path.join(this.homeDir, configDir);
    const helpFilePath = path.join(fullPath, 'STIGMERGY_COMMANDS.md');

    try {
      const helpFileExists = fs.existsSync(helpFilePath);
      return {
        injected: helpFileExists,
        helpFilePath: helpFilePath,
        configDir: fullPath
      };
    } catch (error) {
      return {
        injected: false,
        reason: error.message,
        configDir: fullPath
      };
    }
  }

  /**
   * 为所有支持的 CLI 注入帮助信息
   */
  async injectHelpForAllCLIs() {
    console.log('[HELP_INJECTOR] Injecting Stigmergy help for all CLIs...');

    const results = [];
    for (const cliName of this.supportedCLIs) {
      const success = await this.injectHelpForCLI(cliName);
      results.push({ cli: cliName, success });
    }

    const successful = results.filter(r => r.success).length;
    console.log(`[HELP_INJECTOR] Injection complete: ${successful}/${this.supportedCLIs.length} CLIs updated`);

    return results;
  }
}

module.exports = StigmergyHelpInjector;
