// src/core/coordination/nodejs/HookDeploymentManager.js
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawn, spawnSync } = require('child_process');

class HookDeploymentManager {
  constructor() {
    this.deploymentDir = path.join(os.homedir(), '.stigmergy', 'hooks');
    this.supportedCLIs = [
      'claude',
      'gemini',
      'qwen',
      'iflow',
      'qodercli',
      'codebuddy',
      'codex',
      'copilot',
    ];
  }

  async initialize() {
    console.log('[HOOK_DEPLOYMENT] Initializing hook deployment manager...');
    await this.ensureDeploymentDirectory();
  }

  async ensureDeploymentDirectory() {
    if (!fs.existsSync(this.deploymentDir)) {
      fs.mkdirSync(this.deploymentDir, { recursive: true });
      console.log(
        `[HOOK_DEPLOYMENT] Created deployment directory: ${this.deploymentDir}`,
      );
    }
  }

  async deployHooksForCLI(cliName, options = {}) {
    console.log(`[HOOK_DEPLOYMENT] Deploying hooks for ${cliName}...`);

    if (!this.supportedCLIs.includes(cliName.toLowerCase())) {
      throw new Error(`Unsupported CLI: ${cliName}`);
    }

    try {
      // Create CLI-specific hook directory
      const cliHookDir = path.join(this.deploymentDir, cliName);
      if (!fs.existsSync(cliHookDir)) {
        fs.mkdirSync(cliHookDir, { recursive: true });
      }

      // Deploy Node.js specific hooks
      await this.deployNodeJsHooks(cliName, cliHookDir, options);

      console.log(
        `[HOOK_DEPLOYMENT] Hooks deployed successfully for ${cliName}`,
      );
      return true;
    } catch (error) {
      console.error(
        `[HOOK_DEPLOYMENT] Failed to deploy hooks for ${cliName}:`,
        error,
      );
      return false;
    }
  }

  async deployNodeJsHooks(cliName, hookDir, options) {
    console.log(`[HOOK_DEPLOYMENT] Deploying Node.js hooks for ${cliName}...`);

    // Create a basic hook template for Node.js
    const hookTemplate = this.generateNodeJsHookTemplate(cliName);
    const hookFilePath = path.join(hookDir, `${cliName}_nodejs_hook.js`);

    fs.writeFileSync(hookFilePath, hookTemplate);
    console.log(`[HOOK_DEPLOYMENT] Created Node.js hook: ${hookFilePath}`);

    // Make the hook executable
    try {
      fs.chmodSync(hookFilePath, 0o755);
      console.log(`[HOOK_DEPLOYMENT] Made hook executable: ${hookFilePath}`);
    } catch (error) {
      console.warn(
        `[HOOK_DEPLOYMENT] Failed to make hook executable: ${error.message}`,
      );
    }

    // Create configuration file
    const config = {
      cli: cliName,
      hookPath: hookFilePath,
      deploymentTime: new Date().toISOString(),
      version: '1.0.0-nodejs',
    };

    const configPath = path.join(hookDir, 'config.json');
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    console.log(`[HOOK_DEPLOYMENT] Created hook configuration: ${configPath}`);
  }

  generateNodeJsHookTemplate(cliName) {
    return `#!/usr/bin/env node
/**
 * Node.js Hook for ${cliName.toUpperCase()}
 * Auto-generated by Stigmergy CLI Hook Deployment Manager
 */
const fs = require('fs');
const path = require('path');
class ${this.capitalize(cliName)}NodeJsHook {
  constructor() {
    this.cliName = '${cliName}';
    this.hookDir = __dirname;
    this.logFile = path.join(this.hookDir, '${cliName}_hook.log');
  }
  async onUserPrompt(prompt, context) {
    this.log('INFO', `User prompt received: ${prompt}`);
    // Check for cross-CLI requests
    const crossCLIRequest = this.detectCrossCLIRequest(prompt);
    if (crossCLIRequest) {
      return await this.handleCrossCLIRequest(crossCLIRequest, context);
    }
    // Default processing
    return null;
  }
  async onToolUse(toolName, toolArgs, context) {
    this.log('INFO', `Tool use detected: ${toolName}`);
    return null;
  }
  async onResponseGenerated(response, context) {
    this.log('INFO', 'Response generated');
    return null;
  }
  detectCrossCLIRequest(prompt) {
    // Enhanced pattern matching for cross-CLI requests
    const patterns = [
      /(?:use|call|ask)\\s+(\\w+)\\s+(?:to|for)\\s+(.+)$/i,
      /(?:please\\s+)?(?:use|call|ask)\\s+(\\w+)\\s+(.+)$/i,
      /(\\w+)[,\\s]+(?:please\\s+)?(?:help\\s+me\\s+)?(.+)$/i,
      /请用(\\w+)\\s*帮我(.+)$/i,
      /调用(\\w+)\\s*来(.+)$/i,
      /用(\\w+)\\s*帮我(.+)$/i,
      /(\\w+)，(.+)$/i,
      /让(\\w+)\\s*(.+)$/i
    ];
    
    for (const pattern of patterns) {
      const match = prompt.match(pattern);
      if (match && match.length >= 3) {
        const targetCLI = match[1].toLowerCase();
        const task = match[2];
        
        // Validate that the target CLI is supported
        const supportedCLIs = [
          'claude', 'gemini', 'qwen', 'iflow', 'qodercli', 'codebuddy', 'codex', 'copilot'
        ];
        
        if (supportedCLIs.includes(targetCLI)) {
          return {
            targetCLI: targetCLI,
            task: task,
            source: this.cliName
          };
        }
      }
    }
    
    return null;
  }
  async handleCrossCLIRequest(request, context) {
    this.log('INFO', `Cross-CLI request detected: ${JSON.stringify(request)}`);
    
    // Validate the request
    if (!request.targetCLI || !request.task) {
      this.log('ERROR', 'Invalid cross-CLI request: missing targetCLI or task');
      return `[CROSS-CLI] Invalid request: missing targetCLI or task`;
    }
    
    // Check if the target CLI is the same as the source
    if (request.targetCLI === this.cliName) {
      this.log('WARN', 'Cross-CLI request to self ignored');
      return `[CROSS-CLI] Cannot call self (${request.targetCLI})`;
    }
    
    // Communicate with the coordination layer to execute the cross-CLI call
    try {
      // Dynamically load the CLCommunication module
      const modulePath = path.join(__dirname, '..', '..', '..', '..', 'src', 'core', 'coordination', 'nodejs', 'CLCommunication');
      const CLCommunication = require(modulePath);
      const communicator = new CLCommunication();
      
      const result = await communicator.executeTask(
        request.source, 
        request.targetCLI, 
        request.task, 
        context
      );
      
      if (result.success) {
        return `[CROSS-CLI] Response from ${request.targetCLI}: ${result.output}`;
      } else {
        return `[CROSS-CLI] Error from ${request.targetCLI}: ${result.error}`;
      }
    } catch (error) {
      this.log('ERROR', `Failed to handle cross-CLI request: ${error.message}`);
      return `[CROSS-CLI] Failed to execute ${request.targetCLI}: ${error.message}`;
    }
  }
  log(level, message) {
    const timestamp = new Date().toISOString();
    const logEntry = `[${timestamp}] [${level}] [${this.cliName.toUpperCase()}] ${message}\\n`;
    
    try {
      fs.appendFileSync(this.logFile, logEntry);
    } catch (error) {
      console.error('Failed to write to log file:', error);
    }
  }
  capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
// Export the hook class
module.exports = ${this.capitalize(cliName)}NodeJsHook;
// If run directly, instantiate and test
if (require.main === module) {
  const hook = new ${this.capitalize(cliName)}NodeJsHook();
  console.log('${cliName.toUpperCase()} Node.js Hook initialized');
}`;
  }
    
    // Check if the target CLI is the same as the source
    if (request.targetCLI === this.cliName) {
      this.log('WARN', 'Cross-CLI request to self ignored');
      return \`[CROSS-CLI] Cannot call self (\${request.targetCLI})\`;
    }
    
    // Communicate with the coordination layer to execute the cross-CLI call
    try {
      // Dynamically load the CLCommunication module
      const modulePath = path.join(__dirname, '..', '..', '..', '..', 'src', 'core', 'coordination', 'nodejs', 'CLCommunication');
      const CLCommunication = require(modulePath);
      const communicator = new CLCommunication();
      
      const result = await communicator.executeTask(
        request.source, 
        request.targetCLI, 
        request.task, 
        context
      );
      
      if (result.success) {
        return \`[CROSS-CLI] Response from \${request.targetCLI}: \${result.output}\`;
      } else {
        return \`[CROSS-CLI] Error from \${request.targetCLI}: \${result.error}\`;
      }
    } catch (error) {
      this.log('ERROR', \`Failed to handle cross-CLI request: \${error.message}\`);
      return \`[CROSS-CLI] Failed to execute \${request.targetCLI}: \${error.message}\`;
    }
  }

  log(level, message) {
    const timestamp = new Date().toISOString();
    const logEntry = \`[\${timestamp}] [\${level}] [\${this.cliName.toUpperCase()}] \${message}\\n\`;
    
    try {
      fs.appendFileSync(this.logFile, logEntry);
    } catch (error) {
      console.error('Failed to write to log file:', error);
    }
  }

  capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}

// Export the hook class
module.exports = ${this.capitalize(cliName)}NodeJsHook;

// If run directly, instantiate and test
if (require.main === module) {
  const hook = new ${this.capitalize(cliName)}NodeJsHook();
  console.log('${cliName.toUpperCase()} Node.js Hook initialized');
}
`;
  }

  capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  async undeployHooksForCLI(cliName) {
    console.log(`[HOOK_DEPLOYMENT] Undeploying hooks for ${cliName}...`);

    const cliHookDir = path.join(this.deploymentDir, cliName);
    if (fs.existsSync(cliHookDir)) {
      try {
        fs.rmSync(cliHookDir, { recursive: true, force: true });
        console.log(`[HOOK_DEPLOYMENT] Removed hook directory: ${cliHookDir}`);
        return true;
      } catch (error) {
        console.error(
          '[HOOK_DEPLOYMENT] Failed to remove hook directory:',
          error,
        );
        return false;
      }
    }

    console.log(`[HOOK_DEPLOYMENT] No hooks found for ${cliName}`);
    return true;
  }

  async listDeployedHooks() {
    if (!fs.existsSync(this.deploymentDir)) {
      return [];
    }

    const cliDirs = fs
      .readdirSync(this.deploymentDir, { withFileTypes: true })
      .filter((dirent) => dirent.isDirectory())
      .map((dirent) => dirent.name);

    const hooks = [];
    for (const cliName of cliDirs) {
      const configPath = path.join(this.deploymentDir, cliName, 'config.json');
      if (fs.existsSync(configPath)) {
        try {
          const config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
          hooks.push(config);
        } catch (error) {
          console.warn(
            `[HOOK_DEPLOYMENT] Failed to read config for ${cliName}:`,
            error.message,
          );
        }
      }
    }

    return hooks;
  }

  async validateHookDeployment(cliName) {
    console.log(
      `[HOOK_DEPLOYMENT] Validating hook deployment for ${cliName}...`,
    );

    const cliHookDir = path.join(this.deploymentDir, cliName);
    if (!fs.existsSync(cliHookDir)) {
      return { valid: false, error: 'Hook directory not found' };
    }

    const configPath = path.join(cliHookDir, 'config.json');
    if (!fs.existsSync(configPath)) {
      return { valid: false, error: 'Configuration file not found' };
    }

    const hookPath = path.join(cliHookDir, `${cliName}_nodejs_hook.js`);
    if (!fs.existsSync(hookPath)) {
      return { valid: false, error: 'Hook script not found' };
    }

    // Try to load the hook
    try {
      require(hookPath);
      return { valid: true, message: 'Hook deployment is valid' };
    } catch (error) {
      return { valid: false, error: `Failed to load hook: ${error.message}` };
    }
  }
}

module.exports = HookDeploymentManager;
