// CLI Adapter Generator
// 专门负责生成各CLI的基础适配器文件

const path = require('path');

class CLIAdapterGenerator {
  constructor() {
    this.supportedCLIs = [
      'claude', 'gemini', 'qwen', 'codebuddy', 'codex',
      'iflow', 'qodercli', 'copilot', 'kode'
    ];
  }

  generateForCLI(cliName) {
    return this.generateAdapterContent(cliName);
  }

  generateAdapterContent(cliName) {
    const currentProjectPath = process.cwd();

    switch (cliName.toLowerCase()) {
      case 'claude':
        return this.generateClaudeAdapter(currentProjectPath);
      case 'gemini':
        return this.generateGeminiAdapter(currentProjectPath);
      case 'qwen':
        return this.generateQwenAdapter(currentProjectPath);
      case 'codebuddy':
        return this.generateCodeBuddyAdapter(currentProjectPath);
      case 'codex':
        return this.generateCodexAdapter(currentProjectPath);
      case 'qodercli':
        return this.generateQoderCliAdapter(currentProjectPath);
      case 'iflow':
        return this.generateIFlowAdapter(currentProjectPath);
      case 'copilot':
        return this.generateCopilotAdapter(currentProjectPath);
      default:
        return this.generateGenericAdapter(cliName, currentProjectPath);
    }
  }

  generateClaudeAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * Claude CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class ClaudeHook {
  constructor() {
    this.toolName = 'claude';
    this.configPath = path.join(require('os').homedir(), '.claude', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.claude', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = ClaudeHook;
`;
  }

  generateGeminiAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * Gemini CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class GeminiHook {
  constructor() {
    this.toolName = 'gemini';
    this.configPath = path.join(require('os').homedir(), '.gemini', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.gemini', 'extensions');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = GeminiHook;
`;
  }

  generateQwenAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * Qwen CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class QwenHook {
  constructor() {
    this.toolName = 'qwen';
    this.configPath = path.join(require('os').homedir(), '.qwen', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.qwen', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = QwenHook;
`;
  }

  generateCodeBuddyAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * CodeBuddy CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class CodeBuddyHook {
  constructor() {
    this.toolName = 'codebuddy';
    this.configPath = path.join(require('os').homedir(), '.codebuddy', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.codebuddy', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = CodeBuddyHook;
`;
  }

  generateCodexAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * Codex CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class CodexHook {
  constructor() {
    this.toolName = 'codex';
    this.configPath = path.join(require('os').homedir(), '.codex', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.codex', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = CodexHook;
`;
  }

  generateQoderCliAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * QoderCLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class QoderCliHook {
  constructor() {
    this.toolName = 'qodercli';
    this.configPath = path.join(require('os').homedir(), '.qodercli', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.qodercli', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = QoderCliHook;
`;
  }

  generateIFlowAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * IFlow CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class IFlowHook {
  constructor() {
    this.toolName = 'iflow';
    this.configPath = path.join(require('os').homedir(), '.iflow', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.iflow', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = IFlowHook;
`;
  }

  generateCopilotAdapter(projectPath) {
    return `#!/usr/bin/env node
/**
 * Copilot CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class CopilotHook {
  constructor() {
    this.toolName = 'copilot';
    this.configPath = path.join(require('os').homedir(), '.copilot', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.copilot', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = CopilotHook;
`;
  }

  generateGenericAdapter(cliName, projectPath) {
    return `#!/usr/bin/env node
/**
 * ${cliName.charAt(0).toUpperCase() + cliName.slice(1)} CLI Integration Hook
 * Auto-generated by Stigmergy CLI v1.2.1
 * Project: ${projectPath}
 */

const fs = require('fs');
const path = require('path');

class ${cliName.charAt(0).toUpperCase() + cliName.slice(1)}Hook {
  constructor() {
    this.toolName = '${cliName}';
    this.configPath = path.join(require('os').homedir(), '.${cliName}', 'config.json');
    this.hooksDir = path.join(require('os').homedir(), '.${cliName}', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Received cross-CLI prompt: \${prompt}\`);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log(\`[\${this.toolName.toUpperCase()}] Sending cross-CLI response\`);
    return response;
  }
}

module.exports = ${cliName.charAt(0).toUpperCase() + cliName.slice(1)}Hook;
`;
  }

  getFileName(cliName) {
    return `${cliName}_adapter.js`;
  }
}

module.exports = CLIAdapterGenerator;