// ResumeSession Extension Generator
// 专门负责生成各CLI的ResumeSession扩展文件

const path = require("path");

class ResumeSessionGenerator {
  constructor() {
    this.supportedCLIs = [
      "claude",
      "gemini",
      "qwen",
      "codebuddy",
      "codex",
      "iflow",
      "qodercli",
      "copilot",
      "kode",
      "kilocode",
      "opencode",
      "oh-my-opencode",
      "resumesession",
    ];
  }

  generateForCLI(cliName) {
    const needsSlashPrefix = ["claude", "codebuddy"].includes(
      cliName.toLowerCase(),
    );
    const commandName = needsSlashPrefix
      ? "/stigmergy-resume"
      : "stigmergy-resume";
    const currentProjectPath = process.cwd();

    return this.generateExtensionContent(
      cliName,
      commandName,
      currentProjectPath,
    );
  }

  generateExtensionContent(cliName, commandName, projectPath) {
    return `// ${cliName.charAt(0).toUpperCase() + cliName.slice(1)} CLI ResumeSession Integration
// Auto-generated by ResumeSession v1.0.4
// Project: ${projectPath}

const fs = require('fs');
const path = require('path');
const os = require('os');

// Embedded path configuration for CLI session paths
const getAllCLISessionPaths = () => {
  const homeDir = os.homedir();
    return {
      claude: [path.join(homeDir, '.claude', 'projects')],
      gemini: [path.join(homeDir, '.config', 'gemini', 'tmp')],
      qwen: [path.join(homeDir, '.qwen', 'projects')],
      iflow: [path.join(homeDir, '.iflow', 'projects')],
      qodercli: [path.join(homeDir, '.qoder', 'projects')],
      codebuddy: [path.join(homeDir, '.codebuddy')],
      codex: [path.join(homeDir, '.config', 'codex')],
      kode: [path.join(homeDir, '.kode', 'projects')],
      kilocode: [path.join(homeDir, '.kilocode', 'projects')]
    };
};

// Embedded ResumeSession Core Functionality

class SessionScanner {
  scanSessions(cliType, sessionsPath, projectPath) {
    const sessions = [];
    if (!sessionsPath || !projectPath) return sessions;

    try {
      if (!fs.existsSync(sessionsPath)) return sessions;

      // For IFlow, Claude, QoderCLI, Kode: scan projects subdirectories (one level)
      if ((cliType === 'iflow' || cliType === 'claude' || cliType === 'qodercli' || cliType === 'kode') && sessionsPath.includes('projects')) {
        const subdirs = fs.readdirSync(sessionsPath);
        for (const subdir of subdirs) {
          const subdirPath = path.join(sessionsPath, subdir);
          try {
            const stat = fs.statSync(subdirPath);
            if (stat.isDirectory()) {
              sessions.push(...this.scanSessionFiles(cliType, subdirPath, projectPath));
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      // For Gemini: scan tmp/<hash>/chats subdirectories (multiple levels)
      if (cliType === 'gemini' && sessionsPath.includes('tmp')) {
        const hashDirs = fs.readdirSync(sessionsPath);
        for (const hashDir of hashDirs) {
          const hashDirPath = path.join(sessionsPath, hashDir);
          try {
            const stat = fs.statSync(hashDirPath);
            if (stat.isDirectory()) {
              const chatsPath = path.join(hashDirPath, 'chats');
              if (fs.existsSync(chatsPath)) {
                sessions.push(...this.scanSessionFiles(cliType, chatsPath, projectPath));
              }
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      // For Qwen: scan projects/<projectName>/chats subdirectories (two levels)
      if (cliType === 'qwen' && sessionsPath.includes('projects')) {
        const projectDirs = fs.readdirSync(sessionsPath);
        for (const projectDir of projectDirs) {
          const projectDirPath = path.join(sessionsPath, projectDir);
          try {
            const stat = fs.statSync(projectDirPath);
            if (stat.isDirectory()) {
              const chatsPath = path.join(projectDirPath, 'chats');
              if (fs.existsSync(chatsPath)) {
                sessions.push(...this.scanSessionFiles(cliType, chatsPath, projectPath));
              }
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      // For CodeBuddy: scan both projects subdirectories and root history.jsonl
      if (cliType === 'codebuddy') {
        const projectsPath = path.join(sessionsPath, 'projects');
        if (fs.existsSync(projectsPath)) {
          const projectDirs = fs.readdirSync(projectsPath);
          for (const projectDir of projectDirs) {
            const projectDirPath = path.join(projectsPath, projectDir);
            try {
              const stat = fs.statSync(projectDirPath);
              if (stat.isDirectory()) {
                sessions.push(...this.scanSessionFiles(cliType, projectDirPath, projectPath));
              }
            } catch (error) {
              continue;
            }
          }
        }
        sessions.push(...this.scanSessionFiles(cliType, sessionsPath, projectPath));
        return sessions;
      }

      return this.scanSessionFiles(cliType, sessionsPath, projectPath);
    } catch (error) {
      console.warn(\`Warning: Could not scan \${cliType} sessions:\`, error.message);
    }

    return sessions;
  }

  scanSessionFiles(cliType, sessionsPath, projectPath) {
    const sessions = [];
    try {
      const files = fs.readdirSync(sessionsPath);
      for (const file of files) {
        if (file.endsWith('.json') || file.endsWith('.session') || file.endsWith('.jsonl')) {
          try {
            const filePath = path.join(sessionsPath, file);
            let sessionData;

            if (file.endsWith('.jsonl')) {
              const content = fs.readFileSync(filePath, 'utf8');
              const lines = content.trim().split('\\n').filter(line => line.trim());
              const messages = lines.map(line => JSON.parse(line));

              if (messages.length === 0) continue;
              sessionData = this.parseJSONLSession(messages, file);
            } else {
              const content = fs.readFileSync(filePath, 'utf8');
              sessionData = JSON.parse(content);
            }

            if (this.isProjectSession(sessionData, projectPath)) {
              sessions.push({
                cliType,
                sessionId: sessionData.id || sessionData.sessionId || file.replace(/\\.(json|session|jsonl)$/, ''),
                title: sessionData.title || sessionData.topic || 'Untitled',
                content: this.extractContent(sessionData),
                updatedAt: new Date(sessionData.updatedAt || sessionData.timestamp || fs.statSync(filePath).mtime),
                messageCount: sessionData.messageCount || this.countMessages(sessionData),
                projectPath
              });
            }
          } catch (error) {
            console.warn(\`Warning: Could not parse \${file}:\`, error.message);
          }
        }
      }
    } catch (error) {
      console.warn('Warning: Could not scan files:', error.message);
    }

    return sessions;
  }

  parseJSONLSession(messages, filename) {
    const firstMsg = messages[0];
    const lastMsg = messages[messages.length - 1];
    const userMessages = messages.filter(m => m.type === 'user' || m.role === 'user');

    let title = 'Untitled Session';
    if (userMessages.length > 0) {
      const firstUserMsg = userMessages[0];
      let content = firstUserMsg.message?.content || firstUserMsg.content || '';
      if (typeof content === 'object') {
        content = JSON.stringify(content);
      }
      if (typeof content === 'string' && content.trim()) {
        title = content.substring(0, 100) || title;
      }
    }

    const contentParts = messages
      .map(m => {
        if (m.message && typeof m.message === 'object') {
          return m.message.content || m.message.text || '';
        }
        return m.content || m.text || '';
      })
      .filter(text => text && typeof text === 'string' && text.trim());

    return {
      sessionId: firstMsg.sessionId || filename.replace('.jsonl', ''),
      title: title,
      content: contentParts.join(' '),
      timestamp: lastMsg.timestamp || new Date().toISOString(),
      projectPath: firstMsg.cwd || firstMsg.workingDirectory,
      messageCount: messages.filter(m => m.type === 'user' || m.type === 'assistant' || m.role === 'user' || m.role === 'assistant').length,
      messages: messages
    };
  }

  scanAllCLISessions(projectPath) {
    const allSessions = [];
    const cliPathsMap = getAllCLISessionPaths();

    for (const [cliType, sessionsPaths] of Object.entries(cliPathsMap)) {
      for (const sessionsPath of sessionsPaths) {
        const sessions = this.scanSessions(cliType, sessionsPath, projectPath);
        allSessions.push(...sessions);
      }
    }

    return allSessions;
  }

  isProjectSession(session, projectPath) {
    const sessionProject = session.projectPath || session.workingDirectory;
    if (!sessionProject) return true;

    return sessionProject === projectPath ||
           sessionProject.startsWith(projectPath) ||
           projectPath.startsWith(sessionProject);
  }

  extractContent(sessionData) {
    if (sessionData.content && typeof sessionData.content === 'string') {
      return sessionData.content;
    }

    if (sessionData.messages && Array.isArray(sessionData.messages)) {
      return sessionData.messages
        .map(msg => {
          if (msg.message && typeof msg.message === 'object') {
            const content = msg.message.content || msg.message.text || '';
            return this.extractTextFromContent(content);
          }
          const content = msg.content || msg.text || '';
          return this.extractTextFromContent(content);
        })
        .filter(text => text && typeof text === 'string' && text.trim())
        .join(' ');
    }

    if (Array.isArray(sessionData)) {
      return sessionData
        .map(item => {
          if (item.message && typeof item.message === 'object') {
            const content = item.message.content || item.message.text || '';
            return this.extractTextFromContent(content);
          }
          const content = item.content || item.text || '';
          return this.extractTextFromContent(content);
        })
        .filter(text => text && typeof text === 'string' && text.trim())
        .join(' ');
    }

    return '';
  }

  extractTextFromContent(content) {
    if (typeof content === 'string') {
      return content;
    }

    if (Array.isArray(content)) {
      return content
        .map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object') {
            return item.text || item.content || '';
          }
          return '';
        })
        .filter(text => text && typeof text === 'string')
        .join(' ');
    }

    if (content && typeof content === 'object') {
      return content.text || content.content || JSON.stringify(content);
    }

    return '';
  }

  countMessages(sessionData) {
    if (sessionData.messages) {
      return Array.isArray(sessionData.messages) ? sessionData.messages.length : 0;
    }

    if (Array.isArray(sessionData)) {
      return sessionData.length;
    }

    return 0;
  }
}

class SessionFilter {
  filterByCLI(sessions, cliType) {
    if (!cliType) return sessions;
    return sessions.filter(session => session.cliType === cliType);
  }

  filterBySearch(sessions, searchTerm) {
    if (!searchTerm) return sessions;

    const lowerSearch = searchTerm.toLowerCase();
    return sessions.filter(session =>
      session.title.toLowerCase().includes(lowerSearch) ||
      session.content.toLowerCase().includes(lowerSearch)
    );
  }

  filterByDateRange(sessions, timeRange = 'all') {
    if (timeRange === 'all') return sessions;

    const now = new Date();
    return sessions.filter(session => {
      const sessionDate = new Date(session.updatedAt);

      switch (timeRange) {
        case 'today':
          return sessionDate.toDateString() === now.toDateString();
        case 'week': {
          const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
          return sessionDate >= weekAgo;
        }
        case 'month': {
          const monthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
          return sessionDate >= monthAgo;
        }
        default:
          return true;
      }
    });
  }

  sortByDate(sessions) {
    return [...sessions].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
  }

  filterByProject(sessions, projectPath) {
    return sessions.filter(session => session.projectPath === projectPath);
  }

  applyFilters(sessions, options, projectPath) {
    let filteredSessions = [...sessions];

    filteredSessions = this.filterByProject(filteredSessions, projectPath);

    if (options.cli) {
      filteredSessions = this.filterByCLI(filteredSessions, options.cli);
    }

    if (options.search) {
      filteredSessions = this.filterBySearch(filteredSessions, options.search);
    }

    if (options.timeRange) {
      filteredSessions = this.filterByDateRange(filteredSessions, options.timeRange);
    }

    filteredSessions = this.sortByDate(filteredSessions);

    if (options.limit && options.limit > 0) {
      filteredSessions = filteredSessions.slice(0, options.limit);
    }

    return filteredSessions;
  }
}

class HistoryFormatter {
  formatSummary(sessions, context) {
    if (sessions.length === 0) {
      return \`📭 当前项目暂无历史会话\\n\\n💡 **提示:** 尝试: ${commandName} --search <关键词>\`;
    }

    let response = \`📁 **项目历史会话**\\n\\n📊 共找到 \${sessions.length} 个会话\\n\\n\`;

    const byCLI = {};
    sessions.forEach(session => {
      if (!byCLI[session.cliType]) byCLI[session.cliType] = [];
      byCLI[session.cliType].push(session);
    });

    Object.entries(byCLI).forEach(([cli, cliSessions]) => {
      const icon = this.getCLIIcon(cli);
      response += \`\${icon} **\${cli.toUpperCase()}** (\${cliSessions.length}个)\\n\`;

      cliSessions.slice(0, 3).forEach((session, i) => {
        const date = this.formatDate(session.updatedAt);
        const title = session.title.substring(0, 50);
        response += \`   \${i + 1}. \${title}...\\n\`;
        response += \`      📅 \${date} • 💬 \${session.messageCount}条消息\\n\`;
      });

      if (cliSessions.length > 3) {
        response += \`   ... 还有 \${cliSessions.length - 3} 个会话\\n\`;
      }
      response += '\\n';
    });

    response += \`💡 **使用方法:**\\n\`;
    response += \`• '${commandName} --cli <工具>' - 查看特定CLI\\n\`;
    response += \`• '${commandName} --search <关键词>' - 搜索内容\\n\`;
    response += \`• '${commandName} --format timeline' - 时间线视图\`;

    return response;
  }

  getCLIIcon(cliType) {
    const icons = {
      'claude': '🟢',
      'gemini': '🔵',
      'qwen': '🟡',
      'iflow': '🔴',
      'codebuddy': '🟣',
      'codex': '🟪',
      'qodercli': '🟠',
      'kode': '⚡'
    };
    return icons[cliType] || '🔹';
  }

  formatDate(date) {
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (24 * 60 * 60 * 1000));

    if (days === 0) {
      return date.toLocaleTimeString();
    } else if (days === 1) {
      return '昨天';
    } else if (days < 7) {
      return \`\${days}天前\`;
    } else if (days < 30) {
      return \`\${Math.floor(days / 7)}周前\`;
    } else {
      return \`\${Math.floor(days / 30)}个月前\`;
    }
  }
}

class HistoryQuery {
  constructor() {
    this.scanner = new SessionScanner();
    this.filter = new SessionFilter();
    this.formatter = new HistoryFormatter();
  }

  queryHistory(options, projectPath) {
    try {
      const allSessions = this.scanner.scanAllCLISessions(projectPath);
      const filteredSessions = this.filter.applyFilters(allSessions, options, projectPath);

      const response = this.formatter.formatSummary(filteredSessions);
      const suggestions = this.generateSuggestions(filteredSessions, options);

      return {
        response,
        suggestions
      };
    } catch (error) {
      return {
        response: \`❌ 历史查询失败: \${error.message}\`,
        suggestions: ['${commandName} --help']
      };
    }
  }

  generateSuggestions(sessions, query) {
    const suggestions = [];

    if (sessions.length > 0) {
      suggestions.push(\`${commandName} --format timeline\`);

      if (sessions[0]?.cliType) {
        suggestions.push(\`${commandName} --cli \${sessions[0].cliType}\`);
      }
    }

    suggestions.push(\`${commandName} --search "react"\`);
    suggestions.push(\`${commandName} --today\`);

    return suggestions.slice(0, 5);
  }
}

/**
 * 处理 ${commandName} 命令
 */
async function handleHistoryCommand(input, context) {
  try {
    console.log('🔍 Searching cross-CLI history...');

    const query = buildQuery(input);
    const historyQuery = new HistoryQuery();
    const result = historyQuery.queryHistory(query, '${projectPath}');

    return {
      response: result.response,
      suggestions: result.suggestions
    };
  } catch (error) {
    console.error('History command error:', error);
    return {
      response: \`❌ 历史查询失败: \${error.message}\`,
      suggestions: ['${commandName} --help']
    };
  }
}

/**
 * 构建查询参数
 */
function buildQuery(input) {
  const options = {
    limit: 10,
    format: 'summary',
    timeRange: 'all',
    cli: null,
    search: null
  };

  const cleanInput = input.replace(new RegExp('^\\\\\\\\/?' + '${commandName}' + '\\\\\\s*', 'i'), '').trim();
  const parts = cleanInput.split(/\\\\s+/).filter(p => p.length > 0);

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].toLowerCase();

    if (part === '--cli' && i + 1 < parts.length) {
      options.cli = parts[++i];
    } else if (part === '--search' && i + 1 < parts.length) {
      options.search = parts[++i];
    } else if (part === '--limit' && i + 1 < parts.length) {
      options.limit = parseInt(parts[++i]);
    } else if (part === '--format' && i + 1 < parts.length) {
      const format = parts[++i]?.toLowerCase();
      if (['summary', 'timeline', 'detailed', 'context'].includes(format)) {
        options.format = format;
      }
    } else if (part === '--today') {
      options.timeRange = 'today';
    } else if (part === '--week') {
      options.timeRange = 'week';
    } else if (part === '--month') {
      options.timeRange = 'month';
    } else if (!part.startsWith('--') && !options.search) {
      options.search = part;
    }
  }

  return options;
}

// CLI-specific registration logic

${this.generateCLIRegistrationCode(cliName, commandName, projectPath)}
`;
  }

  generateCLIRegistrationCode(cliName, commandName, projectPath) {
    switch (cliName.toLowerCase()) {
      case "claude":
      case "codebuddy":
        return `
// ${cliName.charAt(0).toUpperCase() + cliName.slice(1)} CLI integration

// Command name constant
const commandName = '${commandName}';

// Main command handler
function handleHistoryCommand(input) {
  if (!input || typeof input !== 'string') {
    return {
      response: 'Usage: ' + commandName + ' [options]\\n' +
                'Options:\\n' +
                '  --cli <name>     Filter by CLI (claude, gemini, qwen, etc.)\\n' +
                '  --search <term>  Search in session content\\n' +
                '  --limit <num>    Maximum sessions to show (default: 10)\\n' +
                '  --format <type>  Output format: summary, detailed, json (default: summary)\\n' +
                '  --time <range>   Time range: today, week, month, all (default: all)',
      suggestions: []
    };
  }

  try {
    const options = parseCommandOptions(input);
    const historyQuery = new HistoryQuery();
    const result = historyQuery.queryHistory(options, projectPath);
    
    return {
      response: result.response,
      suggestions: result.suggestions || []
    };
  } catch (error) {
    return {
      response: 'Error: ' + error.message,
      suggestions: []
    };
  }
}

// Parse command options
function parseCommandOptions(input) {
  const options = {
    limit: 10,
    format: 'summary',
    timeRange: 'all',
    cli: null,
    search: null
  };

  const cleanInput = input.replace(new RegExp('^\\\\/?' + commandName + '\\\\\s*', 'i'), '').trim();
  const parts = cleanInput.split(/\\\s+/).filter(p => p.length > 0);

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].toLowerCase();
    if (part === '--cli' && i + 1 < parts.length) {
      options.cli = parts[++i];
    } else if (part === '--search' && i + 1 < parts.length) {
      options.search = parts[++i];
    } else if (part === '--limit' && i + 1 < parts.length) {
      options.limit = parseInt(parts[++i]);
    } else if (part === '--format' && i + 1 < parts.length) {
      options.format = parts[++i];
    } else if (part === '--time' && i + 1 < parts.length) {
      options.timeRange = parts[++i];
    } else if (!part.startsWith('--') && !options.search) {
      options.search = part;
    }
  }

  return options;
}

// Register command
if (typeof ${cliName} !== 'undefined') {
  ${cliName}.addCommand('${commandName}', handleHistoryCommand);
}

// 导出处理器
module.exports = {
  handleHistoryCommand,
  parseCommandOptions
};`;

      case "gemini":
        return `
class GeminiHistoryHandler {
  constructor() {
    this.commandName = '${commandName}';
  }

  async handleCommand(input, session) {
    if (!input.startsWith('${commandName}')) return null;

    try {
      const options = this.buildQuery(input);
      const historyQuery = new HistoryQuery();
      const result = historyQuery.queryHistory(options, '${projectPath}');

      return {
        text: result.response,
        continue: true,
        suggestions: result.suggestions
      };
    } catch (error) {
      return {
        text: \`History command failed: \${error.message}\`,
        continue: true,
        suggestions: []
      };
    }
  }

  buildQuery(input) {
    const options = {
      limit: 10,
      format: 'summary',
      timeRange: 'all',
      cli: null,
      search: null
    };

    const cleanInput = input.replace(new RegExp('^\\\\/?' + this.commandName + '\\\\\s*', 'i'), '').trim();
    const parts = cleanInput.split(/\\\s+/).filter(p => p.length > 0);

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i].toLowerCase();
      if (part === '--cli' && i + 1 < parts.length) {
        options.cli = parts[++i];
      } else if (part === '--search' && i + 1 < parts.length) {
        options.search = parts[++i];
      } else if (part === '--limit' && i + 1 < parts.length) {
        options.limit = parseInt(parts[++i]);
      } else if (part === '--format' && i + 1 < parts.length) {
        options.format = parts[++i];
      } else if (part === '--time' && i + 1 < parts.length) {
        options.timeRange = parts[++i];
      } else if (!part.startsWith('--') && !options.search) {
        options.search = part;
      }
    }

    return options;
  }
}

// 注册处理器
const handler = new GeminiHistoryHandler();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { GeminiHistoryHandler, handler };
}

if (typeof geminiCLI !== 'undefined') {
  const cmdName = '${commandName}'.replace(/^\\\//, '');
  geminiCLI.addCommandHandler(cmdName, handler.handleCommand.bind(handler));
}`;

      case "qwen":
      case "qodercli":
      case "kode":
      case "kilocode":
        return `
// ${cliName.charAt(0).toUpperCase() + cliName.slice(1)} CLI integration

// Command name constant
const commandName = '${commandName}';

// Main command handler
function handleHistoryCommand(input) {
  if (!input || typeof input !== 'string') {
    return {
      response: 'Usage: ' + commandName + ' [options]\\n' +
                'Options:\\n' +
                '  --cli <name>     Filter by CLI (claude, gemini, qwen, etc.)\\n' +
                '  --search <term>  Search in session content\\n' +
                '  --limit <num>    Maximum sessions to show (default: 10)\\n' +
                '  --format <type>  Output format: summary, detailed, json (default: summary)\\n' +
                '  --time <range>   Time range: today, week, month, all (default: all)',
      suggestions: []
    };
  }

  try {
    const options = parseCommandOptions(input);
    const historyQuery = new HistoryQuery();
    const result = historyQuery.queryHistory(options, projectPath);
    
    return {
      response: result.response,
      suggestions: result.suggestions || []
    };
  } catch (error) {
    return {
      response: 'Error: ' + error.message,
      suggestions: []
    };
  }
}

// Parse command options
function parseCommandOptions(input) {
  const options = {
    limit: 10,
    format: 'summary',
    timeRange: 'all',
    cli: null,
    search: null
  };

  const cleanInput = input.replace(new RegExp('^\\\\/?' + commandName + '\\\\\s*', 'i'), '').trim();
  const parts = cleanInput.split(/\\\s+/).filter(p => p.length > 0);

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].toLowerCase();
    if (part === '--cli' && i + 1 < parts.length) {
      options.cli = parts[++i];
    } else if (part === '--search' && i + 1 < parts.length) {
      options.search = parts[++i];
    } else if (part === '--limit' && i + 1 < parts.length) {
      options.limit = parseInt(parts[++i]);
    } else if (part === '--format' && i + 1 < parts.length) {
      options.format = parts[++i];
    } else if (part === '--time' && i + 1 < parts.length) {
      options.timeRange = parts[++i];
    } else if (!part.startsWith('--') && !options.search) {
      options.search = part;
    }
  }

  return options;
}

// Register extension
if (typeof ${cliName} !== 'undefined' && ${cliName}.addExtension) {
  ${cliName}.addExtension('history', handleHistoryCommand);
}

// 导出处理器
module.exports = {
  handleHistoryCommand,
  parseCommandOptions
};`;

      default:
        return `
// ${cliName.charAt(0).toUpperCase() + cliName.slice(1)} CLI integration
// Generic registration - may need customization for specific CLI

// Command name constant
const commandName = '${commandName}';

// Main command handler
function handleHistoryCommand(input) {
  if (!input || typeof input !== 'string') {
    return {
      response: 'Usage: ' + commandName + ' [options]\\n' +
                'Options:\\n' +
                '  --cli <name>     Filter by CLI (claude, gemini, qwen, etc.)\\n' +
                '  --search <term>  Search in session content\\n' +
                '  --limit <num>    Maximum sessions to show (default: 10)\\n' +
                '  --format <type>  Output format: summary, detailed, json (default: summary)\\n' +
                '  --time <range>   Time range: today, week, month, all (default: all)',
      suggestions: []
    };
  }

  try {
    const options = parseCommandOptions(input);
    const historyQuery = new HistoryQuery();
    const result = historyQuery.queryHistory(options, projectPath);
    
    return {
      response: result.response,
      suggestions: result.suggestions || []
    };
  } catch (error) {
    return {
      response: 'Error: ' + error.message,
      suggestions: []
    };
  }
}

// Parse command options
function parseCommandOptions(input) {
  const options = {
    limit: 10,
    format: 'summary',
    timeRange: 'all',
    cli: null,
    search: null
  };

  const cleanInput = input.replace(new RegExp('^\\\\/?' + commandName + '\\\\\s*', 'i'), '').trim();
  const parts = cleanInput.split(/\\\s+/).filter(p => p.length > 0);

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].toLowerCase();
    if (part === '--cli' && i + 1 < parts.length) {
      options.cli = parts[++i];
    } else if (part === '--search' && i + 1 < parts.length) {
      options.search = parts[++i];
    } else if (part === '--limit' && i + 1 < parts.length) {
      options.limit = parseInt(parts[++i]);
    } else if (part === '--format' && i + 1 < parts.length) {
      options.format = parts[++i];
    } else if (part === '--time' && i + 1 < parts.length) {
      options.timeRange = parts[++i];
    } else if (!part.startsWith('--') && !options.search) {
      options.search = part;
    }
  }

  return options;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    handleHistoryCommand,
    parseCommandOptions
  };
}`;

      case "opencode":
        return `
// OpenCode CLI ResumeSession Integration
// 专门为 OpenCode 实现的会话恢复功能

const fs = require('fs');
const path = require('path');
const os = require('os');

class OpenCodeResumeSession {
  constructor() {
    this.homeDir = os.homedir();
    this.opencodeConfigPath = path.join(this.homeDir, '.opencode');
    this.sessionStoragePath = path.join(this.opencodeConfigPath, 'sessions');
  }

  getProjectPathHash(projectPath) {
    return projectPath
      .replace(/^([A-Za-z]):\\\\/, '$1--')
      .replace(/\\\\/g, '-')
      .replace(/\//g, '-');
  }

  findOpenCodeSessions(projectPath) {
    const sessions = [];

    if (!fs.existsSync(this.sessionStoragePath)) {
      return sessions;
    }

    try {
      const projectHash = this.getProjectPathHash(projectPath);
      const projectSessionPath = path.join(this.sessionStoragePath, projectHash);

      if (!fs.existsSync(projectSessionPath)) {
        return sessions;
      }

      const files = fs.readdirSync(projectSessionPath);
      
      for (const file of files) {
        if (file.endsWith('.json') || file.endsWith('.jsonl')) {
          const filePath = path.join(projectSessionPath, file);
          try {
            const stats = fs.statSync(filePath);
            sessions.push({
              id: file.replace(/\\.(json|jsonl)$/, ''),
              file: file,
              path: filePath,
              modified: stats.mtime,
              size: stats.size
            });
          } catch (error) {
            continue;
          }
        }
      }

      sessions.sort((a, b) => b.modified - a.modified);

    } catch (error) {
      console.error('Error finding OpenCode sessions:', error.message);
    }

    return sessions;
  }

  readSession(sessionPath) {
    try {
      const content = fs.readFileSync(sessionPath, 'utf8');
      
      if (sessionPath.endsWith('.jsonl')) {
        const lines = content.trim().split('\\n').filter(line => line.trim());
        return lines.map(line => {
          try {
            return JSON.parse(line);
          } catch (e) {
            return null;
          }
        }).filter(msg => msg !== null);
      } else {
        return JSON.parse(content);
      }
    } catch (error) {
      console.error('Error reading session:', error.message);
      return null;
    }
  }

  formatSession(session, options = {}) {
    const { format = 'summary', limit = 5 } = options;
    const messages = this.readSession(session.path);

    if (!messages || messages.length === 0) {
      return '📭 会话为空或无法读取';
    }

    const messageList = Array.isArray(messages) ? messages : 
                       (messages.messages && Array.isArray(messages.messages)) ? messages.messages : [];

    if (messageList.length === 0) {
      return '📭 会话没有消息';
    }

    const output = [];

    if (format === 'summary') {
      output.push('📋 OpenCode 会话摘要');
      output.push('');
      output.push('🆔 会话 ID: ' + session.id);
      output.push('📅 最后修改: ' + session.modified.toLocaleString());
      output.push('📝 消息数量: ' + messageList.length);
      output.push('');
      
      const recentMessages = messageList.slice(-limit);
      output.push('最近消息:');
      recentMessages.forEach((msg, index) => {
        const role = msg.type || msg.role || 'unknown';
        const prefix = role === 'user' ? '👤' : '🤖';
        const content = this.extractContent(msg);
        const preview = content ? content.substring(0, 100) + (content.length > 100 ? '...' : '') : '(无内容)';
        output.push('  ' + prefix + ' ' + preview);
      });

    } else if (format === 'detailed') {
      output.push('📋 OpenCode 完整会话');
      output.push('');
      output.push('🆔 会话 ID: ' + session.id);
      output.push('📅 最后修改: ' + session.modified.toLocaleString());
      output.push('📁 文件: ' + session.file);
      output.push('');
      output.push('---');
      output.push('');
      output.push('📝 完整对话内容:');
      output.push('');

      messageList.forEach((msg, index) => {
        const role = msg.type || msg.role || 'unknown';
        const prefix = role === 'user' ? '👤 用户' : '🤖 助手';
        const content = this.extractContent(msg);

        if (content && content.trim()) {
          output.push(prefix + ':');
          output.push(content);
          output.push('');
        }
      });
    }

    return output.join('\\n');
  }

  extractContent(msg) {
    if (msg.message && typeof msg.message === 'object') {
      const content = msg.message.content || msg.message.text || '';
      return this.extractTextFromContent(content);
    }

    const content = msg.content || msg.text || '';
    return this.extractTextFromContent(content);
  }

  extractTextFromContent(content) {
    if (typeof content === 'string') {
      return content;
    }

    if (Array.isArray(content)) {
      return content
        .map(item => {
          if (typeof item === 'string') return item;
          if (item && typeof item === 'object') {
            return item.text || item.content || '';
          }
          return '';
        })
        .filter(text => text && typeof text === 'string')
        .join(' ');
    }

    if (content && typeof content === 'object') {
      return content.text || content.content || '';
    }

    return '';
  }

  execute(options = {}) {
    const { format = 'summary', sessionId = null, limit = 5 } = options;
    const projectPath = process.cwd();
    const sessions = this.findOpenCodeSessions(projectPath);

    if (sessions.length === 0) {
      return '📭 未找到 OpenCode 会话\\n💡 项目路径: ' + projectPath;
    }

    if (sessionId) {
      const session = sessions.find(s => s.id === sessionId);
      if (!session) {
        return '❌ 未找到会话 ID: ' + sessionId + '\\n💡 可用会话: ' + sessions.map(s => s.id).join(', ');
      }
      return this.formatSession(session, { format, limit });
    } else {
      const latestSession = sessions[0];
      let result = this.formatSession(latestSession, { format, limit });

      if (sessions.length > 1) {
        result += '\\n\\n💡 还有 ' + (sessions.length - 1) + ' 个其他会话可用';
        result += '\\n💡 使用 --session <id> 查看其他会话';
      }

      return result;
    }
  }

  listSessions() {
    const projectPath = process.cwd();
    const sessions = this.findOpenCodeSessions(projectPath);

    if (sessions.length === 0) {
      return '📭 未找到 OpenCode 会话';
    }

    let output = '📋 OpenCode 会话列表\\n\\n';
    output += '📊 共找到 ' + sessions.length + ' 个会话\\n\\n';

    sessions.forEach((session, index) => {
      output += (index + 1) + '. ' + session.id + '\\n';
      output += '   📅 ' + session.modified.toLocaleString() + '\\n';
      output += '   📁 ' + session.file + '\\n\\n';
    });

    return output;
  }
}

// Main handler
function handleHistoryCommand(input) {
  if (!input || typeof input !== 'string') {
    return {
      response: 'Usage: ' + commandName + ' [options]\\n' +
                'Options:\\n' +
                '  --detailed, -d  显示详细输出\\n' +
                '  --list, -l     列出所有会话\\n' +
                '  --session, -s <id>  指定会话ID\\n' +
                '  --limit <num>  显示消息数量（默认: 5）',
      suggestions: []
    };
  }

  try {
    const resumeSession = new OpenCodeResumeSession();
    const options = {
      format: 'summary',
      sessionId: null,
      limit: 5
    };

    const parts = input.trim().split(/\\s+/);
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      if (part === '--detailed' || part === '-d') {
        options.format = 'detailed';
      } else if (part === '--list' || part === '-l') {
        return {
          response: resumeSession.listSessions(),
          suggestions: []
        };
      } else if ((part === '--session' || part === '-s') && i + 1 < parts.length) {
        options.sessionId = parts[++i];
      } else if (part === '--limit' && i + 1 < parts.length) {
        options.limit = parseInt(parts[++i]);
      } else if (!part.startsWith('--')) {
        options.sessionId = part;
      }
    }

    return {
      response: resumeSession.execute(options),
      suggestions: []
    };
  } catch (error) {
    return {
      response: 'Error: ' + error.message,
      suggestions: []
    };
  }
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    handleHistoryCommand,
    OpenCodeResumeSession
  };
}`;
    }
  }

  getFileName(cliName) {
    switch (cliName.toLowerCase()) {
      case "claude":
      case "gemini":
      case "qwen":
      case "codebuddy":
      case "codex":
      case "kode":
      case "resumesession":
        return "resumesession-history.js";
      case "qodercli":
        return "history.js";
      case "opencode":
        return "opencode-resume.js";
      default:
        return "resumesession-history.js";
    }
  }
}

module.exports = ResumeSessionGenerator;
