#!/bin/bash
#
# Stigmergy Usage Examples
# 使用示例脚本
#
# 用途: 演示如何使用配置好的 Stigmergy 增强功能
#

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Stigmergy 使用示例${NC}"
echo "======================================"
echo ""

# 1. 搜索引擎使用示例
echo -e "${GREEN}1. 搜索引擎使用示例${NC}"
echo "--------------------------------------"
echo ""
echo "在 Claude CLI 中："
echo ""
echo "  # 基础搜索"
echo "  claude '搜索 latest artificial intelligence news'"
echo ""
echo "  # 学术搜索"
echo "  claude '搜索 machine learning transformers paper 2024'"
echo ""
echo "  # 技术问题"
echo "  claude '搜索 how to install Ollama on Ubuntu'"
echo ""
echo "  # 实时信息"
echo "  claude '搜索 Bitcoin price today'"
echo ""

# 2. 本地 LLM 使用示例
echo -e "${GREEN}2. 本地 LLM 使用示例${NC}"
echo "--------------------------------------"
echo ""
echo "命令行直接使用："
echo ""
echo "  # 使用 Llama 3"
echo "  ollama run llama3:8b '解释一下量子计算'"
echo ""
echo "  # 使用 Qwen（中文）"
echo "  ollama run qwen2.5:7b '写一首关于AI的诗'"
echo ""
echo "  # 交互式对话"
echo "  ollama run llama3:8b"
echo ""
echo "在 Claude CLI 中结合使用："
echo ""
echo "  # 让 Claude 使用本地模型"
echo "  claude '使用本地的 llama3 模型帮我分析这段代码的性能'"
echo ""
echo "  # 混合使用（Claude + 本地LLM）"
echo "  claude '先用本地模型快速分析，然后你给出详细建议'"
echo ""

# 3. API 调用示例
echo -e "${GREEN}3. API 调用示例${NC}"
echo "--------------------------------------"
echo ""
echo "使用 curl 调用 Ollama API："
echo ""
echo "  # 生成文本"
echo "  curl http://localhost:11434/api/generate -d '{"
echo "    \"model\": \"llama3:8b\","
echo "    \"prompt\": \"Why is the sky blue?\""
echo "  }'"
echo ""
echo "  # 对话"
echo "  curl http://localhost:11434/api/chat -d '{"
echo "    \"model\": \"llama3:8b\","
echo "    \"messages\": [{\"role\": \"user\", \"content\": \"Hello\"}]"
echo "  }'"
echo ""

# 4. 组合使用示例
echo -e "${GREEN}4. 组合使用示例${NC}"
echo "--------------------------------------"
echo ""
echo "搜索 + 本地 LLM："
echo ""
echo "  # 1. 搜索信息"
echo "  claude '搜索 Docker 最佳实践 2024'"
echo ""
echo "  # 2. 使用本地模型深入分析"
echo "  ollama run llama3:8b '总结 Docker 容器化的5个关键点'"
echo ""
echo "  # 3. 让 Claude 整合结果"
echo "  claude '结合搜索结果和本地模型的分析，给出 Docker 最佳实践建议'"
echo ""

# 5. 编程任务示例
echo -e "${GREEN}5. 编程任务示例${NC}"
echo "--------------------------------------"
echo ""
echo "代码分析："
echo "  claude '使用本地模型快速分析当前目录的代码结构'"
echo ""
echo "调试："
echo "  claude '搜索这个错误信息的解决方案，然后用本地模型分析我的代码'"
echo ""
echo "重构："
echo "  claude '搜索 React 性能优化最佳实践，帮我重构这段代码'"
echo ""

# 6. 实用工作流
echo -e "${GREEN}6. 实用工作流${NC}"
echo "--------------------------------------"
echo ""
echo "学习新技术："
echo "  # 1. 搜索资料"
echo "  claude '搜索 Rust 编程语言教程'"
echo ""
echo "  # 2. 本地模型练习"
echo "  ollama run llama3:8b '用 Rust 写一个 Hello World'"
echo ""
echo "  # 3. Claude 评审"
echo "  claude '评审这段 Rust 代码，给出改进建议'"
echo ""
echo "研究项目："
echo "  # 1. 搜索相关论文"
echo "  claude '搜索 reinforcement learning survey 2024'"
echo ""
echo "  # 2. 本地模型总结"
echo "  ollama run llama3:8b '总结强化学习的3个核心概念'"
echo ""
echo "  # 3. 深入分析"
echo "  claude '基于搜索和总结，设计一个强化学习项目'"
echo ""

# 7. 配置文件查看
echo -e "${GREEN}7. 查看配置${NC}"
echo "--------------------------------------"
echo ""
echo "# 查看搜索配置"
echo "cat ~/.stigmergy/config/search-services.json"
echo ""
echo "# 查看本地 LLM 配置"
echo "cat ~/.stigmergy/config/local-llm.json"
echo ""
echo "# 列出已安装的模型"
echo "ollama list"
echo ""

# 8. 故障排除
echo -e "${GREEN}8. 故障排除${NC}"
echo "--------------------------------------"
echo ""
echo "# 验证配置"
echo "bash ~/.stigmergy/scripts/verify-config.sh"
echo ""
echo "# 重启 Ollama 服务"
echo "pkill ollama && ollama serve &"
echo ""
echo "# 测试搜索"
echo "curl 'https://api.duckduckgo.com/?q=test&format=json'"
echo ""
echo "# 测试 Ollama"
echo "curl http://localhost:11434/api/tags"
echo ""

# 9. 性能优化提示
echo -e "${GREEN}9. 性能优化提示${NC}"
echo "--------------------------------------"
echo ""
echo "选择合适的模型："
echo "  - phi3: 轻量快速（2.3GB）"
echo "  - llama3:8b: 平衡性能（4.7GB）"
echo "  - qwen2.5:7b: 中文优化（4.5GB）"
echo ""
echo "使用场景："
echo "  - 快速查询 → phi3"
echo "  - 复杂推理 → llama3:8b"
echo "  - 中文任务 → qwen2.5:7b"
echo ""
echo "资源管理："
echo "  - 卸载不用的模型: ollama rm <model>"
echo "  - 查看模型大小: ollama list"
echo "  - 监控资源: top 或 htop"
echo ""

# 10. 下一步
echo -e "${GREEN}10. 下一步${NC}"
echo "--------------------------------------"
echo ""
echo "1. 运行配置验证："
echo "   bash ~/.stigmergy/scripts/verify-config.sh"
echo ""
echo "2. 阅读实用指南："
echo "   cat ~/.stigmergy/docs/realistic-soul-proposal.md"
echo ""
echo "3. 开始使用："
echo "   claude '搜索 today AI news'"
echo "   ollama run llama3:8b '你好'"
echo ""
echo "4. 探索更多："
echo "   - Stigmergy GitHub: https://github.com/ptreezh/stigmergy-CLI-Multi-Agents"
echo "   - Ollama 文档: https://ollama.com/documentation"
echo "   - Claude CLI: https://claude.ai/code"
echo ""

echo -e "${BLUE}======================================${NC}"
echo "开始探索吧！🚀"
