# PowerShell script for smart Git commits following DNASPEC rules
# This script helps create commits with proper AI attribution and formatting

param(
    [Parameter(Mandatory=$true)]
    [string]$Message,

    [string]$Type = "feat",
    [string]$Scope = "",
    [string]$AIModel = "Claude 3.5 Sonnet",
    [string]$GeneratedBy = "iFlow CLI",
    [string]$ReviewedBy = "",
    [string]$Status = "draft",
    [switch]$NoVerify = $false
)

Write-Host "🤖 Smart Commit with DNASPEC Rules" -ForegroundColor Cyan

# Validate commit type
$validTypes = @("feat", "fix", "docs", "style", "refactor", "test", "chore", "ci", "perf", "revert")
if ($validTypes -notcontains $Type) {
    Write-Host "❌ ERROR: Invalid commit type '$Type'" -ForegroundColor Red
    Write-Host "   Valid types: $($validTypes -join ', ')" -ForegroundColor Yellow
    exit 1
}

# Validate status
$validStatuses = @("draft", "reviewed", "approved")
if ($validStatuses -notcontains $Status) {
    Write-Host "❌ ERROR: Invalid status '$Status'" -ForegroundColor Red
    Write-Host "   Valid statuses: $($validStatuses -join ', ')" -ForegroundColor Yellow
    exit 1
}

# Check if there are staged changes
$stagedFiles = git diff --cached --name-only
if (-not $stagedFiles) {
    Write-Host "⚠️  WARNING: No staged files detected" -ForegroundColor Yellow
    Write-Host "   Please stage files first using: git add <files>" -ForegroundColor Yellow
    exit 1
}

Write-Host "📋 Staged files:" -ForegroundColor Cyan
$stagedFiles | ForEach-Object { Write-Host "   - $_" -ForegroundColor White }

# Build commit message
$commitMessage = ""

# Subject line
if ($Scope) {
    $commitMessage = "$Type($Scope): $Message [AI-Generated]"
} else {
    $commitMessage = "$Type: $Message [AI-Generated]"
}

# Body
$commitMessage += "`n`n"
$commitMessage += "AI-assisted commit following DNASPEC rules.`n`n"
$commitMessage += "- AI Model: $AIModel`n"
$commitMessage += "- Generated by: $GeneratedBy`n"

if ($ReviewedBy) {
    $commitMessage += "- Reviewed by: $ReviewedBy`n"
} else {
    $commitMessage += "- Reviewed by: [PENDING]`n"
}

$commitMessage += "- Status: $Status`n"

# Add file statistics
$commitMessage += "`n📊 Files changed:`n"
$stats = git diff --cached --stat
$stats | ForEach-Object {
    if ($_ -match "^\s*(.+?)\s+\|") {
        $commitMessage += "   - $($matches[1])`n"
    }
}

# Display commit message
Write-Host ""
Write-Host "📝 Commit message preview:" -ForegroundColor Cyan
Write-Host ""
Write-Host $commitMessage -ForegroundColor White
Write-Host ""

# Confirm before committing
$confirm = Read-Host "Proceed with commit? (y/N)"
if ($confirm -ne "y" -and $confirm -ne "Y") {
    Write-Host "❌ Commit cancelled" -ForegroundColor Red
    exit 0
}

# Create commit
$gitArgs = @("commit", "-m", $commitMessage)
if ($NoVerify) {
    $gitArgs += "--no-verify"
}

Write-Host "🚀 Creating commit..." -ForegroundColor Green
& git @gitArgs

if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Commit created successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "💡 Next steps:" -ForegroundColor Cyan
    Write-Host "   - Review the commit: git show HEAD" -ForegroundColor White
    Write-Host "   - Push to remote: git push" -ForegroundColor White
    Write-Host "   - Update status when reviewed: git commit --amend" -ForegroundColor White
} else {
    Write-Host "❌ Commit failed" -ForegroundColor Red
    exit 1
}