#!/bin/bash
# Bash script for smart Git commits following DNASPEC rules
# This script helps create commits with proper AI attribution and formatting

MESSAGE=""
TYPE="feat"
SCOPE=""
AI_MODEL="Claude 3.5 Sonnet"
GENERATED_BY="iFlow CLI"
REVIEWED_BY=""
STATUS="draft"
NO_VERIFY=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -m|--message)
            MESSAGE="$2"
            shift 2
            ;;
        -t|--type)
            TYPE="$2"
            shift 2
            ;;
        -s|--scope)
            SCOPE="$2"
            shift 2
            ;;
        -a|--ai-model)
            AI_MODEL="$2"
            shift 2
            ;;
        -g|--generated-by)
            GENERATED_BY="$2"
            shift 2
            ;;
        -r|--reviewed-by)
            REVIEWED_BY="$2"
            shift 2
            ;;
        -S|--status)
            STATUS="$2"
            shift 2
            ;;
        --no-verify)
            NO_VERIFY=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate message
if [ -z "$MESSAGE" ]; then
    echo "❌ ERROR: Message is required"
    echo "Usage: ./smart-commit.sh -m 'commit message' [options]"
    exit 1
fi

# Validate commit type
VALID_TYPES=("feat" "fix" "docs" "style" "refactor" "test" "chore" "ci" "perf" "revert")
if [[ ! " ${VALID_TYPES[@]} " =~ " ${TYPE} " ]]; then
    echo "❌ ERROR: Invalid commit type '$TYPE'"
    echo "   Valid types: ${VALID_TYPES[*]}"
    exit 1
fi

# Validate status
VALID_STATUSES=("draft" "reviewed" "approved")
if [[ ! " ${VALID_STATUSES[@]} " =~ " ${STATUS} " ]]; then
    echo "❌ ERROR: Invalid status '$STATUS'"
    echo "   Valid statuses: ${VALID_STATUSES[*]}"
    exit 1
fi

echo "🤖 Smart Commit with DNASPEC Rules"

# Check if there are staged changes
STAGED_FILES=$(git diff --cached --name-only)
if [ -z "$STAGED_FILES" ]; then
    echo "⚠️  WARNING: No staged files detected"
    echo "   Please stage files first using: git add <files>"
    exit 1
fi

echo "📋 Staged files:"
echo "$STAGED_FILES" | while read -r file; do
    echo "   - $file"
done

# Build commit message
COMMIT_MESSAGE=""

# Subject line
if [ -n "$SCOPE" ]; then
    COMMIT_MESSAGE="$TYPE($SCOPE): $MESSAGE [AI-Generated]"
else
    COMMIT_MESSAGE="$TYPE: $MESSAGE [AI-Generated]"
fi

# Body
COMMIT_MESSAGE+=$'\n\n'
COMMIT_MESSAGE+="AI-assisted commit following DNASPEC rules."
COMMIT_MESSAGE+=$'\n\n'
COMMIT_MESSAGE+="- AI Model: $AI_MODEL"$'\n'
COMMIT_MESSAGE+="- Generated by: $GENERATED_BY"$'\n'

if [ -n "$REVIEWED_BY" ]; then
    COMMIT_MESSAGE+="- Reviewed by: $REVIEWED_BY"$'\n'
else
    COMMIT_MESSAGE+="- Reviewed by: [PENDING]"$'\n'
fi

COMMIT_MESSAGE+="- Status: $STATUS"$'\n'

# Add file statistics
COMMIT_MESSAGE+=$'\n'
COMMIT_MESSAGE+="📊 Files changed:"$'\n'
git diff --cached --stat | while read -r line; do
    if [[ "$line" =~ ^[[:space:]]*(.+?)[[:space:]]+\| ]]; then
        COMMIT_MESSAGE+="   - ${BASH_REMATCH[1]}"$'\n'
    fi
done

# Display commit message
echo ""
echo "📝 Commit message preview:"
echo ""
echo "$COMMIT_MESSAGE"
echo ""

# Confirm before committing
read -p "Proceed with commit? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Commit cancelled"
    exit 0
fi

# Create commit
GIT_ARGS=("commit" "-m" "$COMMIT_MESSAGE")
if [ "$NO_VERIFY" = true ]; then
    GIT_ARGS+=("--no-verify")
fi

echo "🚀 Creating commit..."
git "${GIT_ARGS[@]}"

if [ $? -eq 0 ]; then
    echo "✅ Commit created successfully!"
    echo ""
    echo "💡 Next steps:"
    echo "   - Review the commit: git show HEAD"
    echo "   - Push to remote: git push"
    echo "   - Update status when reviewed: git commit --amend"
else
    echo "❌ Commit failed"
    exit 1
fi