// IFlow CLI ResumeSession Integration
// Auto-generated by ResumeSession v1.0.4
// Project: D:\stigmergy-CLI-Multi-Agents

const fs = require('fs');
const path = require('path');
const os = require('os');

// Load shared path configuration
const pathConfigLoader = require(path.join(__dirname, 'path-config-loader.js'));

class SessionScanner {
  scanSessions(cliType, sessionsPath, projectPath) {
    const sessions = [];
    if (!sessionsPath || !projectPath) return sessions;

    try {
      if (!fs.existsSync(sessionsPath)) return sessions;

      // For IFlow: scan projects/<projectName>/
      if (cliType === 'iflow' && sessionsPath.includes('projects')) {
        const subdirs = fs.readdirSync(sessionsPath);
        for (const subdir of subdirs) {
          const subdirPath = path.join(sessionsPath, subdir);
          try {
            const stat = fs.statSync(subdirPath);
            if (stat.isDirectory()) {
              sessions.push(...this.scanSessionFiles(cliType, subdirPath, projectPath));
            }
          } catch (error) {
            continue;
          }
        }
        return sessions;
      }

      return this.scanSessionFiles(cliType, sessionsPath, projectPath);
    } catch (error) {
      console.warn(`Warning: Could not scan ${cliType} sessions:`, error.message);
    }

    return sessions;
  }

  scanSessionFiles(cliType, sessionsPath, projectPath) {
    const sessions = [];

    try {
      const files = fs.readdirSync(sessionsPath);
      for (const file of files) {
        if (file.endsWith('.jsonl') && file.startsWith('session-')) {
          try {
            const filePath = path.join(sessionsPath, file);
            const content = fs.readFileSync(filePath, 'utf8');
            const lines = content.trim().split('\n').filter(line => line.trim());
            const messages = lines.map(line => JSON.parse(line));

            if (messages.length === 0) continue;

            const firstMsg = messages[0];
            const lastMsg = messages[messages.length - 1];
            const firstUserMsg = messages.find(m => m.type === 'user' && m.message);

            let title = 'Untitled Session';
            if (firstUserMsg && firstUserMsg.message) {
              let content = firstUserMsg.message.content || '';
              if (typeof content === 'object') {
                content = JSON.stringify(content);
              }
              if (typeof content === 'string' && content.trim()) {
                title = content.substring(0, 100) || title;
              }
            }

            const sessionData = {
              sessionId: firstMsg.sessionId || file.replace('.jsonl', ''),
              title: title,
              messages: messages,
              timestamp: lastMsg.timestamp,
              cwd: firstMsg.cwd,
              projectPath: firstMsg.cwd,
              messageCount: messages.filter(m => m.type === 'user' || m.type === 'assistant').length
            };

            if (this.isProjectSession(sessionData, projectPath)) {
              sessions.push({
                cliType,
                sessionId: sessionData.sessionId,
                title: sessionData.title,
                content: this.extractContent(sessionData),
                updatedAt: new Date(sessionData.timestamp),
                messageCount: sessionData.messageCount,
                projectPath
              });
            }
          } catch (error) {
            console.warn(`Warning: Could not parse ${file}:`, error.message);
          }
        }
      }
    } catch (error) {
      console.warn(`Warning: Could not scan files:`, error.message);
    }

    return sessions;
  }

  scanAllCLISessions(projectPath) {`n    const allSessions = [];`n    const cliPathsMap = pathConfigLoader.getAllCLISessionPaths();`n`n    for (const [cliType, sessionsPaths] of Object.entries(cliPathsMap)) {`n      for (const sessionsPath of sessionsPaths) {`n        const sessions = this.scanSessions(cliType, sessionsPath, projectPath);`n        allSessions.push(...sessions);`n      }`n    }`n`n    return allSessions;`n  }


  isProjectSession(session, projectPath) {
    const sessionProject = session.projectPath || session.cwd;
    if (!sessionProject) return true;

    return sessionProject === projectPath ||
           sessionProject.startsWith(projectPath) ||
           projectPath.startsWith(sessionProject);
  }

  extractContent(sessionData) {
    if (sessionData.messages) {
      return sessionData.messages
        .map(msg => {
          if (msg.message && msg.message.content) {
            return msg.message.content;
          }
          return '';
        })
        .join(' ');
    }
    return '';
  }
}

class SessionFilter {
  applyFilters(sessions, options, projectPath) {
    let filtered = sessions.filter(s => s.projectPath === projectPath);

    if (options.cli) {
      filtered = filtered.filter(s => s.cliType === options.cli);
    }

    if (options.search) {
      const term = options.search.toLowerCase();
      filtered = filtered.filter(s =>
        s.title.toLowerCase().includes(term) ||
        s.content.toLowerCase().includes(term)
      );
    }

    filtered.sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));

    if (options.limit) {
      filtered = filtered.slice(0, options.limit);
    }

    return filtered;
  }
}

class HistoryFormatter {
  formatSummary(sessions) {
    if (sessions.length === 0) {
      return '📭 当前项目暂无历史会话\n\n💡 尝试: /history --search <关键�?';
    }

    let response = `📁 **项目历史会话**\n\n📊 �?${sessions.length} 个\n\n`;

    const byCLI = {};
    sessions.forEach(s => {
      if (!byCLI[s.cliType]) byCLI[s.cliType] = [];
      byCLI[s.cliType].push(s);
    });

    Object.entries(byCLI).forEach(([cli, cliSessions]) => {
      const icon = this.getCLIIcon(cli);
      response += `${icon} **${cli.toUpperCase()}** (${cliSessions.length}�?\n`;
      cliSessions.slice(0, 3).forEach((s, i) => {
        response += `   ${i + 1}. ${s.title.substring(0, 50)}...\n`;
        response += `      💬 ${s.messageCount}条消息\n`;
      });
      if (cliSessions.length > 3) {
        response += `   ... 还有 ${cliSessions.length - 3} 个\n`;
      }
      response += '\n';
    });

    response += '💡 **使用:** stigmergy history --cli <工具> | --search <�? | --format timeline';
    return response;
  }

  formatTimeline(sessions) {
    if (sessions.length === 0) return '📭 暂无会话';
    let response = '�?**时间�?*\n\n';
    sessions.forEach((s, i) => {
      const icon = this.getCLIIcon(s.cliType);
      response += `${i + 1}. ${icon} ${s.title}\n   💬 ${s.messageCount}条\n\n`;
    });
    return response;
  }

  formatDetailed(sessions) {
    if (sessions.length === 0) return '📭 暂无会话';
    let response = '📋 **详细**\n\n';
    sessions.forEach((s, i) => {
      const icon = this.getCLIIcon(s.cliType);
      response += `${i + 1}. ${icon} **${s.title}**\n   🔧 ${s.cliType}\n   💬 ${s.messageCount}条\n\n`;
    });
    return response;
  }

  formatContext(session) {
    if (!session) return '📭 暂无上下�?;
    return `🔄 **上下�?*\n\n${session.title}\n💬 ${session.messageCount}条消息\n\n${session.content.substring(0, 500)}...`;
  }

  getCLIIcon(cliType) {
    const icons = {
      'claude': '🟢',
      'gemini': '🔵',
      'qwen': '🟡',
      'iflow': '🔴',
      'codebuddy': '🟣',
      'codex': '🟪',
      'qodercli': '🟠'
    };
    return icons[cliType] || '🔹';
  }
}

class HistoryQuery {
  constructor() {
    this.scanner = new SessionScanner();
    this.filter = new SessionFilter();
    this.formatter = new HistoryFormatter();
  }

  queryHistory(options, projectPath) {
    try {
      const allSessions = this.scanner.scanAllCLISessions(projectPath);
      const filtered = this.filter.applyFilters(allSessions, options, projectPath);

      let response;
      switch (options.format) {
        case 'timeline':
          response = this.formatter.formatTimeline(filtered);
          break;
        case 'detailed':
          response = this.formatter.formatDetailed(filtered);
          break;
        case 'context':
          response = this.formatter.formatContext(filtered[0]);
          break;
        default:
          response = this.formatter.formatSummary(filtered);
      }

      return {
        response,
        suggestions: ['stigmergy history --format timeline', 'stigmergy history --search <keyword>']
      };
    } catch (error) {
      return {
        response: `�?查询失败: ${error.message}`,
        suggestions: []
      };
    }
  }
}

class IFlowHistoryCommand {
  constructor() {
    this.historyQuery = new HistoryQuery();
  }

  async execute(args, workflow) {
    try {
      const options = this.parseArgs(args);
      const projectPath = workflow.projectPath || 'D:\stigmergy-CLI-Multi-Agents';
      const result = this.historyQuery.queryHistory(options, projectPath);

      return result.response;
    } catch (error) {
      return `�?失败: ${error.message}`;
    }
  }

  parseArgs(args) {
    const options = {
      limit: 10,
      format: 'summary',
      timeRange: 'all',
      cli: null,
      search: null
    };

    for (let i = 0; i < args.length; i++) {
      const arg = args[i];

      if (arg === '--cli' && i + 1 < args.length) {
        options.cli = args[++i];
      } else if (arg === '--search' && i + 1 < args.length) {
        options.search = args[++i];
      } else if (arg === '--limit' && i + 1 < args.length) {
        options.limit = parseInt(args[++i]);
      } else if (arg === '--format' && i + 1 < args.length) {
        options.format = args[++i];
      } else if (arg === '--today') {
        options.timeRange = 'today';
      }
    }

    return options;
  }
}

const historyCommand = {
  name: 'history',
  description: 'Show cross-CLI project history',
  execute: async (args, workflow) => {
    const cmd = new IFlowHistoryCommand();
    return await cmd.execute(args, workflow);
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = historyCommand;
}

if (typeof stigmergy !== 'undefined') {
  stigmergy.addCommand(historyCommand);
}
