// Codex CLI ResumeSession Integration
// Auto-generated by ResumeSession v1.0.4
// Project: D:\stigmergy-CLI-Multi-Agents

const fs = require('fs');
const path = require('path');
const os = require('os');

class SessionScanner {
  scanSessions(cliType, sessionsPath, projectPath) {
    const sessions = [];
    if (!sessionsPath || !projectPath) return sessions;

    try {
      if (!fs.existsSync(sessionsPath)) return sessions;

      // For Codex: scan date-layered structure YYYY/MM/DD/
      if (cliType === 'codex') {
        return this.scanCodexDateLayers(sessionsPath, projectPath);
      }

      return this.scanSessionFiles(cliType, sessionsPath, projectPath);
    } catch (error) {
      console.warn(`Warning: Could not scan ${cliType} sessions:`, error.message);
    }

    return sessions;
  }

  scanCodexDateLayers(sessionsPath, projectPath) {
    const sessions = [];

    try {
      // Scan year directories (YYYY)
      const years = fs.readdirSync(sessionsPath).filter(y => /^\d{4}$/.test(y));
      
      for (const year of years) {
        const yearPath = path.join(sessionsPath, year);
        
        try {
          // Scan month directories (MM)
          const months = fs.readdirSync(yearPath).filter(m => /^\d{2}$/.test(m));
          
          for (const month of months) {
            const monthPath = path.join(yearPath, month);
            
            try {
              // Scan day directories (DD)
              const days = fs.readdirSync(monthPath).filter(d => /^\d{2}$/.test(d));
              
              for (const day of days) {
                const dayPath = path.join(monthPath, day);
                sessions.push(...this.scanSessionFiles('codex', dayPath, projectPath));
              }
            } catch (error) {
              continue;
            }
          }
        } catch (error) {
          continue;
        }
      }
    } catch (error) {
      console.warn(`Warning: Could not scan Codex date layers:`, error.message);
    }

    return sessions;
  }

  scanSessionFiles(cliType, sessionsPath, projectPath) {
    const sessions = [];

    try {
      const files = fs.readdirSync(sessionsPath);
      for (const file of files) {
        if (file.endsWith('.jsonl')) {
          try {
            const filePath = path.join(sessionsPath, file);
            const content = fs.readFileSync(filePath, 'utf8');
            const lines = content.trim().split('\n').filter(line => line.trim());
            const messages = lines.map(line => JSON.parse(line));

            if (messages.length === 0) continue;

            const firstMsg = messages[0];
            const lastMsg = messages[messages.length - 1];
            const firstUserMsg = messages.find(m => m.type === 'user' || m.role === 'user');

            let title = 'Untitled Session';
            if (firstUserMsg) {
              const content = firstUserMsg.content || firstUserMsg.message || firstUserMsg.text;
              if (content) {
                title = content.substring(0, 100) || title;
              }
            }

            const sessionData = {
              sessionId: firstMsg.sessionId || firstMsg.id || file.replace('.jsonl', ''),
              title: title,
              messages: messages,
              timestamp: lastMsg.timestamp || lastMsg.createdAt || fs.statSync(filePath).mtime,
              cwd: firstMsg.cwd || firstMsg.workingDirectory,
              projectPath: firstMsg.cwd || firstMsg.workingDirectory,
              messageCount: messages.filter(m => m.type === 'user' || m.type === 'assistant' || m.role === 'user' || m.role === 'assistant').length
            };

            if (this.isProjectSession(sessionData, projectPath)) {
              sessions.push({
                cliType,
                sessionId: sessionData.sessionId,
                title: sessionData.title,
                content: this.extractContent(sessionData),
                updatedAt: new Date(sessionData.timestamp),
                messageCount: sessionData.messageCount,
                projectPath
              });
            }
          } catch (error) {
            console.warn(`Warning: Could not parse ${file}:`, error.message);
          }
        }
      }
    } catch (error) {
      console.warn(`Warning: Could not scan files:`, error.message);
    }

    return sessions;
  }

  scanAllCLISessions(projectPath) {
    const allSessions = [];
    const cliPaths = this.getCLISessionPaths();

    for (const [cliType, sessionsPath] of Object.entries(cliPaths)) {
      const sessions = this.scanSessions(cliType, sessionsPath, projectPath);
      allSessions.push(...sessions);
    }

    return allSessions;
  }

  getCLISessionPaths() {
    const homeDir = os.homedir();
    return {
      claude: path.join(homeDir, '.claude', 'sessions'),
      gemini: path.join(homeDir, '.gemini', 'sessions'),
      qwen: path.join(homeDir, '.qwen', 'projects'),
      iflow: path.join(homeDir, '.iflow', 'projects'),
      codebuddy: path.join(homeDir, '.codebuddy'),
      qodercli: path.join(homeDir, '.qodercli', 'sessions'),
      codex: path.join(homeDir, '.codex', 'sessions')
    };
  }

  isProjectSession(session, projectPath) {
    const sessionProject = session.projectPath || session.cwd;
    if (!sessionProject) return true;

    return sessionProject === projectPath ||
           sessionProject.startsWith(projectPath) ||
           projectPath.startsWith(sessionProject);
  }

  extractContent(sessionData) {
    if (sessionData.messages) {
      return sessionData.messages
        .map(msg => {
          if (msg.content) return msg.content;
          if (msg.message) return msg.message;
          if (msg.text) return msg.text;
          return '';
        })
        .join(' ');
    }
    return '';
  }
}

class SessionFilter {
  applyFilters(sessions, options, projectPath) {
    let filtered = sessions.filter(s => s.projectPath === projectPath);

    if (options.cli) {
      filtered = filtered.filter(s => s.cliType === options.cli);
    }

    if (options.search) {
      const term = options.search.toLowerCase();
      filtered = filtered.filter(s =>
        s.title.toLowerCase().includes(term) ||
        s.content.toLowerCase().includes(term)
      );
    }

    filtered.sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));

    if (options.limit) {
      filtered = filtered.slice(0, options.limit);
    }

    return filtered;
  }
}

class HistoryFormatter {
  formatSummary(sessions) {
    if (sessions.length === 0) {
      return '📭 当前项目暂无历史会话\n\n💡 尝试: /history --search <关键词>';
    }

    let response = `📁 **项目历史会话**\n\n📊 共 ${sessions.length} 个\n\n`;

    const byCLI = {};
    sessions.forEach(s => {
      if (!byCLI[s.cliType]) byCLI[s.cliType] = [];
      byCLI[s.cliType].push(s);
    });

    Object.entries(byCLI).forEach(([cli, cliSessions]) => {
      const icon = this.getCLIIcon(cli);
      response += `${icon} **${cli.toUpperCase()}** (${cliSessions.length}个)\n`;
      cliSessions.slice(0, 3).forEach((s, i) => {
        response += `   ${i + 1}. ${s.title.substring(0, 50)}...\n`;
        response += `      💬 ${s.messageCount}条消息\n`;
      });
      if (cliSessions.length > 3) {
        response += `   ... 还有 ${cliSessions.length - 3} 个\n`;
      }
      response += '\n';
    });

    response += '💡 **使用:** /history --cli <工具> | --search <词> | --format timeline';
    return response;
  }

  formatTimeline(sessions) {
    if (sessions.length === 0) return '📭 暂无会话';
    let response = '⏰ **时间线**\n\n';
    sessions.forEach((s, i) => {
      const icon = this.getCLIIcon(s.cliType);
      response += `${i + 1}. ${icon} ${s.title}\n   💬 ${s.messageCount}条\n\n`;
    });
    return response;
  }

  formatDetailed(sessions) {
    if (sessions.length === 0) return '📭 暂无会话';
    let response = '📋 **详细**\n\n';
    sessions.forEach((s, i) => {
      const icon = this.getCLIIcon(s.cliType);
      response += `${i + 1}. ${icon} **${s.title}**\n   🔧 ${s.cliType}\n   💬 ${s.messageCount}条\n\n`;
    });
    return response;
  }

  formatContext(session) {
    if (!session) return '📭 暂无上下文';
    return `🔄 **上下文**\n\n${session.title}\n💬 ${session.messageCount}条消息\n\n${session.content.substring(0, 500)}...`;
  }

  getCLIIcon(cliType) {
    const icons = {
      'claude': '🟢',
      'gemini': '🔵',
      'qwen': '🟡',
      'iflow': '🔴',
      'codebuddy': '🟣',
      'codex': '🟪',
      'qodercli': '🟠'
    };
    return icons[cliType] || '🔹';
  }
}

class HistoryQuery {
  constructor() {
    this.scanner = new SessionScanner();
    this.filter = new SessionFilter();
    this.formatter = new HistoryFormatter();
  }

  queryHistory(options, projectPath) {
    try {
      const allSessions = this.scanner.scanAllCLISessions(projectPath);
      const filtered = this.filter.applyFilters(allSessions, options, projectPath);

      let response;
      switch (options.format) {
        case 'timeline':
          response = this.formatter.formatTimeline(filtered);
          break;
        case 'detailed':
          response = this.formatter.formatDetailed(filtered);
          break;
        case 'context':
          response = this.formatter.formatContext(filtered[0]);
          break;
        default:
          response = this.formatter.formatSummary(filtered);
      }

      return {
        response,
        suggestions: ['/history --format timeline', '/history --search <keyword>']
      };
    } catch (error) {
      return {
        response: `❌ 查询失败: ${error.message}`,
        suggestions: []
      };
    }
  }
}

class CodexHistoryHandler {
  constructor() {
    this.historyQuery = new HistoryQuery();
  }

  async processCommand(input, session) {
    if (!input.startsWith('/history')) return null;

    try {
      const options = this.buildQuery(input);
      const result = this.historyQuery.queryHistory(options, 'D:\stigmergy-CLI-Multi-Agents');

      return {
        response: result.response,
        suggestions: result.suggestions
      };
    } catch (error) {
      return {
        response: `❌ 失败: ${error.message}`,
        suggestions: []
      };
    }
  }

  buildQuery(input) {
    const options = {
      limit: 10,
      format: 'summary',
      timeRange: 'all',
      cli: null,
      search: null
    };

    const parts = input.replace(/^\/history\s*/i, '').trim().split(/\s+/).filter(p => p.length > 0);

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i].toLowerCase();

      if (part === '--cli' && i + 1 < parts.length) {
        options.cli = parts[++i];
      } else if (part === '--search' && i + 1 < parts.length) {
        options.search = parts[++i];
      } else if (part === '--limit' && i + 1 < parts.length) {
        options.limit = parseInt(parts[++i]);
      } else if (part === '--format' && i + 1 < parts.length) {
        options.format = parts[++i];
      } else if (part === '--today') {
        options.timeRange = 'today';
      }
    }

    return options;
  }
}

const handler = new CodexHistoryHandler();

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CodexHistoryHandler, handler };
}

if (typeof codex !== 'undefined') {
  codex.addCommand('history', handler.processCommand.bind(handler));
}
