#!/usr/bin/env node
/**
 * OpenCode Integration Installer
 * 为 OpenCode CLI 安装 Stigmergy 集成
 */

const fs = require("fs");
const path = require("path");
const os = require("os");

class OpenCodeIntegrationInstaller {
  constructor() {
    this.homeDir = os.homedir();
    this.opencodeConfigPath = path.join(this.homeDir, ".opencode");
    this.hooksDir = path.join(this.opencodeConfigPath, "hooks");
    this.skillsDir = path.join(this.opencodeConfigPath, "skills");
  }

  /**
   * 安装 OpenCode 集成
   */
  async install() {
    console.log("🔧 开始安装 OpenCode 集成...\n");

    try {
      // 1. 创建必要的目录
      this.createDirectories();

      // 2. 部署 hooks
      this.deployHooks();

      // 3. 部署 skills
      this.deploySkills();

      // 4. 更新配置
      this.updateConfig();

      console.log("\n✅ OpenCode 集成安装完成！");
      console.log("📁 配置目录: " + this.opencodeConfigPath);
      console.log("💡 现在可以在 OpenCode 中使用 /resumesession 命令");

      return { success: true };
    } catch (error) {
      console.error("\n❌ 安装失败:", error.message);
      return { success: false, error: error.message };
    }
  }

  /**
   * 创建必要的目录
   */
  createDirectories() {
    console.log("📁 创建目录结构...");

    const directories = [
      this.opencodeConfigPath,
      this.hooksDir,
      this.skillsDir,
    ];

    for (const dir of directories) {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
        console.log("  ✅ 创建: " + dir);
      } else {
        console.log("  ℹ️  已存在: " + dir);
      }
    }
  }

  /**
   * 部署 hooks
   */
  deployHooks() {
    console.log("\n🔗 部署 hooks...");

    const hookContent = `#!/usr/bin/env node
/**
 * OpenCode AI CLI Integration Hook
 * Generated by Stigmergy CLI v${require("../../../package.json").version}
 */

const fs = require('fs');
const path = require('path');

class OpencodeHook {
  constructor() {
    this.toolName = 'opencode';
    this.configPath = path.join(os.homedir(), '.opencode', 'config.json');
    this.hooksDir = path.join(os.homedir(), '.opencode', 'hooks');
  }

  async onPrompt(prompt) {
    // Handle incoming prompts from other CLI tools
    console.log('[' + this.toolName.toUpperCase() + '] Received cross-CLI prompt: ' + prompt);
    return { handled: true, response: 'Prompt processed by ' + this.toolName };
  }

  async onResponse(response) {
    // Handle responses to be sent to other CLI tools
    console.log('[' + this.toolName.toUpperCase() + '] Sending cross-CLI response');
    return response;
  }
}

module.exports = OpencodeHook;
`;

    const hookFilePath = path.join(this.hooksDir, "opencode_hook.js");

    if (!fs.existsSync(hookFilePath)) {
      fs.writeFileSync(hookFilePath, hookContent, "utf8");
      console.log("  ✅ 创建: opencode_hook.js");
    } else {
      console.log("  ℹ️  已存在: opencode_hook.js");
    }
  }

  /**
   * 部署 skills
   */
  deploySkills() {
    console.log("\n⚡ 部署 skills...");

    // 复制 resumesession 技能
    const sourceSkillPath = path.join(
      __dirname,
      "../../../skills/resumesession/opencode-resume.js",
    );
    const targetSkillPath = path.join(this.skillsDir, "resumesession.js");

    if (fs.existsSync(sourceSkillPath)) {
      const skillContent = fs.readFileSync(sourceSkillPath, "utf8");
      fs.writeFileSync(targetSkillPath, skillContent, "utf8");
      console.log("  ✅ 部署: resumesession.js");
    } else {
      console.log("  ⚠️  未找到: opencode-resume.js");
    }
  }

  /**
   * 更新配置
   */
  updateConfig() {
    console.log("\n⚙️  更新配置...");

    const configPath = path.join(this.opencodeConfigPath, "config.json");
    const hooksJsonPath = path.join(this.opencodeConfigPath, "hooks.json");

    // 更新 hooks.json
    const hooksConfig = {
      cross_cli_adapter: {
        enabled: true,
        supported_tools: [
          "claude",
          "gemini",
          "qwen",
          "iflow",
          "qodercli",
          "codebuddy",
          "copilot",
          "codex",
          "kilocode",
          "kode",
        ],
        trigger_patterns: [
          "use\\s+(\\w+)\\s+to\\s+(.+)",
          "call\\s+(\\w+)\\s+(.+)",
          "ask\\s+(\\w+)\\s+(.+)",
          "stigmergy\\s+(\\w+)\\s+(.+)",
        ],
      },
    };

    fs.writeFileSync(
      hooksJsonPath,
      JSON.stringify(hooksConfig, null, 2),
      "utf8",
    );
    console.log("  ✅ 更新: hooks.json");

    // 更新 config.json
    let config = {};
    if (fs.existsSync(configPath)) {
      try {
        config = JSON.parse(fs.readFileSync(configPath, "utf8"));
      } catch (error) {
        console.log("  ⚠️  无法读取现有配置，将创建新配置");
      }
    }

    // 添加 Stigmergy 配置
    config.stigmergy = {
      enabled: true,
      version: require("../../../package.json").version,
      skills: ["resumesession"],
    };

    fs.writeFileSync(configPath, JSON.stringify(config, null, 2), "utf8");
    console.log("  ✅ 更新: config.json");
  }

  /**
   * 卸载 OpenCode 集成
   */
  async uninstall() {
    console.log("🗑️  开始卸载 OpenCode 集成...\n");

    try {
      // 删除技能文件
      const skillPath = path.join(this.skillsDir, "resumesession.js");
      if (fs.existsSync(skillPath)) {
        fs.unlinkSync(skillPath);
        console.log("  ✅ 删除: resumesession.js");
      }

      console.log("\n✅ OpenCode 集成卸载完成！");
      return { success: true };
    } catch (error) {
      console.error("\n❌ 卸载失败:", error.message);
      return { success: false, error: error.message };
    }
  }
}

// 如果直接运行此脚本
if (require.main === module) {
  const installer = new OpenCodeIntegrationInstaller();
  const args = process.argv.slice(2);

  if (args.includes("--uninstall")) {
    installer.uninstall().then((result) => {
      process.exit(result.success ? 0 : 1);
    });
  } else {
    installer.install().then((result) => {
      process.exit(result.success ? 0 : 1);
    });
  }
}

module.exports = OpenCodeIntegrationInstaller;
