#!/usr/bin/env node
/**
 * Superpowers Command Handler
 * Deploys complete Superpowers plugin to all local CLIs
 */

const chalk = require("chalk");
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");
const os = require("os");

const REPO_URL = "https://github.com/obra/superpowers.git";
const CACHE_DIR = path.join(os.homedir(), ".cache", "stigmergy", "superpowers");

const CLIS = {
  claude: {
    name: "Claude",
    home: ".claude",
    plugin: "plugins/superpowers",
    hooks: "hooks",
  },
  qwen: {
    name: "Qwen",
    home: ".qwen",
    plugin: "extensions/superpowers-qwen",
    hooks: "hooks",
  },
  iflow: {
    name: "iFlow",
    home: ".iflow",
    plugin: "plugins/superpowers",
    hooks: "hooks",
  },
  codebuddy: {
    name: "CodeBuddy",
    home: ".codebuddy",
    plugin: "buddies/superpowers",
    hooks: "hooks",
  },
  opencode: {
    name: "OpenCode",
    home: ".opencode",
    plugin: "plugins/superpowers",
    hooks: "hooks",
  },
  kilocode: {
    name: "KiloCode",
    home: ".kilocode",
    plugin: "plugins/superpowers",
    hooks: "hooks",
  },
  gemini: {
    name: "Gemini",
    home: ".config/gemini",
    plugin: "extensions/superpowers",
    hooks: "extensions",
  },
  codex: {
    name: "Codex",
    home: ".config/codex",
    plugin: "extensions/superpowers",
    hooks: "extensions",
  },
};

async function deployCompleteSuperpowers(options) {
  options = options || {};
  console.log("\n🦸 Superpowers Deployment");
  console.log("=".repeat(50));

  var home = os.homedir();
  var avail = Object.keys(CLIS).filter(function (k) {
    return fs.existsSync(path.join(home, CLIS[k].home));
  });

  if (avail.length === 0) {
    console.log("\n⚠️  No CLIs found\n");
    return;
  }

  console.log(
    "\n📋 CLIs: " +
      avail
        .map(function (k) {
          return CLIS[k].name;
        })
        .join(", ") +
      "\n",
  );

  if (!options.deployOnly) {
    console.log("📦 Cloning obra/superpowers...\n");
    cloneRepo();
  }

  if (!options.cloneOnly) {
    console.log("📦 Deploying to CLIs...\n");
    deploy(avail, home);
  }

  console.log("✅ Done!\n");
}

function cloneRepo() {
  var dir = path.join(CACHE_DIR, "repo");

  if (!fs.existsSync(CACHE_DIR)) fs.mkdirSync(CACHE_DIR, { recursive: true });

  if (fs.existsSync(dir)) {
    try {
      execSync("git fetch origin", { cwd: dir, stdio: "ignore" });
      execSync("git merge --ff-only origin/main", {
        cwd: dir,
        stdio: "ignore",
      });
      console.log("  🔄 Updated\n");
    } catch (e) {
      fs.rmSync(dir, { recursive: true });
      execSync("git clone " + REPO_URL + " " + dir, { stdio: "ignore" });
      console.log("  ✅ Re-cloned\n");
    }
  } else {
    execSync("git clone " + REPO_URL + " " + dir, { stdio: "ignore" });
    console.log("  ✅ Cloned\n");
  }
}

function deploy(avail, home) {
  var repoDir = path.join(CACHE_DIR, "repo");

  for (var i = 0; i < avail.length; i++) {
    var cli = avail[i];
    var cfg = CLIS[cli];
    var cliHome = path.join(home, cfg.home);

    var pluginDir = path.join(cliHome, cfg.plugin);
    var hooksDir = path.join(cliHome, cfg.hooks);
    var skillsDir = path.join(cliHome, "skills");

    fs.mkdirSync(pluginDir, { recursive: true });
    fs.mkdirSync(hooksDir, { recursive: true });
    fs.mkdirSync(skillsDir, { recursive: true });

    copy(
      path.join(repoDir, ".claude-plugin"),
      path.join(pluginDir, ".claude-plugin"),
    );
    copy(path.join(repoDir, "skills"), skillsDir);

    var hooksJson = {
      hooks: {
        sessionStart: {
          name: "SessionStart",
          enabled: true,
          priority: 1,
          matchers: ["startup", "resume", "clear"],
        },
      },
    };
    fs.writeFileSync(
      path.join(hooksDir, "hooks.json"),
      JSON.stringify(hooksJson, null, 2),
    );

    var hookFile = cli === "qwen" ? "session-start.ts" : "session-start.js";
    fs.writeFileSync(path.join(hooksDir, hookFile), HOOK_CONTENT);

    var count = fs.readdirSync(skillsDir).filter(function (f) {
      return !f.startsWith(".");
    }).length;
    console.log("  ✅ " + cfg.name + ": " + count + " skills");
  }
}

function copy(src, dst) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dst, { recursive: true });
  var ents = fs.readdirSync(src, { withFileTypes: true });
  for (var i = 0; i < ents.length; i++) {
    var e = ents[i];
    var s = path.join(src, e.name);
    var d = path.join(dst, e.name);
    if (e.isDirectory()) copy(s, d);
    else
      try {
        fs.copyFileSync(s, d);
      } catch (err) {}
  }
}

var HOOK_CONTENT = [
  "/**",
  " * Superpowers Session Start Hook",
  " * Auto-generated by Stigmergy",
  " */",
  "const fs = require('fs');",
  "const path = require('path');",
  "const os = require('os');",
  "",
  "const SKILLS_ROOT = path.join(os.homedir(), 'skills');",
  "",
  "async function sessionStart(context) {",
  "  try {",
  "    let add = '<EXTREMELY_IMPORTANT> You have superpowers.';",
  "    let sp = path.join(SKILLS_ROOT, 'using-superpowers', 'skill.md');",
  "    if (fs.existsSync(sp)) {",
  "      let c = fs.readFileSync(sp, 'utf8').replace(/\\\\/g, '\\\\\\\\').replace(/\"/g, '\\\\\"').replace(/\\n/g, '\\\\n');",
  "      add += ' **using-superpowers skill**: ' + c;",
  "    }",
  "    add += '</EXTREMELY_IMPORTANT>';",
  "    context.additionalContext = (context.additionalContext || '') + '\\\\n\\\\n' + add;",
  "    console.log('Superpowers injected');",
  "  } catch (e) { console.error(e.message); }",
  "  return context;",
  "}",
  "",
  "module.exports = { sessionStart };",
  "",
].join("\\n");

async function verifySuperpowers() {
  console.log("\\n🔍 Verify\\n");
  var home = os.homedir();
  var ok = 0,
    bad = 0;
  for (var k in CLIS) {
    var c = CLIS[k];
    var h = path.join(home, c.home, c.hooks);
    var has =
      fs.existsSync(path.join(h, "hooks.json")) &&
      (fs.existsSync(path.join(h, "session-start.js")) ||
        fs.existsSync(path.join(h, "session-start.ts")));
    console.log("  " + (has ? "✅" : "❌") + " " + c.name);
    if (has) ok++;
    else bad++;
  }
  console.log("\\n" + ok + " OK, " + bad + " missing\\n");
}

async function cleanSuperpowers() {
  console.log("\\n🗑️ Clean\\n");
  var home = os.homedir();
  for (var k in CLIS) {
    var c = CLIS[k];
    var p = path.join(home, c.home, c.plugin);
    var h = path.join(home, c.home, c.hooks);
    if (fs.existsSync(p)) {
      fs.rmSync(p, { recursive: true });
      console.log("  ✅ " + c.name + " plugin");
    }
    var hf = path.join(h, "hooks.json");
    var sf = path.join(h, "session-start.js");
    var tf = path.join(h, "session-start.ts");
    if (fs.existsSync(hf)) fs.unlinkSync(hf);
    if (fs.existsSync(sf)) fs.unlinkSync(sf);
    if (fs.existsSync(tf)) fs.unlinkSync(tf);
  }
  if (fs.existsSync(CACHE_DIR)) {
    fs.rmSync(CACHE_DIR, { recursive: true });
    console.log("  ✅ Cache");
  }
  console.log("\\n✅ Cleaned\\n");
}

module.exports = {
  deployCompleteSuperpowers: deployCompleteSuperpowers,
  verifySuperpowers: verifySuperpowers,
  cleanSuperpowers: cleanSuperpowers,
};
